# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging
from typing import Any, TYPE_CHECKING
import warnings

from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.eventstream import DuplexEventStream
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.plugins import user_agent_plugin

from .config import Config, Plugin
from .models import (
    DELETE_LEXICON,
    DESCRIBE_VOICES,
    DeleteLexiconInput,
    DeleteLexiconOutput,
    DescribeVoicesInput,
    DescribeVoicesOutput,
    GET_LEXICON,
    GET_SPEECH_SYNTHESIS_TASK,
    GetLexiconInput,
    GetLexiconOutput,
    GetSpeechSynthesisTaskInput,
    GetSpeechSynthesisTaskOutput,
    LIST_LEXICONS,
    LIST_SPEECH_SYNTHESIS_TASKS,
    ListLexiconsInput,
    ListLexiconsOutput,
    ListSpeechSynthesisTasksInput,
    ListSpeechSynthesisTasksOutput,
    PUT_LEXICON,
    PutLexiconInput,
    PutLexiconOutput,
    START_SPEECH_SYNTHESIS_STREAM,
    START_SPEECH_SYNTHESIS_TASK,
    SYNTHESIZE_SPEECH,
    StartSpeechSynthesisStreamActionStream,
    StartSpeechSynthesisStreamEventStream,
    StartSpeechSynthesisStreamInput,
    StartSpeechSynthesisStreamOutput,
    StartSpeechSynthesisTaskInput,
    StartSpeechSynthesisTaskOutput,
    SynthesizeSpeechInput,
    SynthesizeSpeechOutput,
    _StartSpeechSynthesisStreamEventStreamDeserializer,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncPollyClient:
    """
    Amazon Polly is a web service that makes it easy to synthesize speech
    from text.

    The Amazon Polly service provides API operations for synthesizing
    high-quality speech from plain text and Speech Synthesis Markup Language
    (SSML), along with managing pronunciations lexicons that enable you to
    get the best results for your application domain.
    """

    def __init__(
        self, config: Config | None = None, plugins: list[Plugin] | None = None
    ):
        """
        Constructor for `AsyncPollyClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables that modify the configuration dynamically. These
                can be used to set defaults, for example.
        """
        self._config = config or Config()

        client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]
        if plugins:
            client_plugins.extend(plugins)

        for plugin in client_plugins:
            plugin(self._config)

        self._retry_strategy_resolver = RetryStrategyResolver()

    async def delete_lexicon(
        self, input: DeleteLexiconInput, plugins: list[Plugin] | None = None
    ) -> DeleteLexiconOutput:
        """
        Deletes the specified pronunciation lexicon stored in an Amazon Web
        Services Region. A lexicon which has been deleted is not available for
        speech synthesis, nor is it possible to retrieve it using either the
        `GetLexicon` or `ListLexicon` APIs.

        For more information, see [Managing
        Lexicons](https://docs.aws.amazon.com/polly/latest/dg/managing-lexicons.html).

        Args:
            input:
                An instance of `DeleteLexiconInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteLexiconOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DELETE_LEXICON,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def describe_voices(
        self, input: DescribeVoicesInput, plugins: list[Plugin] | None = None
    ) -> DescribeVoicesOutput:
        """
        Returns the list of voices that are available for use when requesting
        speech synthesis. Each voice speaks a specified language, is either male
        or female, and is identified by an ID, which is the ASCII version of the
        voice name.

        When synthesizing speech ( `SynthesizeSpeech` ), you provide the voice
        ID for the voice you want from the list of voices returned by
        `DescribeVoices`.

        For example, you want your news reader application to read news in a
        specific language, but giving a user the option to choose the voice.
        Using the `DescribeVoices` operation you can provide the user with a
        list of available voices to select from.

        You can optionally specify a language code to filter the available
        voices. For example, if you specify `en-US`, the operation returns a
        list of all available US English voices.

        This operation requires permissions to perform the
        `polly:DescribeVoices` action.

        Args:
            input:
                An instance of `DescribeVoicesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DescribeVoicesOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DESCRIBE_VOICES,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_lexicon(
        self, input: GetLexiconInput, plugins: list[Plugin] | None = None
    ) -> GetLexiconOutput:
        """
        Returns the content of the specified pronunciation lexicon stored in an
        Amazon Web Services Region. For more information, see [Managing
        Lexicons](https://docs.aws.amazon.com/polly/latest/dg/managing-lexicons.html).

        Args:
            input:
                An instance of `GetLexiconInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetLexiconOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_LEXICON,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_speech_synthesis_task(
        self, input: GetSpeechSynthesisTaskInput, plugins: list[Plugin] | None = None
    ) -> GetSpeechSynthesisTaskOutput:
        """
        Retrieves a specific SpeechSynthesisTask object based on its TaskID.
        This object contains information about the given speech synthesis task,
        including the status of the task, and a link to the S3 bucket containing
        the output of the task.

        Args:
            input:
                An instance of `GetSpeechSynthesisTaskInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetSpeechSynthesisTaskOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_SPEECH_SYNTHESIS_TASK,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_lexicons(
        self, input: ListLexiconsInput, plugins: list[Plugin] | None = None
    ) -> ListLexiconsOutput:
        """
        Returns a list of pronunciation lexicons stored in an Amazon Web
        Services Region. For more information, see [Managing
        Lexicons](https://docs.aws.amazon.com/polly/latest/dg/managing-lexicons.html).

        Args:
            input:
                An instance of `ListLexiconsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListLexiconsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_LEXICONS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_speech_synthesis_tasks(
        self, input: ListSpeechSynthesisTasksInput, plugins: list[Plugin] | None = None
    ) -> ListSpeechSynthesisTasksOutput:
        """
        Returns a list of SpeechSynthesisTask objects ordered by their creation
        date. This operation can filter the tasks by their status, for example,
        allowing users to list only tasks that are completed.

        Args:
            input:
                An instance of `ListSpeechSynthesisTasksInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListSpeechSynthesisTasksOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_SPEECH_SYNTHESIS_TASKS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def put_lexicon(
        self, input: PutLexiconInput, plugins: list[Plugin] | None = None
    ) -> PutLexiconOutput:
        """
        Stores a pronunciation lexicon in an Amazon Web Services Region. If a
        lexicon with the same name already exists in the region, it is
        overwritten by the new lexicon. Lexicon operations have eventual
        consistency, therefore, it might take some time before the lexicon is
        available to the SynthesizeSpeech operation.

        For more information, see [Managing
        Lexicons](https://docs.aws.amazon.com/polly/latest/dg/managing-lexicons.html).

        Args:
            input:
                An instance of `PutLexiconInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutLexiconOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=PUT_LEXICON,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def start_speech_synthesis_stream(
        self,
        input: StartSpeechSynthesisStreamInput,
        plugins: list[Plugin] | None = None,
    ) -> DuplexEventStream[
        StartSpeechSynthesisStreamActionStream,
        StartSpeechSynthesisStreamEventStream,
        StartSpeechSynthesisStreamOutput,
    ]:
        """
        Synthesizes UTF-8 input, plain text, or SSML over a bidirectional
        streaming connection. Specify synthesis parameters in HTTP/2 headers,
        send text incrementally as events on the input stream, and receive
        synthesized audio as it becomes available.

        This operation serves as a bidirectional counterpart to
        `SynthesizeSpeech`:

        - [SynthesizeSpeech](https://docs.aws.amazon.com/polly/latest/API/API_SynthesizeSpeech.html)

        Args:
            input:
                An instance of `StartSpeechSynthesisStreamInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            A `DuplexEventStream` for bidirectional streaming.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=START_SPEECH_SYNTHESIS_STREAM,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline.duplex_stream(
            call,
            StartSpeechSynthesisStreamActionStream,
            StartSpeechSynthesisStreamEventStream,
            _StartSpeechSynthesisStreamEventStreamDeserializer().deserialize,
        )

    async def start_speech_synthesis_task(
        self, input: StartSpeechSynthesisTaskInput, plugins: list[Plugin] | None = None
    ) -> StartSpeechSynthesisTaskOutput:
        """
        Allows the creation of an asynchronous synthesis task, by starting a new
        `SpeechSynthesisTask`. This operation requires all the standard
        information needed for speech synthesis, plus the name of an Amazon S3
        bucket for the service to store the output of the synthesis task and two
        optional parameters (`OutputS3KeyPrefix` and `SnsTopicArn`). Once the
        synthesis task is created, this operation will return a
        `SpeechSynthesisTask` object, which will include an identifier of this
        task as well as the current status. The `SpeechSynthesisTask` object is
        available for 72 hours after starting the asynchronous synthesis task.

        Args:
            input:
                An instance of `StartSpeechSynthesisTaskInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `StartSpeechSynthesisTaskOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=START_SPEECH_SYNTHESIS_TASK,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def synthesize_speech(
        self, input: SynthesizeSpeechInput, plugins: list[Plugin] | None = None
    ) -> SynthesizeSpeechOutput:
        """
        Synthesizes UTF-8 input, plain text or SSML, to a stream of bytes. SSML
        input must be valid, well-formed SSML. Some alphabets might not be
        available with all the voices (for example, Cyrillic might not be read
        at all by English voices) unless phoneme mapping is used. For more
        information, see [How it
        Works](https://docs.aws.amazon.com/polly/latest/dg/how-text-to-speech-works.html).

        Args:
            input:
                An instance of `SynthesizeSpeechInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `SynthesizeSpeechOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=SYNTHESIZE_SPEECH,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)


if TYPE_CHECKING:
    # Deprecated alias for backwards compatibility, to be removed.
    PollyClient = AsyncPollyClient


def __getattr__(name: str) -> Any:
    if name == "PollyClient":
        warnings.warn(
            "PollyClient is deprecated, use AsyncPollyClient instead. "
            "This alias will be removed in a future version.",
            DeprecationWarning,
            stacklevel=2,
        )
        return AsyncPollyClient
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
