# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
from typing import Any, Callable, TypeAlias, Union

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, ClientTransport, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.aio.interfaces.retries import RetryStrategy
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces import URI
from smithy_core.retries import RetryStrategyOptions
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient
from smithy_http.interfaces import HTTPRequestConfiguration

from ._private.schemas import GUARD_DUTY_API_SERVICE as _SCHEMA_GUARD_DUTY_API_SERVICE
from .auth import HTTPAuthSchemeResolver
from .models import (
    AcceptAdministratorInvitationInput,
    AcceptAdministratorInvitationOutput,
    AcceptInvitationInput,
    AcceptInvitationOutput,
    ArchiveFindingsInput,
    ArchiveFindingsOutput,
    CreateDetectorInput,
    CreateDetectorOutput,
    CreateFilterInput,
    CreateFilterOutput,
    CreateIPSetInput,
    CreateIPSetOutput,
    CreateInvestigationInput,
    CreateInvestigationOutput,
    CreateMalwareProtectionPlanInput,
    CreateMalwareProtectionPlanOutput,
    CreateMembersInput,
    CreateMembersOutput,
    CreatePublishingDestinationInput,
    CreatePublishingDestinationOutput,
    CreateSampleFindingsInput,
    CreateSampleFindingsOutput,
    CreateThreatEntitySetInput,
    CreateThreatEntitySetOutput,
    CreateThreatIntelSetInput,
    CreateThreatIntelSetOutput,
    CreateTrustedEntitySetInput,
    CreateTrustedEntitySetOutput,
    DeclineInvitationsInput,
    DeclineInvitationsOutput,
    DeleteDetectorInput,
    DeleteDetectorOutput,
    DeleteFilterInput,
    DeleteFilterOutput,
    DeleteIPSetInput,
    DeleteIPSetOutput,
    DeleteInvitationsInput,
    DeleteInvitationsOutput,
    DeleteMalwareProtectionPlanInput,
    DeleteMalwareProtectionPlanOutput,
    DeleteMembersInput,
    DeleteMembersOutput,
    DeletePublishingDestinationInput,
    DeletePublishingDestinationOutput,
    DeleteThreatEntitySetInput,
    DeleteThreatEntitySetOutput,
    DeleteThreatIntelSetInput,
    DeleteThreatIntelSetOutput,
    DeleteTrustedEntitySetInput,
    DeleteTrustedEntitySetOutput,
    DescribeMalwareScansInput,
    DescribeMalwareScansOutput,
    DescribeOrganizationConfigurationInput,
    DescribeOrganizationConfigurationOutput,
    DescribePublishingDestinationInput,
    DescribePublishingDestinationOutput,
    DisableOrganizationAdminAccountInput,
    DisableOrganizationAdminAccountOutput,
    DisassociateFromAdministratorAccountInput,
    DisassociateFromAdministratorAccountOutput,
    DisassociateFromMasterAccountInput,
    DisassociateFromMasterAccountOutput,
    DisassociateMembersInput,
    DisassociateMembersOutput,
    EnableOrganizationAdminAccountInput,
    EnableOrganizationAdminAccountOutput,
    GetAdministratorAccountInput,
    GetAdministratorAccountOutput,
    GetCoverageStatisticsInput,
    GetCoverageStatisticsOutput,
    GetDetectorInput,
    GetDetectorOutput,
    GetFilterInput,
    GetFilterOutput,
    GetFindingsInput,
    GetFindingsOutput,
    GetFindingsStatisticsInput,
    GetFindingsStatisticsOutput,
    GetIPSetInput,
    GetIPSetOutput,
    GetInvestigationInput,
    GetInvestigationOutput,
    GetInvitationsCountInput,
    GetInvitationsCountOutput,
    GetMalwareProtectionPlanInput,
    GetMalwareProtectionPlanOutput,
    GetMalwareScanInput,
    GetMalwareScanOutput,
    GetMalwareScanSettingsInput,
    GetMalwareScanSettingsOutput,
    GetMasterAccountInput,
    GetMasterAccountOutput,
    GetMemberDetectorsInput,
    GetMemberDetectorsOutput,
    GetMembersInput,
    GetMembersOutput,
    GetOrganizationStatisticsInput,
    GetOrganizationStatisticsOutput,
    GetRemainingFreeTrialDaysInput,
    GetRemainingFreeTrialDaysOutput,
    GetThreatEntitySetInput,
    GetThreatEntitySetOutput,
    GetThreatIntelSetInput,
    GetThreatIntelSetOutput,
    GetTrustedEntitySetInput,
    GetTrustedEntitySetOutput,
    GetUsageStatisticsInput,
    GetUsageStatisticsOutput,
    InviteMembersInput,
    InviteMembersOutput,
    ListCoverageInput,
    ListCoverageOutput,
    ListDetectorsInput,
    ListDetectorsOutput,
    ListFiltersInput,
    ListFiltersOutput,
    ListFindingsInput,
    ListFindingsOutput,
    ListIPSetsInput,
    ListIPSetsOutput,
    ListInvestigationsInput,
    ListInvestigationsOutput,
    ListInvitationsInput,
    ListInvitationsOutput,
    ListMalwareProtectionPlansInput,
    ListMalwareProtectionPlansOutput,
    ListMalwareScansInput,
    ListMalwareScansOutput,
    ListMembersInput,
    ListMembersOutput,
    ListOrganizationAdminAccountsInput,
    ListOrganizationAdminAccountsOutput,
    ListPublishingDestinationsInput,
    ListPublishingDestinationsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    ListThreatEntitySetsInput,
    ListThreatEntitySetsOutput,
    ListThreatIntelSetsInput,
    ListThreatIntelSetsOutput,
    ListTrustedEntitySetsInput,
    ListTrustedEntitySetsOutput,
    SendObjectMalwareScanInput,
    SendObjectMalwareScanOutput,
    StartMalwareScanInput,
    StartMalwareScanOutput,
    StartMonitoringMembersInput,
    StartMonitoringMembersOutput,
    StopMonitoringMembersInput,
    StopMonitoringMembersOutput,
    TagResourceInput,
    TagResourceOutput,
    UnarchiveFindingsInput,
    UnarchiveFindingsOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateDetectorInput,
    UpdateDetectorOutput,
    UpdateFilterInput,
    UpdateFilterOutput,
    UpdateFindingsFeedbackInput,
    UpdateFindingsFeedbackOutput,
    UpdateIPSetInput,
    UpdateIPSetOutput,
    UpdateMalwareProtectionPlanInput,
    UpdateMalwareProtectionPlanOutput,
    UpdateMalwareScanSettingsInput,
    UpdateMalwareScanSettingsOutput,
    UpdateMemberDetectorsInput,
    UpdateMemberDetectorsOutput,
    UpdateOrganizationConfigurationInput,
    UpdateOrganizationConfigurationOutput,
    UpdatePublishingDestinationInput,
    UpdatePublishingDestinationOutput,
    UpdateThreatEntitySetInput,
    UpdateThreatEntitySetOutput,
    UpdateThreatIntelSetInput,
    UpdateThreatIntelSetOutput,
    UpdateTrustedEntitySetInput,
    UpdateTrustedEntitySetOutput,
)


_ServiceInterceptor = Union[
    Interceptor[
        AcceptAdministratorInvitationInput,
        AcceptAdministratorInvitationOutput,
        Any,
        Any,
    ],
    Interceptor[AcceptInvitationInput, AcceptInvitationOutput, Any, Any],
    Interceptor[ArchiveFindingsInput, ArchiveFindingsOutput, Any, Any],
    Interceptor[CreateDetectorInput, CreateDetectorOutput, Any, Any],
    Interceptor[CreateFilterInput, CreateFilterOutput, Any, Any],
    Interceptor[CreateInvestigationInput, CreateInvestigationOutput, Any, Any],
    Interceptor[CreateIPSetInput, CreateIPSetOutput, Any, Any],
    Interceptor[
        CreateMalwareProtectionPlanInput, CreateMalwareProtectionPlanOutput, Any, Any
    ],
    Interceptor[CreateMembersInput, CreateMembersOutput, Any, Any],
    Interceptor[
        CreatePublishingDestinationInput, CreatePublishingDestinationOutput, Any, Any
    ],
    Interceptor[CreateSampleFindingsInput, CreateSampleFindingsOutput, Any, Any],
    Interceptor[CreateThreatEntitySetInput, CreateThreatEntitySetOutput, Any, Any],
    Interceptor[CreateThreatIntelSetInput, CreateThreatIntelSetOutput, Any, Any],
    Interceptor[CreateTrustedEntitySetInput, CreateTrustedEntitySetOutput, Any, Any],
    Interceptor[DeclineInvitationsInput, DeclineInvitationsOutput, Any, Any],
    Interceptor[DeleteDetectorInput, DeleteDetectorOutput, Any, Any],
    Interceptor[DeleteFilterInput, DeleteFilterOutput, Any, Any],
    Interceptor[DeleteInvitationsInput, DeleteInvitationsOutput, Any, Any],
    Interceptor[DeleteIPSetInput, DeleteIPSetOutput, Any, Any],
    Interceptor[
        DeleteMalwareProtectionPlanInput, DeleteMalwareProtectionPlanOutput, Any, Any
    ],
    Interceptor[DeleteMembersInput, DeleteMembersOutput, Any, Any],
    Interceptor[
        DeletePublishingDestinationInput, DeletePublishingDestinationOutput, Any, Any
    ],
    Interceptor[DeleteThreatEntitySetInput, DeleteThreatEntitySetOutput, Any, Any],
    Interceptor[DeleteThreatIntelSetInput, DeleteThreatIntelSetOutput, Any, Any],
    Interceptor[DeleteTrustedEntitySetInput, DeleteTrustedEntitySetOutput, Any, Any],
    Interceptor[DescribeMalwareScansInput, DescribeMalwareScansOutput, Any, Any],
    Interceptor[
        DescribeOrganizationConfigurationInput,
        DescribeOrganizationConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        DescribePublishingDestinationInput,
        DescribePublishingDestinationOutput,
        Any,
        Any,
    ],
    Interceptor[
        DisableOrganizationAdminAccountInput,
        DisableOrganizationAdminAccountOutput,
        Any,
        Any,
    ],
    Interceptor[
        DisassociateFromAdministratorAccountInput,
        DisassociateFromAdministratorAccountOutput,
        Any,
        Any,
    ],
    Interceptor[
        DisassociateFromMasterAccountInput,
        DisassociateFromMasterAccountOutput,
        Any,
        Any,
    ],
    Interceptor[DisassociateMembersInput, DisassociateMembersOutput, Any, Any],
    Interceptor[
        EnableOrganizationAdminAccountInput,
        EnableOrganizationAdminAccountOutput,
        Any,
        Any,
    ],
    Interceptor[GetAdministratorAccountInput, GetAdministratorAccountOutput, Any, Any],
    Interceptor[GetCoverageStatisticsInput, GetCoverageStatisticsOutput, Any, Any],
    Interceptor[GetDetectorInput, GetDetectorOutput, Any, Any],
    Interceptor[GetFilterInput, GetFilterOutput, Any, Any],
    Interceptor[GetFindingsInput, GetFindingsOutput, Any, Any],
    Interceptor[GetFindingsStatisticsInput, GetFindingsStatisticsOutput, Any, Any],
    Interceptor[GetInvestigationInput, GetInvestigationOutput, Any, Any],
    Interceptor[GetInvitationsCountInput, GetInvitationsCountOutput, Any, Any],
    Interceptor[GetIPSetInput, GetIPSetOutput, Any, Any],
    Interceptor[
        GetMalwareProtectionPlanInput, GetMalwareProtectionPlanOutput, Any, Any
    ],
    Interceptor[GetMalwareScanInput, GetMalwareScanOutput, Any, Any],
    Interceptor[GetMalwareScanSettingsInput, GetMalwareScanSettingsOutput, Any, Any],
    Interceptor[GetMasterAccountInput, GetMasterAccountOutput, Any, Any],
    Interceptor[GetMemberDetectorsInput, GetMemberDetectorsOutput, Any, Any],
    Interceptor[GetMembersInput, GetMembersOutput, Any, Any],
    Interceptor[
        GetOrganizationStatisticsInput, GetOrganizationStatisticsOutput, Any, Any
    ],
    Interceptor[
        GetRemainingFreeTrialDaysInput, GetRemainingFreeTrialDaysOutput, Any, Any
    ],
    Interceptor[GetThreatEntitySetInput, GetThreatEntitySetOutput, Any, Any],
    Interceptor[GetThreatIntelSetInput, GetThreatIntelSetOutput, Any, Any],
    Interceptor[GetTrustedEntitySetInput, GetTrustedEntitySetOutput, Any, Any],
    Interceptor[GetUsageStatisticsInput, GetUsageStatisticsOutput, Any, Any],
    Interceptor[InviteMembersInput, InviteMembersOutput, Any, Any],
    Interceptor[ListCoverageInput, ListCoverageOutput, Any, Any],
    Interceptor[ListDetectorsInput, ListDetectorsOutput, Any, Any],
    Interceptor[ListFiltersInput, ListFiltersOutput, Any, Any],
    Interceptor[ListFindingsInput, ListFindingsOutput, Any, Any],
    Interceptor[ListInvestigationsInput, ListInvestigationsOutput, Any, Any],
    Interceptor[ListInvitationsInput, ListInvitationsOutput, Any, Any],
    Interceptor[ListIPSetsInput, ListIPSetsOutput, Any, Any],
    Interceptor[
        ListMalwareProtectionPlansInput, ListMalwareProtectionPlansOutput, Any, Any
    ],
    Interceptor[ListMalwareScansInput, ListMalwareScansOutput, Any, Any],
    Interceptor[ListMembersInput, ListMembersOutput, Any, Any],
    Interceptor[
        ListOrganizationAdminAccountsInput,
        ListOrganizationAdminAccountsOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListPublishingDestinationsInput, ListPublishingDestinationsOutput, Any, Any
    ],
    Interceptor[ListTagsForResourceInput, ListTagsForResourceOutput, Any, Any],
    Interceptor[ListThreatEntitySetsInput, ListThreatEntitySetsOutput, Any, Any],
    Interceptor[ListThreatIntelSetsInput, ListThreatIntelSetsOutput, Any, Any],
    Interceptor[ListTrustedEntitySetsInput, ListTrustedEntitySetsOutput, Any, Any],
    Interceptor[SendObjectMalwareScanInput, SendObjectMalwareScanOutput, Any, Any],
    Interceptor[StartMalwareScanInput, StartMalwareScanOutput, Any, Any],
    Interceptor[StartMonitoringMembersInput, StartMonitoringMembersOutput, Any, Any],
    Interceptor[StopMonitoringMembersInput, StopMonitoringMembersOutput, Any, Any],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[UnarchiveFindingsInput, UnarchiveFindingsOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[UpdateDetectorInput, UpdateDetectorOutput, Any, Any],
    Interceptor[UpdateFilterInput, UpdateFilterOutput, Any, Any],
    Interceptor[UpdateFindingsFeedbackInput, UpdateFindingsFeedbackOutput, Any, Any],
    Interceptor[UpdateIPSetInput, UpdateIPSetOutput, Any, Any],
    Interceptor[
        UpdateMalwareProtectionPlanInput, UpdateMalwareProtectionPlanOutput, Any, Any
    ],
    Interceptor[
        UpdateMalwareScanSettingsInput, UpdateMalwareScanSettingsOutput, Any, Any
    ],
    Interceptor[UpdateMemberDetectorsInput, UpdateMemberDetectorsOutput, Any, Any],
    Interceptor[
        UpdateOrganizationConfigurationInput,
        UpdateOrganizationConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdatePublishingDestinationInput, UpdatePublishingDestinationOutput, Any, Any
    ],
    Interceptor[UpdateThreatEntitySetInput, UpdateThreatEntitySetOutput, Any, Any],
    Interceptor[UpdateThreatIntelSetInput, UpdateThreatIntelSetOutput, Any, Any],
    Interceptor[UpdateTrustedEntitySetInput, UpdateTrustedEntitySetOutput, Any, Any],
]


@dataclass(init=False)
class Config:
    """Configuration for GuardDuty."""

    auth_scheme_resolver: HTTPAuthSchemeResolver
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]]
    """A map of auth scheme ids to auth schemes."""

    aws_access_key_id: str | None
    """The identifier for a secret access key."""

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    )
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    aws_secret_access_key: str | None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None
    """An access key ID that identifies temporary security credentials."""

    endpoint_resolver: EndpointResolver
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    endpoint_uri: str | URI | None
    """A static URI to route requests to."""

    http_request_config: HTTPRequestConfiguration | None
    """Configuration for individual HTTP requests."""

    interceptors: list[_ServiceInterceptor]
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    protocol: ClientProtocol[Any, Any] | None
    """The protocol to serialize and deserialize requests with."""

    region: str | None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    retry_strategy: RetryStrategy | RetryStrategyOptions | None
    """
    The retry strategy or options for configuring retry behavior. Can be
    either a configured RetryStrategy or RetryStrategyOptions to create one.
    """

    sdk_ua_app_id: str | None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    transport: ClientTransport[Any, Any] | None
    """The transport to use to send requests (e.g. an HTTP client)."""

    user_agent_extra: str | None
    """Additional suffix to be added to the User-Agent header."""

    def __init__(
        self,
        *,
        auth_scheme_resolver: HTTPAuthSchemeResolver | None = None,
        auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None,
        aws_access_key_id: str | None = None,
        aws_credentials_identity_resolver: IdentityResolver[
            AWSCredentialsIdentity, AWSIdentityProperties
        ]
        | None = None,
        aws_secret_access_key: str | None = None,
        aws_session_token: str | None = None,
        endpoint_resolver: EndpointResolver | None = None,
        endpoint_uri: str | URI | None = None,
        http_request_config: HTTPRequestConfiguration | None = None,
        interceptors: list[_ServiceInterceptor] | None = None,
        protocol: ClientProtocol[Any, Any] | None = None,
        region: str | None = None,
        retry_strategy: RetryStrategy | RetryStrategyOptions | None = None,
        sdk_ua_app_id: str | None = None,
        transport: ClientTransport[Any, Any] | None = None,
        user_agent_extra: str | None = None,
    ):
        self.auth_scheme_resolver = auth_scheme_resolver or HTTPAuthSchemeResolver()
        self.auth_schemes = auth_schemes or {
            ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="guardduty")
        }
        self.aws_access_key_id = aws_access_key_id
        self.aws_credentials_identity_resolver = aws_credentials_identity_resolver
        self.aws_secret_access_key = aws_secret_access_key
        self.aws_session_token = aws_session_token
        self.endpoint_resolver = endpoint_resolver or StandardRegionalEndpointsResolver(
            endpoint_prefix="guardduty"
        )
        self.endpoint_uri = endpoint_uri
        self.http_request_config = http_request_config
        self.interceptors = interceptors or []
        self.protocol = protocol or RestJsonClientProtocol(
            _SCHEMA_GUARD_DUTY_API_SERVICE
        )
        self.region = region
        self.retry_strategy = retry_strategy
        self.sdk_ua_app_id = sdk_ua_app_id
        self.transport = transport or AIOHTTPClient()
        self.user_agent_extra = user_agent_extra

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Sets the implementation of an auth scheme.

        Using this method ensures the correct key is used.

        Args:
            scheme:
                The auth scheme to add.
        """
        self.auth_schemes[scheme.scheme_id] = scheme


Plugin: TypeAlias = Callable[[Config], None]
"""A callable that allows customizing the config object on each request."""
