# Code generated by smithy-python-codegen DO NOT EDIT.

from typing import Any

from smithy_core.interceptors import Interceptor, RequestContext
from smithy_http import Field
from smithy_http.aio.interfaces import HTTPRequest

from .config import Config


class _AcceptHeaderInterceptor(Interceptor[Any, Any, HTTPRequest, None]):
    """Sets the Accept header to application/json if not already present."""

    def modify_before_signing(
        self, context: RequestContext[Any, HTTPRequest]
    ) -> HTTPRequest:
        request = context.transport_request
        if "Accept" not in request.fields:
            request.fields.set_field(Field(name="Accept", values=["application/json"]))
        return request


def accept_header_plugin(config: Config):
    config.interceptors.append(_AcceptHeaderInterceptor())
