# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
from typing import Any, Callable, TypeAlias, Union

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, ClientTransport, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.aio.interfaces.retries import RetryStrategy
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces import URI
from smithy_core.retries import RetryStrategyOptions
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient
from smithy_http.interfaces import HTTPRequestConfiguration

from ._private.schemas import (
    BACKPLANE_CONTROL_SERVICE as _SCHEMA_BACKPLANE_CONTROL_SERVICE,
)
from .auth import HTTPAuthSchemeResolver
from .models import (
    CreateApiKeyInput,
    CreateApiKeyOutput,
    CreateAuthorizerInput,
    CreateAuthorizerOutput,
    CreateBasePathMappingInput,
    CreateBasePathMappingOutput,
    CreateDeploymentInput,
    CreateDeploymentOutput,
    CreateDocumentationPartInput,
    CreateDocumentationPartOutput,
    CreateDocumentationVersionInput,
    CreateDocumentationVersionOutput,
    CreateDomainNameAccessAssociationInput,
    CreateDomainNameAccessAssociationOutput,
    CreateDomainNameInput,
    CreateDomainNameOutput,
    CreateModelInput,
    CreateModelOutput,
    CreateRequestValidatorInput,
    CreateRequestValidatorOutput,
    CreateResourceInput,
    CreateResourceOutput,
    CreateRestApiInput,
    CreateRestApiOutput,
    CreateStageInput,
    CreateStageOutput,
    CreateUsagePlanInput,
    CreateUsagePlanKeyInput,
    CreateUsagePlanKeyOutput,
    CreateUsagePlanOutput,
    CreateVpcLinkInput,
    CreateVpcLinkOutput,
    DeleteApiKeyInput,
    DeleteApiKeyOutput,
    DeleteAuthorizerInput,
    DeleteAuthorizerOutput,
    DeleteBasePathMappingInput,
    DeleteBasePathMappingOutput,
    DeleteClientCertificateInput,
    DeleteClientCertificateOutput,
    DeleteDeploymentInput,
    DeleteDeploymentOutput,
    DeleteDocumentationPartInput,
    DeleteDocumentationPartOutput,
    DeleteDocumentationVersionInput,
    DeleteDocumentationVersionOutput,
    DeleteDomainNameAccessAssociationInput,
    DeleteDomainNameAccessAssociationOutput,
    DeleteDomainNameInput,
    DeleteDomainNameOutput,
    DeleteGatewayResponseInput,
    DeleteGatewayResponseOutput,
    DeleteIntegrationInput,
    DeleteIntegrationOutput,
    DeleteIntegrationResponseInput,
    DeleteIntegrationResponseOutput,
    DeleteMethodInput,
    DeleteMethodOutput,
    DeleteMethodResponseInput,
    DeleteMethodResponseOutput,
    DeleteModelInput,
    DeleteModelOutput,
    DeleteRequestValidatorInput,
    DeleteRequestValidatorOutput,
    DeleteResourceInput,
    DeleteResourceOutput,
    DeleteRestApiInput,
    DeleteRestApiOutput,
    DeleteStageInput,
    DeleteStageOutput,
    DeleteUsagePlanInput,
    DeleteUsagePlanKeyInput,
    DeleteUsagePlanKeyOutput,
    DeleteUsagePlanOutput,
    DeleteVpcLinkInput,
    DeleteVpcLinkOutput,
    FlushStageAuthorizersCacheInput,
    FlushStageAuthorizersCacheOutput,
    FlushStageCacheInput,
    FlushStageCacheOutput,
    GenerateClientCertificateInput,
    GenerateClientCertificateOutput,
    GetAccountInput,
    GetAccountOutput,
    GetApiKeyInput,
    GetApiKeyOutput,
    GetApiKeysInput,
    GetApiKeysOutput,
    GetAuthorizerInput,
    GetAuthorizerOutput,
    GetAuthorizersInput,
    GetAuthorizersOutput,
    GetBasePathMappingInput,
    GetBasePathMappingOutput,
    GetBasePathMappingsInput,
    GetBasePathMappingsOutput,
    GetClientCertificateInput,
    GetClientCertificateOutput,
    GetClientCertificatesInput,
    GetClientCertificatesOutput,
    GetDeploymentInput,
    GetDeploymentOutput,
    GetDeploymentsInput,
    GetDeploymentsOutput,
    GetDocumentationPartInput,
    GetDocumentationPartOutput,
    GetDocumentationPartsInput,
    GetDocumentationPartsOutput,
    GetDocumentationVersionInput,
    GetDocumentationVersionOutput,
    GetDocumentationVersionsInput,
    GetDocumentationVersionsOutput,
    GetDomainNameAccessAssociationsInput,
    GetDomainNameAccessAssociationsOutput,
    GetDomainNameInput,
    GetDomainNameOutput,
    GetDomainNamesInput,
    GetDomainNamesOutput,
    GetExportInput,
    GetExportOutput,
    GetGatewayResponseInput,
    GetGatewayResponseOutput,
    GetGatewayResponsesInput,
    GetGatewayResponsesOutput,
    GetIntegrationInput,
    GetIntegrationOutput,
    GetIntegrationResponseInput,
    GetIntegrationResponseOutput,
    GetMethodInput,
    GetMethodOutput,
    GetMethodResponseInput,
    GetMethodResponseOutput,
    GetModelInput,
    GetModelOutput,
    GetModelTemplateInput,
    GetModelTemplateOutput,
    GetModelsInput,
    GetModelsOutput,
    GetRequestValidatorInput,
    GetRequestValidatorOutput,
    GetRequestValidatorsInput,
    GetRequestValidatorsOutput,
    GetResourceInput,
    GetResourceOutput,
    GetResourcesInput,
    GetResourcesOutput,
    GetRestApiInput,
    GetRestApiOutput,
    GetRestApisInput,
    GetRestApisOutput,
    GetSdkInput,
    GetSdkOutput,
    GetSdkTypeInput,
    GetSdkTypeOutput,
    GetSdkTypesInput,
    GetSdkTypesOutput,
    GetStageInput,
    GetStageOutput,
    GetStagesInput,
    GetStagesOutput,
    GetTagsInput,
    GetTagsOutput,
    GetUsageInput,
    GetUsageOutput,
    GetUsagePlanInput,
    GetUsagePlanKeyInput,
    GetUsagePlanKeyOutput,
    GetUsagePlanKeysInput,
    GetUsagePlanKeysOutput,
    GetUsagePlanOutput,
    GetUsagePlansInput,
    GetUsagePlansOutput,
    GetVpcLinkInput,
    GetVpcLinkOutput,
    GetVpcLinksInput,
    GetVpcLinksOutput,
    ImportApiKeysInput,
    ImportApiKeysOutput,
    ImportDocumentationPartsInput,
    ImportDocumentationPartsOutput,
    ImportRestApiInput,
    ImportRestApiOutput,
    PutGatewayResponseInput,
    PutGatewayResponseOutput,
    PutIntegrationInput,
    PutIntegrationOutput,
    PutIntegrationResponseInput,
    PutIntegrationResponseOutput,
    PutMethodInput,
    PutMethodOutput,
    PutMethodResponseInput,
    PutMethodResponseOutput,
    PutRestApiInput,
    PutRestApiOutput,
    RejectDomainNameAccessAssociationInput,
    RejectDomainNameAccessAssociationOutput,
    TagResourceInput,
    TagResourceOutput,
    TestInvokeAuthorizerInput,
    TestInvokeAuthorizerOutput,
    TestInvokeMethodInput,
    TestInvokeMethodOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateAccountInput,
    UpdateAccountOutput,
    UpdateApiKeyInput,
    UpdateApiKeyOutput,
    UpdateAuthorizerInput,
    UpdateAuthorizerOutput,
    UpdateBasePathMappingInput,
    UpdateBasePathMappingOutput,
    UpdateClientCertificateInput,
    UpdateClientCertificateOutput,
    UpdateDeploymentInput,
    UpdateDeploymentOutput,
    UpdateDocumentationPartInput,
    UpdateDocumentationPartOutput,
    UpdateDocumentationVersionInput,
    UpdateDocumentationVersionOutput,
    UpdateDomainNameInput,
    UpdateDomainNameOutput,
    UpdateGatewayResponseInput,
    UpdateGatewayResponseOutput,
    UpdateIntegrationInput,
    UpdateIntegrationOutput,
    UpdateIntegrationResponseInput,
    UpdateIntegrationResponseOutput,
    UpdateMethodInput,
    UpdateMethodOutput,
    UpdateMethodResponseInput,
    UpdateMethodResponseOutput,
    UpdateModelInput,
    UpdateModelOutput,
    UpdateRequestValidatorInput,
    UpdateRequestValidatorOutput,
    UpdateResourceInput,
    UpdateResourceOutput,
    UpdateRestApiInput,
    UpdateRestApiOutput,
    UpdateStageInput,
    UpdateStageOutput,
    UpdateUsageInput,
    UpdateUsageOutput,
    UpdateUsagePlanInput,
    UpdateUsagePlanOutput,
    UpdateVpcLinkInput,
    UpdateVpcLinkOutput,
)


_ServiceInterceptor = Union[
    Interceptor[CreateApiKeyInput, CreateApiKeyOutput, Any, Any],
    Interceptor[CreateAuthorizerInput, CreateAuthorizerOutput, Any, Any],
    Interceptor[CreateBasePathMappingInput, CreateBasePathMappingOutput, Any, Any],
    Interceptor[CreateDeploymentInput, CreateDeploymentOutput, Any, Any],
    Interceptor[CreateDocumentationPartInput, CreateDocumentationPartOutput, Any, Any],
    Interceptor[
        CreateDocumentationVersionInput, CreateDocumentationVersionOutput, Any, Any
    ],
    Interceptor[CreateDomainNameInput, CreateDomainNameOutput, Any, Any],
    Interceptor[
        CreateDomainNameAccessAssociationInput,
        CreateDomainNameAccessAssociationOutput,
        Any,
        Any,
    ],
    Interceptor[CreateModelInput, CreateModelOutput, Any, Any],
    Interceptor[CreateRequestValidatorInput, CreateRequestValidatorOutput, Any, Any],
    Interceptor[CreateResourceInput, CreateResourceOutput, Any, Any],
    Interceptor[CreateRestApiInput, CreateRestApiOutput, Any, Any],
    Interceptor[CreateStageInput, CreateStageOutput, Any, Any],
    Interceptor[CreateUsagePlanInput, CreateUsagePlanOutput, Any, Any],
    Interceptor[CreateUsagePlanKeyInput, CreateUsagePlanKeyOutput, Any, Any],
    Interceptor[CreateVpcLinkInput, CreateVpcLinkOutput, Any, Any],
    Interceptor[DeleteApiKeyInput, DeleteApiKeyOutput, Any, Any],
    Interceptor[DeleteAuthorizerInput, DeleteAuthorizerOutput, Any, Any],
    Interceptor[DeleteBasePathMappingInput, DeleteBasePathMappingOutput, Any, Any],
    Interceptor[DeleteClientCertificateInput, DeleteClientCertificateOutput, Any, Any],
    Interceptor[DeleteDeploymentInput, DeleteDeploymentOutput, Any, Any],
    Interceptor[DeleteDocumentationPartInput, DeleteDocumentationPartOutput, Any, Any],
    Interceptor[
        DeleteDocumentationVersionInput, DeleteDocumentationVersionOutput, Any, Any
    ],
    Interceptor[DeleteDomainNameInput, DeleteDomainNameOutput, Any, Any],
    Interceptor[
        DeleteDomainNameAccessAssociationInput,
        DeleteDomainNameAccessAssociationOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteGatewayResponseInput, DeleteGatewayResponseOutput, Any, Any],
    Interceptor[DeleteIntegrationInput, DeleteIntegrationOutput, Any, Any],
    Interceptor[
        DeleteIntegrationResponseInput, DeleteIntegrationResponseOutput, Any, Any
    ],
    Interceptor[DeleteMethodInput, DeleteMethodOutput, Any, Any],
    Interceptor[DeleteMethodResponseInput, DeleteMethodResponseOutput, Any, Any],
    Interceptor[DeleteModelInput, DeleteModelOutput, Any, Any],
    Interceptor[DeleteRequestValidatorInput, DeleteRequestValidatorOutput, Any, Any],
    Interceptor[DeleteResourceInput, DeleteResourceOutput, Any, Any],
    Interceptor[DeleteRestApiInput, DeleteRestApiOutput, Any, Any],
    Interceptor[DeleteStageInput, DeleteStageOutput, Any, Any],
    Interceptor[DeleteUsagePlanInput, DeleteUsagePlanOutput, Any, Any],
    Interceptor[DeleteUsagePlanKeyInput, DeleteUsagePlanKeyOutput, Any, Any],
    Interceptor[DeleteVpcLinkInput, DeleteVpcLinkOutput, Any, Any],
    Interceptor[
        FlushStageAuthorizersCacheInput, FlushStageAuthorizersCacheOutput, Any, Any
    ],
    Interceptor[FlushStageCacheInput, FlushStageCacheOutput, Any, Any],
    Interceptor[
        GenerateClientCertificateInput, GenerateClientCertificateOutput, Any, Any
    ],
    Interceptor[GetAccountInput, GetAccountOutput, Any, Any],
    Interceptor[GetApiKeyInput, GetApiKeyOutput, Any, Any],
    Interceptor[GetApiKeysInput, GetApiKeysOutput, Any, Any],
    Interceptor[GetAuthorizerInput, GetAuthorizerOutput, Any, Any],
    Interceptor[GetAuthorizersInput, GetAuthorizersOutput, Any, Any],
    Interceptor[GetBasePathMappingInput, GetBasePathMappingOutput, Any, Any],
    Interceptor[GetBasePathMappingsInput, GetBasePathMappingsOutput, Any, Any],
    Interceptor[GetClientCertificateInput, GetClientCertificateOutput, Any, Any],
    Interceptor[GetClientCertificatesInput, GetClientCertificatesOutput, Any, Any],
    Interceptor[GetDeploymentInput, GetDeploymentOutput, Any, Any],
    Interceptor[GetDeploymentsInput, GetDeploymentsOutput, Any, Any],
    Interceptor[GetDocumentationPartInput, GetDocumentationPartOutput, Any, Any],
    Interceptor[GetDocumentationPartsInput, GetDocumentationPartsOutput, Any, Any],
    Interceptor[GetDocumentationVersionInput, GetDocumentationVersionOutput, Any, Any],
    Interceptor[
        GetDocumentationVersionsInput, GetDocumentationVersionsOutput, Any, Any
    ],
    Interceptor[GetDomainNameInput, GetDomainNameOutput, Any, Any],
    Interceptor[
        GetDomainNameAccessAssociationsInput,
        GetDomainNameAccessAssociationsOutput,
        Any,
        Any,
    ],
    Interceptor[GetDomainNamesInput, GetDomainNamesOutput, Any, Any],
    Interceptor[GetExportInput, GetExportOutput, Any, Any],
    Interceptor[GetGatewayResponseInput, GetGatewayResponseOutput, Any, Any],
    Interceptor[GetGatewayResponsesInput, GetGatewayResponsesOutput, Any, Any],
    Interceptor[GetIntegrationInput, GetIntegrationOutput, Any, Any],
    Interceptor[GetIntegrationResponseInput, GetIntegrationResponseOutput, Any, Any],
    Interceptor[GetMethodInput, GetMethodOutput, Any, Any],
    Interceptor[GetMethodResponseInput, GetMethodResponseOutput, Any, Any],
    Interceptor[GetModelInput, GetModelOutput, Any, Any],
    Interceptor[GetModelsInput, GetModelsOutput, Any, Any],
    Interceptor[GetModelTemplateInput, GetModelTemplateOutput, Any, Any],
    Interceptor[GetRequestValidatorInput, GetRequestValidatorOutput, Any, Any],
    Interceptor[GetRequestValidatorsInput, GetRequestValidatorsOutput, Any, Any],
    Interceptor[GetResourceInput, GetResourceOutput, Any, Any],
    Interceptor[GetResourcesInput, GetResourcesOutput, Any, Any],
    Interceptor[GetRestApiInput, GetRestApiOutput, Any, Any],
    Interceptor[GetRestApisInput, GetRestApisOutput, Any, Any],
    Interceptor[GetSdkInput, GetSdkOutput, Any, Any],
    Interceptor[GetSdkTypeInput, GetSdkTypeOutput, Any, Any],
    Interceptor[GetSdkTypesInput, GetSdkTypesOutput, Any, Any],
    Interceptor[GetStageInput, GetStageOutput, Any, Any],
    Interceptor[GetStagesInput, GetStagesOutput, Any, Any],
    Interceptor[GetTagsInput, GetTagsOutput, Any, Any],
    Interceptor[GetUsageInput, GetUsageOutput, Any, Any],
    Interceptor[GetUsagePlanInput, GetUsagePlanOutput, Any, Any],
    Interceptor[GetUsagePlanKeyInput, GetUsagePlanKeyOutput, Any, Any],
    Interceptor[GetUsagePlanKeysInput, GetUsagePlanKeysOutput, Any, Any],
    Interceptor[GetUsagePlansInput, GetUsagePlansOutput, Any, Any],
    Interceptor[GetVpcLinkInput, GetVpcLinkOutput, Any, Any],
    Interceptor[GetVpcLinksInput, GetVpcLinksOutput, Any, Any],
    Interceptor[ImportApiKeysInput, ImportApiKeysOutput, Any, Any],
    Interceptor[
        ImportDocumentationPartsInput, ImportDocumentationPartsOutput, Any, Any
    ],
    Interceptor[ImportRestApiInput, ImportRestApiOutput, Any, Any],
    Interceptor[PutGatewayResponseInput, PutGatewayResponseOutput, Any, Any],
    Interceptor[PutIntegrationInput, PutIntegrationOutput, Any, Any],
    Interceptor[PutIntegrationResponseInput, PutIntegrationResponseOutput, Any, Any],
    Interceptor[PutMethodInput, PutMethodOutput, Any, Any],
    Interceptor[PutMethodResponseInput, PutMethodResponseOutput, Any, Any],
    Interceptor[PutRestApiInput, PutRestApiOutput, Any, Any],
    Interceptor[
        RejectDomainNameAccessAssociationInput,
        RejectDomainNameAccessAssociationOutput,
        Any,
        Any,
    ],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[TestInvokeAuthorizerInput, TestInvokeAuthorizerOutput, Any, Any],
    Interceptor[TestInvokeMethodInput, TestInvokeMethodOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[UpdateAccountInput, UpdateAccountOutput, Any, Any],
    Interceptor[UpdateApiKeyInput, UpdateApiKeyOutput, Any, Any],
    Interceptor[UpdateAuthorizerInput, UpdateAuthorizerOutput, Any, Any],
    Interceptor[UpdateBasePathMappingInput, UpdateBasePathMappingOutput, Any, Any],
    Interceptor[UpdateClientCertificateInput, UpdateClientCertificateOutput, Any, Any],
    Interceptor[UpdateDeploymentInput, UpdateDeploymentOutput, Any, Any],
    Interceptor[UpdateDocumentationPartInput, UpdateDocumentationPartOutput, Any, Any],
    Interceptor[
        UpdateDocumentationVersionInput, UpdateDocumentationVersionOutput, Any, Any
    ],
    Interceptor[UpdateDomainNameInput, UpdateDomainNameOutput, Any, Any],
    Interceptor[UpdateGatewayResponseInput, UpdateGatewayResponseOutput, Any, Any],
    Interceptor[UpdateIntegrationInput, UpdateIntegrationOutput, Any, Any],
    Interceptor[
        UpdateIntegrationResponseInput, UpdateIntegrationResponseOutput, Any, Any
    ],
    Interceptor[UpdateMethodInput, UpdateMethodOutput, Any, Any],
    Interceptor[UpdateMethodResponseInput, UpdateMethodResponseOutput, Any, Any],
    Interceptor[UpdateModelInput, UpdateModelOutput, Any, Any],
    Interceptor[UpdateRequestValidatorInput, UpdateRequestValidatorOutput, Any, Any],
    Interceptor[UpdateResourceInput, UpdateResourceOutput, Any, Any],
    Interceptor[UpdateRestApiInput, UpdateRestApiOutput, Any, Any],
    Interceptor[UpdateStageInput, UpdateStageOutput, Any, Any],
    Interceptor[UpdateUsageInput, UpdateUsageOutput, Any, Any],
    Interceptor[UpdateUsagePlanInput, UpdateUsagePlanOutput, Any, Any],
    Interceptor[UpdateVpcLinkInput, UpdateVpcLinkOutput, Any, Any],
]


@dataclass(init=False)
class Config:
    """Configuration for API Gateway."""

    auth_scheme_resolver: HTTPAuthSchemeResolver
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]]
    """A map of auth scheme ids to auth schemes."""

    aws_access_key_id: str | None
    """The identifier for a secret access key."""

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    )
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    aws_secret_access_key: str | None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None
    """An access key ID that identifies temporary security credentials."""

    endpoint_resolver: EndpointResolver
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    endpoint_uri: str | URI | None
    """A static URI to route requests to."""

    http_request_config: HTTPRequestConfiguration | None
    """Configuration for individual HTTP requests."""

    interceptors: list[_ServiceInterceptor]
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    protocol: ClientProtocol[Any, Any] | None
    """The protocol to serialize and deserialize requests with."""

    region: str | None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    retry_strategy: RetryStrategy | RetryStrategyOptions | None
    """
    The retry strategy or options for configuring retry behavior. Can be
    either a configured RetryStrategy or RetryStrategyOptions to create one.
    """

    sdk_ua_app_id: str | None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    transport: ClientTransport[Any, Any] | None
    """
    The transport to use to send requests (e.g. an HTTP client). Operations
    with bidirectional event streams require a DuplexClientTransport, such
    as AWSCRTHTTPClient. Transports are assumed not to support duplex
    streaming unless they explicitly set SUPPORTS_DUPLEX_STREAMING to True.
    """

    user_agent_extra: str | None
    """Additional suffix to be added to the User-Agent header."""

    def __init__(
        self,
        *,
        auth_scheme_resolver: HTTPAuthSchemeResolver | None = None,
        auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None,
        aws_access_key_id: str | None = None,
        aws_credentials_identity_resolver: IdentityResolver[
            AWSCredentialsIdentity, AWSIdentityProperties
        ]
        | None = None,
        aws_secret_access_key: str | None = None,
        aws_session_token: str | None = None,
        endpoint_resolver: EndpointResolver | None = None,
        endpoint_uri: str | URI | None = None,
        http_request_config: HTTPRequestConfiguration | None = None,
        interceptors: list[_ServiceInterceptor] | None = None,
        protocol: ClientProtocol[Any, Any] | None = None,
        region: str | None = None,
        retry_strategy: RetryStrategy | RetryStrategyOptions | None = None,
        sdk_ua_app_id: str | None = None,
        transport: ClientTransport[Any, Any] | None = None,
        user_agent_extra: str | None = None,
    ):
        self.auth_scheme_resolver = auth_scheme_resolver or HTTPAuthSchemeResolver()
        self.auth_schemes = auth_schemes or {
            ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="apigateway")
        }
        self.aws_access_key_id = aws_access_key_id
        self.aws_credentials_identity_resolver = aws_credentials_identity_resolver
        self.aws_secret_access_key = aws_secret_access_key
        self.aws_session_token = aws_session_token
        self.endpoint_resolver = endpoint_resolver or StandardRegionalEndpointsResolver(
            endpoint_prefix="apigateway"
        )
        self.endpoint_uri = endpoint_uri
        self.http_request_config = http_request_config
        self.interceptors = interceptors or []
        self.protocol = protocol or RestJsonClientProtocol(
            _SCHEMA_BACKPLANE_CONTROL_SERVICE
        )
        self.region = region
        self.retry_strategy = retry_strategy
        self.sdk_ua_app_id = sdk_ua_app_id
        self.transport = transport or AIOHTTPClient()
        self.user_agent_extra = user_agent_extra

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Sets the implementation of an auth scheme.

        Using this method ensures the correct key is used.

        Args:
            scheme:
                The auth scheme to add.
        """
        self.auth_schemes[scheme.scheme_id] = scheme


Plugin: TypeAlias = Callable[[Config], None]
"""A callable that allows customizing the config object on each request."""
