# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
from typing import Any, Callable, TypeAlias, Union

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, ClientTransport, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.aio.interfaces.retries import RetryStrategy
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces import URI
from smithy_core.retries import RetryStrategyOptions
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient
from smithy_http.interfaces import HTTPRequestConfiguration

from ._private.schemas import (
    AMAZON_BEDROCK_CONTROL_PLANE_SERVICE as _SCHEMA_AMAZON_BEDROCK_CONTROL_PLANE_SERVICE,
)
from .auth import HTTPAuthSchemeResolver
from .models import (
    BatchDeleteAdvancedPromptOptimizationJobInput,
    BatchDeleteAdvancedPromptOptimizationJobOutput,
    BatchDeleteEvaluationJobInput,
    BatchDeleteEvaluationJobOutput,
    CancelAutomatedReasoningPolicyBuildWorkflowInput,
    CancelAutomatedReasoningPolicyBuildWorkflowOutput,
    CreateAdvancedPromptOptimizationJobInput,
    CreateAdvancedPromptOptimizationJobOutput,
    CreateAutomatedReasoningPolicyInput,
    CreateAutomatedReasoningPolicyOutput,
    CreateAutomatedReasoningPolicyTestCaseInput,
    CreateAutomatedReasoningPolicyTestCaseOutput,
    CreateAutomatedReasoningPolicyVersionInput,
    CreateAutomatedReasoningPolicyVersionOutput,
    CreateCustomModelDeploymentInput,
    CreateCustomModelDeploymentOutput,
    CreateCustomModelInput,
    CreateCustomModelOutput,
    CreateEvaluationJobInput,
    CreateEvaluationJobOutput,
    CreateFoundationModelAgreementInput,
    CreateFoundationModelAgreementOutput,
    CreateGuardrailInput,
    CreateGuardrailOutput,
    CreateGuardrailVersionInput,
    CreateGuardrailVersionOutput,
    CreateInferenceProfileInput,
    CreateInferenceProfileOutput,
    CreateMarketplaceModelEndpointInput,
    CreateMarketplaceModelEndpointOutput,
    CreateModelCopyJobInput,
    CreateModelCopyJobOutput,
    CreateModelCustomizationJobInput,
    CreateModelCustomizationJobOutput,
    CreateModelImportJobInput,
    CreateModelImportJobOutput,
    CreateModelInvocationJobInput,
    CreateModelInvocationJobOutput,
    CreatePromptRouterInput,
    CreatePromptRouterOutput,
    CreateProvisionedModelThroughputInput,
    CreateProvisionedModelThroughputOutput,
    DeleteAutomatedReasoningPolicyBuildWorkflowInput,
    DeleteAutomatedReasoningPolicyBuildWorkflowOutput,
    DeleteAutomatedReasoningPolicyInput,
    DeleteAutomatedReasoningPolicyOutput,
    DeleteAutomatedReasoningPolicyTestCaseInput,
    DeleteAutomatedReasoningPolicyTestCaseOutput,
    DeleteCustomModelDeploymentInput,
    DeleteCustomModelDeploymentOutput,
    DeleteCustomModelInput,
    DeleteCustomModelOutput,
    DeleteEnforcedGuardrailConfigurationInput,
    DeleteEnforcedGuardrailConfigurationOutput,
    DeleteFoundationModelAgreementInput,
    DeleteFoundationModelAgreementOutput,
    DeleteGuardrailInput,
    DeleteGuardrailOutput,
    DeleteImportedModelInput,
    DeleteImportedModelOutput,
    DeleteInferenceProfileInput,
    DeleteInferenceProfileOutput,
    DeleteMarketplaceModelEndpointInput,
    DeleteMarketplaceModelEndpointOutput,
    DeleteModelInvocationLoggingConfigurationInput,
    DeleteModelInvocationLoggingConfigurationOutput,
    DeletePromptRouterInput,
    DeletePromptRouterOutput,
    DeleteProvisionedModelThroughputInput,
    DeleteProvisionedModelThroughputOutput,
    DeleteResourcePolicyInput,
    DeleteResourcePolicyOutput,
    DeregisterMarketplaceModelEndpointInput,
    DeregisterMarketplaceModelEndpointOutput,
    ExportAutomatedReasoningPolicyVersionInput,
    ExportAutomatedReasoningPolicyVersionOutput,
    GetAccountDataRetentionInput,
    GetAccountDataRetentionOutput,
    GetAdvancedPromptOptimizationJobInput,
    GetAdvancedPromptOptimizationJobOutput,
    GetAutomatedReasoningPolicyAnnotationsInput,
    GetAutomatedReasoningPolicyAnnotationsOutput,
    GetAutomatedReasoningPolicyBuildWorkflowInput,
    GetAutomatedReasoningPolicyBuildWorkflowOutput,
    GetAutomatedReasoningPolicyBuildWorkflowResultAssetsInput,
    GetAutomatedReasoningPolicyBuildWorkflowResultAssetsOutput,
    GetAutomatedReasoningPolicyInput,
    GetAutomatedReasoningPolicyNextScenarioInput,
    GetAutomatedReasoningPolicyNextScenarioOutput,
    GetAutomatedReasoningPolicyOutput,
    GetAutomatedReasoningPolicyTestCaseInput,
    GetAutomatedReasoningPolicyTestCaseOutput,
    GetAutomatedReasoningPolicyTestResultInput,
    GetAutomatedReasoningPolicyTestResultOutput,
    GetCustomModelDeploymentInput,
    GetCustomModelDeploymentOutput,
    GetCustomModelInput,
    GetCustomModelOutput,
    GetEvaluationJobInput,
    GetEvaluationJobOutput,
    GetFoundationModelAvailabilityInput,
    GetFoundationModelAvailabilityOutput,
    GetFoundationModelInput,
    GetFoundationModelOutput,
    GetGuardrailInput,
    GetGuardrailOutput,
    GetImportedModelInput,
    GetImportedModelOutput,
    GetInferenceProfileInput,
    GetInferenceProfileOutput,
    GetMarketplaceModelEndpointInput,
    GetMarketplaceModelEndpointOutput,
    GetModelCopyJobInput,
    GetModelCopyJobOutput,
    GetModelCustomizationJobInput,
    GetModelCustomizationJobOutput,
    GetModelImportJobInput,
    GetModelImportJobOutput,
    GetModelInvocationJobInput,
    GetModelInvocationJobOutput,
    GetModelInvocationLoggingConfigurationInput,
    GetModelInvocationLoggingConfigurationOutput,
    GetPromptRouterInput,
    GetPromptRouterOutput,
    GetProvisionedModelThroughputInput,
    GetProvisionedModelThroughputOutput,
    GetResourcePolicyInput,
    GetResourcePolicyOutput,
    GetUseCaseForModelAccessInput,
    GetUseCaseForModelAccessOutput,
    ListAdvancedPromptOptimizationJobsInput,
    ListAdvancedPromptOptimizationJobsOutput,
    ListAutomatedReasoningPoliciesInput,
    ListAutomatedReasoningPoliciesOutput,
    ListAutomatedReasoningPolicyBuildWorkflowsInput,
    ListAutomatedReasoningPolicyBuildWorkflowsOutput,
    ListAutomatedReasoningPolicyTestCasesInput,
    ListAutomatedReasoningPolicyTestCasesOutput,
    ListAutomatedReasoningPolicyTestResultsInput,
    ListAutomatedReasoningPolicyTestResultsOutput,
    ListCustomModelDeploymentsInput,
    ListCustomModelDeploymentsOutput,
    ListCustomModelsInput,
    ListCustomModelsOutput,
    ListEnforcedGuardrailsConfigurationInput,
    ListEnforcedGuardrailsConfigurationOutput,
    ListEvaluationJobsInput,
    ListEvaluationJobsOutput,
    ListFoundationModelAgreementOffersInput,
    ListFoundationModelAgreementOffersOutput,
    ListFoundationModelsInput,
    ListFoundationModelsOutput,
    ListGuardrailsInput,
    ListGuardrailsOutput,
    ListImportedModelsInput,
    ListImportedModelsOutput,
    ListInferenceProfilesInput,
    ListInferenceProfilesOutput,
    ListMarketplaceModelEndpointsInput,
    ListMarketplaceModelEndpointsOutput,
    ListModelCopyJobsInput,
    ListModelCopyJobsOutput,
    ListModelCustomizationJobsInput,
    ListModelCustomizationJobsOutput,
    ListModelImportJobsInput,
    ListModelImportJobsOutput,
    ListModelInvocationJobsInput,
    ListModelInvocationJobsOutput,
    ListPromptRoutersInput,
    ListPromptRoutersOutput,
    ListProvisionedModelThroughputsInput,
    ListProvisionedModelThroughputsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    PutAccountDataRetentionInput,
    PutAccountDataRetentionOutput,
    PutEnforcedGuardrailConfigurationInput,
    PutEnforcedGuardrailConfigurationOutput,
    PutModelInvocationLoggingConfigurationInput,
    PutModelInvocationLoggingConfigurationOutput,
    PutResourcePolicyInput,
    PutResourcePolicyOutput,
    PutUseCaseForModelAccessInput,
    PutUseCaseForModelAccessOutput,
    RegisterMarketplaceModelEndpointInput,
    RegisterMarketplaceModelEndpointOutput,
    StartAutomatedReasoningPolicyBuildWorkflowInput,
    StartAutomatedReasoningPolicyBuildWorkflowOutput,
    StartAutomatedReasoningPolicyTestWorkflowInput,
    StartAutomatedReasoningPolicyTestWorkflowOutput,
    StopAdvancedPromptOptimizationJobInput,
    StopAdvancedPromptOptimizationJobOutput,
    StopEvaluationJobInput,
    StopEvaluationJobOutput,
    StopModelCustomizationJobInput,
    StopModelCustomizationJobOutput,
    StopModelInvocationJobInput,
    StopModelInvocationJobOutput,
    TagResourceInput,
    TagResourceOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateAutomatedReasoningPolicyAnnotationsInput,
    UpdateAutomatedReasoningPolicyAnnotationsOutput,
    UpdateAutomatedReasoningPolicyInput,
    UpdateAutomatedReasoningPolicyOutput,
    UpdateAutomatedReasoningPolicyTestCaseInput,
    UpdateAutomatedReasoningPolicyTestCaseOutput,
    UpdateCustomModelDeploymentInput,
    UpdateCustomModelDeploymentOutput,
    UpdateGuardrailInput,
    UpdateGuardrailOutput,
    UpdateMarketplaceModelEndpointInput,
    UpdateMarketplaceModelEndpointOutput,
    UpdateProvisionedModelThroughputInput,
    UpdateProvisionedModelThroughputOutput,
)


_ServiceInterceptor = Union[
    Interceptor[
        BatchDeleteAdvancedPromptOptimizationJobInput,
        BatchDeleteAdvancedPromptOptimizationJobOutput,
        Any,
        Any,
    ],
    Interceptor[
        BatchDeleteEvaluationJobInput, BatchDeleteEvaluationJobOutput, Any, Any
    ],
    Interceptor[
        CancelAutomatedReasoningPolicyBuildWorkflowInput,
        CancelAutomatedReasoningPolicyBuildWorkflowOutput,
        Any,
        Any,
    ],
    Interceptor[
        CreateAdvancedPromptOptimizationJobInput,
        CreateAdvancedPromptOptimizationJobOutput,
        Any,
        Any,
    ],
    Interceptor[
        CreateAutomatedReasoningPolicyInput,
        CreateAutomatedReasoningPolicyOutput,
        Any,
        Any,
    ],
    Interceptor[
        CreateAutomatedReasoningPolicyTestCaseInput,
        CreateAutomatedReasoningPolicyTestCaseOutput,
        Any,
        Any,
    ],
    Interceptor[
        CreateAutomatedReasoningPolicyVersionInput,
        CreateAutomatedReasoningPolicyVersionOutput,
        Any,
        Any,
    ],
    Interceptor[CreateCustomModelInput, CreateCustomModelOutput, Any, Any],
    Interceptor[
        CreateCustomModelDeploymentInput, CreateCustomModelDeploymentOutput, Any, Any
    ],
    Interceptor[CreateEvaluationJobInput, CreateEvaluationJobOutput, Any, Any],
    Interceptor[
        CreateFoundationModelAgreementInput,
        CreateFoundationModelAgreementOutput,
        Any,
        Any,
    ],
    Interceptor[CreateGuardrailInput, CreateGuardrailOutput, Any, Any],
    Interceptor[CreateGuardrailVersionInput, CreateGuardrailVersionOutput, Any, Any],
    Interceptor[CreateInferenceProfileInput, CreateInferenceProfileOutput, Any, Any],
    Interceptor[
        CreateMarketplaceModelEndpointInput,
        CreateMarketplaceModelEndpointOutput,
        Any,
        Any,
    ],
    Interceptor[CreateModelCopyJobInput, CreateModelCopyJobOutput, Any, Any],
    Interceptor[
        CreateModelCustomizationJobInput, CreateModelCustomizationJobOutput, Any, Any
    ],
    Interceptor[CreateModelImportJobInput, CreateModelImportJobOutput, Any, Any],
    Interceptor[
        CreateModelInvocationJobInput, CreateModelInvocationJobOutput, Any, Any
    ],
    Interceptor[CreatePromptRouterInput, CreatePromptRouterOutput, Any, Any],
    Interceptor[
        CreateProvisionedModelThroughputInput,
        CreateProvisionedModelThroughputOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteAutomatedReasoningPolicyInput,
        DeleteAutomatedReasoningPolicyOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteAutomatedReasoningPolicyBuildWorkflowInput,
        DeleteAutomatedReasoningPolicyBuildWorkflowOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteAutomatedReasoningPolicyTestCaseInput,
        DeleteAutomatedReasoningPolicyTestCaseOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteCustomModelInput, DeleteCustomModelOutput, Any, Any],
    Interceptor[
        DeleteCustomModelDeploymentInput, DeleteCustomModelDeploymentOutput, Any, Any
    ],
    Interceptor[
        DeleteEnforcedGuardrailConfigurationInput,
        DeleteEnforcedGuardrailConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteFoundationModelAgreementInput,
        DeleteFoundationModelAgreementOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteGuardrailInput, DeleteGuardrailOutput, Any, Any],
    Interceptor[DeleteImportedModelInput, DeleteImportedModelOutput, Any, Any],
    Interceptor[DeleteInferenceProfileInput, DeleteInferenceProfileOutput, Any, Any],
    Interceptor[
        DeleteMarketplaceModelEndpointInput,
        DeleteMarketplaceModelEndpointOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteModelInvocationLoggingConfigurationInput,
        DeleteModelInvocationLoggingConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[DeletePromptRouterInput, DeletePromptRouterOutput, Any, Any],
    Interceptor[
        DeleteProvisionedModelThroughputInput,
        DeleteProvisionedModelThroughputOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteResourcePolicyInput, DeleteResourcePolicyOutput, Any, Any],
    Interceptor[
        DeregisterMarketplaceModelEndpointInput,
        DeregisterMarketplaceModelEndpointOutput,
        Any,
        Any,
    ],
    Interceptor[
        ExportAutomatedReasoningPolicyVersionInput,
        ExportAutomatedReasoningPolicyVersionOutput,
        Any,
        Any,
    ],
    Interceptor[GetAccountDataRetentionInput, GetAccountDataRetentionOutput, Any, Any],
    Interceptor[
        GetAdvancedPromptOptimizationJobInput,
        GetAdvancedPromptOptimizationJobOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyInput, GetAutomatedReasoningPolicyOutput, Any, Any
    ],
    Interceptor[
        GetAutomatedReasoningPolicyAnnotationsInput,
        GetAutomatedReasoningPolicyAnnotationsOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyBuildWorkflowInput,
        GetAutomatedReasoningPolicyBuildWorkflowOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyBuildWorkflowResultAssetsInput,
        GetAutomatedReasoningPolicyBuildWorkflowResultAssetsOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyNextScenarioInput,
        GetAutomatedReasoningPolicyNextScenarioOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyTestCaseInput,
        GetAutomatedReasoningPolicyTestCaseOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetAutomatedReasoningPolicyTestResultInput,
        GetAutomatedReasoningPolicyTestResultOutput,
        Any,
        Any,
    ],
    Interceptor[GetCustomModelInput, GetCustomModelOutput, Any, Any],
    Interceptor[
        GetCustomModelDeploymentInput, GetCustomModelDeploymentOutput, Any, Any
    ],
    Interceptor[GetEvaluationJobInput, GetEvaluationJobOutput, Any, Any],
    Interceptor[GetFoundationModelInput, GetFoundationModelOutput, Any, Any],
    Interceptor[
        GetFoundationModelAvailabilityInput,
        GetFoundationModelAvailabilityOutput,
        Any,
        Any,
    ],
    Interceptor[GetGuardrailInput, GetGuardrailOutput, Any, Any],
    Interceptor[GetImportedModelInput, GetImportedModelOutput, Any, Any],
    Interceptor[GetInferenceProfileInput, GetInferenceProfileOutput, Any, Any],
    Interceptor[
        GetMarketplaceModelEndpointInput, GetMarketplaceModelEndpointOutput, Any, Any
    ],
    Interceptor[GetModelCopyJobInput, GetModelCopyJobOutput, Any, Any],
    Interceptor[
        GetModelCustomizationJobInput, GetModelCustomizationJobOutput, Any, Any
    ],
    Interceptor[GetModelImportJobInput, GetModelImportJobOutput, Any, Any],
    Interceptor[GetModelInvocationJobInput, GetModelInvocationJobOutput, Any, Any],
    Interceptor[
        GetModelInvocationLoggingConfigurationInput,
        GetModelInvocationLoggingConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[GetPromptRouterInput, GetPromptRouterOutput, Any, Any],
    Interceptor[
        GetProvisionedModelThroughputInput,
        GetProvisionedModelThroughputOutput,
        Any,
        Any,
    ],
    Interceptor[GetResourcePolicyInput, GetResourcePolicyOutput, Any, Any],
    Interceptor[
        GetUseCaseForModelAccessInput, GetUseCaseForModelAccessOutput, Any, Any
    ],
    Interceptor[
        ListAdvancedPromptOptimizationJobsInput,
        ListAdvancedPromptOptimizationJobsOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListAutomatedReasoningPoliciesInput,
        ListAutomatedReasoningPoliciesOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListAutomatedReasoningPolicyBuildWorkflowsInput,
        ListAutomatedReasoningPolicyBuildWorkflowsOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListAutomatedReasoningPolicyTestCasesInput,
        ListAutomatedReasoningPolicyTestCasesOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListAutomatedReasoningPolicyTestResultsInput,
        ListAutomatedReasoningPolicyTestResultsOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListCustomModelDeploymentsInput, ListCustomModelDeploymentsOutput, Any, Any
    ],
    Interceptor[ListCustomModelsInput, ListCustomModelsOutput, Any, Any],
    Interceptor[
        ListEnforcedGuardrailsConfigurationInput,
        ListEnforcedGuardrailsConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[ListEvaluationJobsInput, ListEvaluationJobsOutput, Any, Any],
    Interceptor[
        ListFoundationModelAgreementOffersInput,
        ListFoundationModelAgreementOffersOutput,
        Any,
        Any,
    ],
    Interceptor[ListFoundationModelsInput, ListFoundationModelsOutput, Any, Any],
    Interceptor[ListGuardrailsInput, ListGuardrailsOutput, Any, Any],
    Interceptor[ListImportedModelsInput, ListImportedModelsOutput, Any, Any],
    Interceptor[ListInferenceProfilesInput, ListInferenceProfilesOutput, Any, Any],
    Interceptor[
        ListMarketplaceModelEndpointsInput,
        ListMarketplaceModelEndpointsOutput,
        Any,
        Any,
    ],
    Interceptor[ListModelCopyJobsInput, ListModelCopyJobsOutput, Any, Any],
    Interceptor[
        ListModelCustomizationJobsInput, ListModelCustomizationJobsOutput, Any, Any
    ],
    Interceptor[ListModelImportJobsInput, ListModelImportJobsOutput, Any, Any],
    Interceptor[ListModelInvocationJobsInput, ListModelInvocationJobsOutput, Any, Any],
    Interceptor[ListPromptRoutersInput, ListPromptRoutersOutput, Any, Any],
    Interceptor[
        ListProvisionedModelThroughputsInput,
        ListProvisionedModelThroughputsOutput,
        Any,
        Any,
    ],
    Interceptor[ListTagsForResourceInput, ListTagsForResourceOutput, Any, Any],
    Interceptor[PutAccountDataRetentionInput, PutAccountDataRetentionOutput, Any, Any],
    Interceptor[
        PutEnforcedGuardrailConfigurationInput,
        PutEnforcedGuardrailConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        PutModelInvocationLoggingConfigurationInput,
        PutModelInvocationLoggingConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[PutResourcePolicyInput, PutResourcePolicyOutput, Any, Any],
    Interceptor[
        PutUseCaseForModelAccessInput, PutUseCaseForModelAccessOutput, Any, Any
    ],
    Interceptor[
        RegisterMarketplaceModelEndpointInput,
        RegisterMarketplaceModelEndpointOutput,
        Any,
        Any,
    ],
    Interceptor[
        StartAutomatedReasoningPolicyBuildWorkflowInput,
        StartAutomatedReasoningPolicyBuildWorkflowOutput,
        Any,
        Any,
    ],
    Interceptor[
        StartAutomatedReasoningPolicyTestWorkflowInput,
        StartAutomatedReasoningPolicyTestWorkflowOutput,
        Any,
        Any,
    ],
    Interceptor[
        StopAdvancedPromptOptimizationJobInput,
        StopAdvancedPromptOptimizationJobOutput,
        Any,
        Any,
    ],
    Interceptor[StopEvaluationJobInput, StopEvaluationJobOutput, Any, Any],
    Interceptor[
        StopModelCustomizationJobInput, StopModelCustomizationJobOutput, Any, Any
    ],
    Interceptor[StopModelInvocationJobInput, StopModelInvocationJobOutput, Any, Any],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[
        UpdateAutomatedReasoningPolicyInput,
        UpdateAutomatedReasoningPolicyOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateAutomatedReasoningPolicyAnnotationsInput,
        UpdateAutomatedReasoningPolicyAnnotationsOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateAutomatedReasoningPolicyTestCaseInput,
        UpdateAutomatedReasoningPolicyTestCaseOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateCustomModelDeploymentInput, UpdateCustomModelDeploymentOutput, Any, Any
    ],
    Interceptor[UpdateGuardrailInput, UpdateGuardrailOutput, Any, Any],
    Interceptor[
        UpdateMarketplaceModelEndpointInput,
        UpdateMarketplaceModelEndpointOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateProvisionedModelThroughputInput,
        UpdateProvisionedModelThroughputOutput,
        Any,
        Any,
    ],
]


@dataclass(init=False)
class Config:
    """Configuration for Bedrock."""

    auth_scheme_resolver: HTTPAuthSchemeResolver
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]]
    """A map of auth scheme ids to auth schemes."""

    aws_access_key_id: str | None
    """The identifier for a secret access key."""

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    )
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    aws_secret_access_key: str | None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None
    """An access key ID that identifies temporary security credentials."""

    endpoint_resolver: EndpointResolver
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    endpoint_uri: str | URI | None
    """A static URI to route requests to."""

    http_request_config: HTTPRequestConfiguration | None
    """Configuration for individual HTTP requests."""

    interceptors: list[_ServiceInterceptor]
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    protocol: ClientProtocol[Any, Any] | None
    """The protocol to serialize and deserialize requests with."""

    region: str | None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    retry_strategy: RetryStrategy | RetryStrategyOptions | None
    """
    The retry strategy or options for configuring retry behavior. Can be
    either a configured RetryStrategy or RetryStrategyOptions to create one.
    """

    sdk_ua_app_id: str | None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    transport: ClientTransport[Any, Any] | None
    """The transport to use to send requests (e.g. an HTTP client)."""

    user_agent_extra: str | None
    """Additional suffix to be added to the User-Agent header."""

    def __init__(
        self,
        *,
        auth_scheme_resolver: HTTPAuthSchemeResolver | None = None,
        auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None,
        aws_access_key_id: str | None = None,
        aws_credentials_identity_resolver: IdentityResolver[
            AWSCredentialsIdentity, AWSIdentityProperties
        ]
        | None = None,
        aws_secret_access_key: str | None = None,
        aws_session_token: str | None = None,
        endpoint_resolver: EndpointResolver | None = None,
        endpoint_uri: str | URI | None = None,
        http_request_config: HTTPRequestConfiguration | None = None,
        interceptors: list[_ServiceInterceptor] | None = None,
        protocol: ClientProtocol[Any, Any] | None = None,
        region: str | None = None,
        retry_strategy: RetryStrategy | RetryStrategyOptions | None = None,
        sdk_ua_app_id: str | None = None,
        transport: ClientTransport[Any, Any] | None = None,
        user_agent_extra: str | None = None,
    ):
        self.auth_scheme_resolver = auth_scheme_resolver or HTTPAuthSchemeResolver()
        self.auth_schemes = auth_schemes or {
            ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="bedrock")
        }
        self.aws_access_key_id = aws_access_key_id
        self.aws_credentials_identity_resolver = aws_credentials_identity_resolver
        self.aws_secret_access_key = aws_secret_access_key
        self.aws_session_token = aws_session_token
        self.endpoint_resolver = endpoint_resolver or StandardRegionalEndpointsResolver(
            endpoint_prefix="bedrock"
        )
        self.endpoint_uri = endpoint_uri
        self.http_request_config = http_request_config
        self.interceptors = interceptors or []
        self.protocol = protocol or RestJsonClientProtocol(
            _SCHEMA_AMAZON_BEDROCK_CONTROL_PLANE_SERVICE
        )
        self.region = region
        self.retry_strategy = retry_strategy
        self.sdk_ua_app_id = sdk_ua_app_id
        self.transport = transport or AIOHTTPClient()
        self.user_agent_extra = user_agent_extra

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Sets the implementation of an auth scheme.

        Using this method ensures the correct key is used.

        Args:
            scheme:
                The auth scheme to add.
        """
        self.auth_schemes[scheme.scheme_id] = scheme


Plugin: TypeAlias = Callable[[Config], None]
"""A callable that allows customizing the config object on each request."""
