# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
from typing import Any, Callable, TypeAlias, Union

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, ClientTransport, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.aio.interfaces.retries import RetryStrategy
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces import URI
from smithy_core.retries import RetryStrategyOptions
from smithy_core.shapes import ShapeID
from smithy_http.aio.crt import AWSCRTHTTPClient
from smithy_http.interfaces import HTTPRequestConfiguration

from ._private.schemas import EXPERT_Q as _SCHEMA_EXPERT_Q
from .auth import HTTPAuthSchemeResolver
from .models import (
    AssociatePermissionInput,
    AssociatePermissionOutput,
    BatchDeleteDocumentInput,
    BatchDeleteDocumentOutput,
    BatchPutDocumentInput,
    BatchPutDocumentOutput,
    CancelSubscriptionInput,
    CancelSubscriptionOutput,
    ChatInput,
    ChatOutput,
    ChatSyncInput,
    ChatSyncOutput,
    CheckDocumentAccessInput,
    CheckDocumentAccessOutput,
    CreateAnonymousWebExperienceUrlInput,
    CreateAnonymousWebExperienceUrlOutput,
    CreateApplicationInput,
    CreateApplicationOutput,
    CreateChatResponseConfigurationInput,
    CreateChatResponseConfigurationOutput,
    CreateDataAccessorInput,
    CreateDataAccessorOutput,
    CreateDataSourceInput,
    CreateDataSourceOutput,
    CreateIndexInput,
    CreateIndexOutput,
    CreatePluginInput,
    CreatePluginOutput,
    CreateRetrieverInput,
    CreateRetrieverOutput,
    CreateSubscriptionInput,
    CreateSubscriptionOutput,
    CreateUserInput,
    CreateUserOutput,
    CreateWebExperienceInput,
    CreateWebExperienceOutput,
    DeleteApplicationInput,
    DeleteApplicationOutput,
    DeleteAttachmentInput,
    DeleteAttachmentOutput,
    DeleteChatControlsConfigurationInput,
    DeleteChatControlsConfigurationOutput,
    DeleteChatResponseConfigurationInput,
    DeleteChatResponseConfigurationOutput,
    DeleteConversationInput,
    DeleteConversationOutput,
    DeleteDataAccessorInput,
    DeleteDataAccessorOutput,
    DeleteDataSourceInput,
    DeleteDataSourceOutput,
    DeleteGroupInput,
    DeleteGroupOutput,
    DeleteIndexInput,
    DeleteIndexOutput,
    DeletePluginInput,
    DeletePluginOutput,
    DeleteRetrieverInput,
    DeleteRetrieverOutput,
    DeleteUserInput,
    DeleteUserOutput,
    DeleteWebExperienceInput,
    DeleteWebExperienceOutput,
    DisassociatePermissionInput,
    DisassociatePermissionOutput,
    GetApplicationInput,
    GetApplicationOutput,
    GetChatControlsConfigurationInput,
    GetChatControlsConfigurationOutput,
    GetChatResponseConfigurationInput,
    GetChatResponseConfigurationOutput,
    GetDataAccessorInput,
    GetDataAccessorOutput,
    GetDataSourceInput,
    GetDataSourceOutput,
    GetDocumentContentInput,
    GetDocumentContentOutput,
    GetGroupInput,
    GetGroupOutput,
    GetIndexInput,
    GetIndexOutput,
    GetMediaInput,
    GetMediaOutput,
    GetPluginInput,
    GetPluginOutput,
    GetPolicyInput,
    GetPolicyOutput,
    GetRetrieverInput,
    GetRetrieverOutput,
    GetUserInput,
    GetUserOutput,
    GetWebExperienceInput,
    GetWebExperienceOutput,
    ListApplicationsInput,
    ListApplicationsOutput,
    ListAttachmentsInput,
    ListAttachmentsOutput,
    ListChatResponseConfigurationsInput,
    ListChatResponseConfigurationsOutput,
    ListConversationsInput,
    ListConversationsOutput,
    ListDataAccessorsInput,
    ListDataAccessorsOutput,
    ListDataSourceSyncJobsInput,
    ListDataSourceSyncJobsOutput,
    ListDataSourcesInput,
    ListDataSourcesOutput,
    ListDocumentsInput,
    ListDocumentsOutput,
    ListGroupsInput,
    ListGroupsOutput,
    ListIndicesInput,
    ListIndicesOutput,
    ListMessagesInput,
    ListMessagesOutput,
    ListPluginActionsInput,
    ListPluginActionsOutput,
    ListPluginTypeActionsInput,
    ListPluginTypeActionsOutput,
    ListPluginTypeMetadataInput,
    ListPluginTypeMetadataOutput,
    ListPluginsInput,
    ListPluginsOutput,
    ListRetrieversInput,
    ListRetrieversOutput,
    ListSubscriptionsInput,
    ListSubscriptionsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    ListWebExperiencesInput,
    ListWebExperiencesOutput,
    PutFeedbackInput,
    PutFeedbackOutput,
    PutGroupInput,
    PutGroupOutput,
    SearchRelevantContentInput,
    SearchRelevantContentOutput,
    StartDataSourceSyncJobInput,
    StartDataSourceSyncJobOutput,
    StopDataSourceSyncJobInput,
    StopDataSourceSyncJobOutput,
    TagResourceInput,
    TagResourceOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateApplicationInput,
    UpdateApplicationOutput,
    UpdateChatControlsConfigurationInput,
    UpdateChatControlsConfigurationOutput,
    UpdateChatResponseConfigurationInput,
    UpdateChatResponseConfigurationOutput,
    UpdateDataAccessorInput,
    UpdateDataAccessorOutput,
    UpdateDataSourceInput,
    UpdateDataSourceOutput,
    UpdateIndexInput,
    UpdateIndexOutput,
    UpdatePluginInput,
    UpdatePluginOutput,
    UpdateRetrieverInput,
    UpdateRetrieverOutput,
    UpdateSubscriptionInput,
    UpdateSubscriptionOutput,
    UpdateUserInput,
    UpdateUserOutput,
    UpdateWebExperienceInput,
    UpdateWebExperienceOutput,
)


_ServiceInterceptor = Union[
    Interceptor[AssociatePermissionInput, AssociatePermissionOutput, Any, Any],
    Interceptor[BatchDeleteDocumentInput, BatchDeleteDocumentOutput, Any, Any],
    Interceptor[BatchPutDocumentInput, BatchPutDocumentOutput, Any, Any],
    Interceptor[CancelSubscriptionInput, CancelSubscriptionOutput, Any, Any],
    Interceptor[ChatInput, ChatOutput, Any, Any],
    Interceptor[ChatSyncInput, ChatSyncOutput, Any, Any],
    Interceptor[CheckDocumentAccessInput, CheckDocumentAccessOutput, Any, Any],
    Interceptor[
        CreateAnonymousWebExperienceUrlInput,
        CreateAnonymousWebExperienceUrlOutput,
        Any,
        Any,
    ],
    Interceptor[CreateApplicationInput, CreateApplicationOutput, Any, Any],
    Interceptor[
        CreateChatResponseConfigurationInput,
        CreateChatResponseConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[CreateDataAccessorInput, CreateDataAccessorOutput, Any, Any],
    Interceptor[CreateDataSourceInput, CreateDataSourceOutput, Any, Any],
    Interceptor[CreateIndexInput, CreateIndexOutput, Any, Any],
    Interceptor[CreatePluginInput, CreatePluginOutput, Any, Any],
    Interceptor[CreateRetrieverInput, CreateRetrieverOutput, Any, Any],
    Interceptor[CreateSubscriptionInput, CreateSubscriptionOutput, Any, Any],
    Interceptor[CreateUserInput, CreateUserOutput, Any, Any],
    Interceptor[CreateWebExperienceInput, CreateWebExperienceOutput, Any, Any],
    Interceptor[DeleteApplicationInput, DeleteApplicationOutput, Any, Any],
    Interceptor[DeleteAttachmentInput, DeleteAttachmentOutput, Any, Any],
    Interceptor[
        DeleteChatControlsConfigurationInput,
        DeleteChatControlsConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteChatResponseConfigurationInput,
        DeleteChatResponseConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteConversationInput, DeleteConversationOutput, Any, Any],
    Interceptor[DeleteDataAccessorInput, DeleteDataAccessorOutput, Any, Any],
    Interceptor[DeleteDataSourceInput, DeleteDataSourceOutput, Any, Any],
    Interceptor[DeleteGroupInput, DeleteGroupOutput, Any, Any],
    Interceptor[DeleteIndexInput, DeleteIndexOutput, Any, Any],
    Interceptor[DeletePluginInput, DeletePluginOutput, Any, Any],
    Interceptor[DeleteRetrieverInput, DeleteRetrieverOutput, Any, Any],
    Interceptor[DeleteUserInput, DeleteUserOutput, Any, Any],
    Interceptor[DeleteWebExperienceInput, DeleteWebExperienceOutput, Any, Any],
    Interceptor[DisassociatePermissionInput, DisassociatePermissionOutput, Any, Any],
    Interceptor[GetApplicationInput, GetApplicationOutput, Any, Any],
    Interceptor[
        GetChatControlsConfigurationInput, GetChatControlsConfigurationOutput, Any, Any
    ],
    Interceptor[
        GetChatResponseConfigurationInput, GetChatResponseConfigurationOutput, Any, Any
    ],
    Interceptor[GetDataAccessorInput, GetDataAccessorOutput, Any, Any],
    Interceptor[GetDataSourceInput, GetDataSourceOutput, Any, Any],
    Interceptor[GetDocumentContentInput, GetDocumentContentOutput, Any, Any],
    Interceptor[GetGroupInput, GetGroupOutput, Any, Any],
    Interceptor[GetIndexInput, GetIndexOutput, Any, Any],
    Interceptor[GetMediaInput, GetMediaOutput, Any, Any],
    Interceptor[GetPluginInput, GetPluginOutput, Any, Any],
    Interceptor[GetPolicyInput, GetPolicyOutput, Any, Any],
    Interceptor[GetRetrieverInput, GetRetrieverOutput, Any, Any],
    Interceptor[GetUserInput, GetUserOutput, Any, Any],
    Interceptor[GetWebExperienceInput, GetWebExperienceOutput, Any, Any],
    Interceptor[ListApplicationsInput, ListApplicationsOutput, Any, Any],
    Interceptor[ListAttachmentsInput, ListAttachmentsOutput, Any, Any],
    Interceptor[
        ListChatResponseConfigurationsInput,
        ListChatResponseConfigurationsOutput,
        Any,
        Any,
    ],
    Interceptor[ListConversationsInput, ListConversationsOutput, Any, Any],
    Interceptor[ListDataAccessorsInput, ListDataAccessorsOutput, Any, Any],
    Interceptor[ListDataSourcesInput, ListDataSourcesOutput, Any, Any],
    Interceptor[ListDataSourceSyncJobsInput, ListDataSourceSyncJobsOutput, Any, Any],
    Interceptor[ListDocumentsInput, ListDocumentsOutput, Any, Any],
    Interceptor[ListGroupsInput, ListGroupsOutput, Any, Any],
    Interceptor[ListIndicesInput, ListIndicesOutput, Any, Any],
    Interceptor[ListMessagesInput, ListMessagesOutput, Any, Any],
    Interceptor[ListPluginActionsInput, ListPluginActionsOutput, Any, Any],
    Interceptor[ListPluginsInput, ListPluginsOutput, Any, Any],
    Interceptor[ListPluginTypeActionsInput, ListPluginTypeActionsOutput, Any, Any],
    Interceptor[ListPluginTypeMetadataInput, ListPluginTypeMetadataOutput, Any, Any],
    Interceptor[ListRetrieversInput, ListRetrieversOutput, Any, Any],
    Interceptor[ListSubscriptionsInput, ListSubscriptionsOutput, Any, Any],
    Interceptor[ListTagsForResourceInput, ListTagsForResourceOutput, Any, Any],
    Interceptor[ListWebExperiencesInput, ListWebExperiencesOutput, Any, Any],
    Interceptor[PutFeedbackInput, PutFeedbackOutput, Any, Any],
    Interceptor[PutGroupInput, PutGroupOutput, Any, Any],
    Interceptor[SearchRelevantContentInput, SearchRelevantContentOutput, Any, Any],
    Interceptor[StartDataSourceSyncJobInput, StartDataSourceSyncJobOutput, Any, Any],
    Interceptor[StopDataSourceSyncJobInput, StopDataSourceSyncJobOutput, Any, Any],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[UpdateApplicationInput, UpdateApplicationOutput, Any, Any],
    Interceptor[
        UpdateChatControlsConfigurationInput,
        UpdateChatControlsConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateChatResponseConfigurationInput,
        UpdateChatResponseConfigurationOutput,
        Any,
        Any,
    ],
    Interceptor[UpdateDataAccessorInput, UpdateDataAccessorOutput, Any, Any],
    Interceptor[UpdateDataSourceInput, UpdateDataSourceOutput, Any, Any],
    Interceptor[UpdateIndexInput, UpdateIndexOutput, Any, Any],
    Interceptor[UpdatePluginInput, UpdatePluginOutput, Any, Any],
    Interceptor[UpdateRetrieverInput, UpdateRetrieverOutput, Any, Any],
    Interceptor[UpdateSubscriptionInput, UpdateSubscriptionOutput, Any, Any],
    Interceptor[UpdateUserInput, UpdateUserOutput, Any, Any],
    Interceptor[UpdateWebExperienceInput, UpdateWebExperienceOutput, Any, Any],
]


@dataclass(init=False)
class Config:
    """Configuration for QBusiness."""

    auth_scheme_resolver: HTTPAuthSchemeResolver
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]]
    """A map of auth scheme ids to auth schemes."""

    aws_access_key_id: str | None
    """The identifier for a secret access key."""

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    )
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    aws_secret_access_key: str | None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None
    """An access key ID that identifies temporary security credentials."""

    endpoint_resolver: EndpointResolver
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    endpoint_uri: str | URI | None
    """A static URI to route requests to."""

    http_request_config: HTTPRequestConfiguration | None
    """Configuration for individual HTTP requests."""

    interceptors: list[_ServiceInterceptor]
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    protocol: ClientProtocol[Any, Any] | None
    """The protocol to serialize and deserialize requests with."""

    region: str | None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    retry_strategy: RetryStrategy | RetryStrategyOptions | None
    """
    The retry strategy or options for configuring retry behavior. Can be
    either a configured RetryStrategy or RetryStrategyOptions to create one.
    """

    sdk_ua_app_id: str | None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    transport: ClientTransport[Any, Any] | None
    """
    The transport to use to send requests (e.g. an HTTP client). Operations
    with bidirectional event streams require a DuplexClientTransport, such
    as AWSCRTHTTPClient. Transports are assumed not to support duplex
    streaming unless they explicitly set SUPPORTS_DUPLEX_STREAMING to True.
    """

    user_agent_extra: str | None
    """Additional suffix to be added to the User-Agent header."""

    def __init__(
        self,
        *,
        auth_scheme_resolver: HTTPAuthSchemeResolver | None = None,
        auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None,
        aws_access_key_id: str | None = None,
        aws_credentials_identity_resolver: IdentityResolver[
            AWSCredentialsIdentity, AWSIdentityProperties
        ]
        | None = None,
        aws_secret_access_key: str | None = None,
        aws_session_token: str | None = None,
        endpoint_resolver: EndpointResolver | None = None,
        endpoint_uri: str | URI | None = None,
        http_request_config: HTTPRequestConfiguration | None = None,
        interceptors: list[_ServiceInterceptor] | None = None,
        protocol: ClientProtocol[Any, Any] | None = None,
        region: str | None = None,
        retry_strategy: RetryStrategy | RetryStrategyOptions | None = None,
        sdk_ua_app_id: str | None = None,
        transport: ClientTransport[Any, Any] | None = None,
        user_agent_extra: str | None = None,
    ):
        self.auth_scheme_resolver = auth_scheme_resolver or HTTPAuthSchemeResolver()
        self.auth_schemes = auth_schemes or {
            ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="qbusiness")
        }
        self.aws_access_key_id = aws_access_key_id
        self.aws_credentials_identity_resolver = aws_credentials_identity_resolver
        self.aws_secret_access_key = aws_secret_access_key
        self.aws_session_token = aws_session_token
        self.endpoint_resolver = endpoint_resolver or StandardRegionalEndpointsResolver(
            endpoint_prefix="qbusiness"
        )
        self.endpoint_uri = endpoint_uri
        self.http_request_config = http_request_config
        self.interceptors = interceptors or []
        self.protocol = protocol or RestJsonClientProtocol(_SCHEMA_EXPERT_Q)
        self.region = region
        self.retry_strategy = retry_strategy
        self.sdk_ua_app_id = sdk_ua_app_id
        self.transport = transport or AWSCRTHTTPClient()
        self.user_agent_extra = user_agent_extra

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Sets the implementation of an auth scheme.

        Using this method ensures the correct key is used.

        Args:
            scheme:
                The auth scheme to add.
        """
        self.auth_schemes[scheme.scheme_id] = scheme


Plugin: TypeAlias = Callable[[Config], None]
"""A callable that allows customizing the config object on each request."""
