# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
from typing import Any, Callable, TypeAlias, Union

from smithy_aws_core.aio.protocols import AwsQueryClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, ClientTransport, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.aio.interfaces.retries import RetryStrategy
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces import URI
from smithy_core.retries import RetryStrategyOptions
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient
from smithy_http.interfaces import HTTPRequestConfiguration

from ._private.schemas import (
    AMAZON_SIMPLE_NOTIFICATION_SERVICE as _SCHEMA_AMAZON_SIMPLE_NOTIFICATION_SERVICE,
)
from .auth import HTTPAuthSchemeResolver
from .models import (
    AddPermissionInput,
    AddPermissionOutput,
    CheckIfPhoneNumberIsOptedOutInput,
    CheckIfPhoneNumberIsOptedOutOutput,
    ConfirmSubscriptionInput,
    ConfirmSubscriptionOutput,
    CreatePlatformApplicationInput,
    CreatePlatformApplicationOutput,
    CreatePlatformEndpointInput,
    CreatePlatformEndpointOutput,
    CreateSMSSandboxPhoneNumberInput,
    CreateSMSSandboxPhoneNumberOutput,
    CreateTopicInput,
    CreateTopicOutput,
    DeleteEndpointInput,
    DeleteEndpointOutput,
    DeletePlatformApplicationInput,
    DeletePlatformApplicationOutput,
    DeleteSMSSandboxPhoneNumberInput,
    DeleteSMSSandboxPhoneNumberOutput,
    DeleteTopicInput,
    DeleteTopicOutput,
    GetDataProtectionPolicyInput,
    GetDataProtectionPolicyOutput,
    GetEndpointAttributesInput,
    GetEndpointAttributesOutput,
    GetPlatformApplicationAttributesInput,
    GetPlatformApplicationAttributesOutput,
    GetSMSAttributesInput,
    GetSMSAttributesOutput,
    GetSMSSandboxAccountStatusInput,
    GetSMSSandboxAccountStatusOutput,
    GetSubscriptionAttributesInput,
    GetSubscriptionAttributesOutput,
    GetTopicAttributesInput,
    GetTopicAttributesOutput,
    ListEndpointsByPlatformApplicationInput,
    ListEndpointsByPlatformApplicationOutput,
    ListOriginationNumbersInput,
    ListOriginationNumbersOutput,
    ListPhoneNumbersOptedOutInput,
    ListPhoneNumbersOptedOutOutput,
    ListPlatformApplicationsInput,
    ListPlatformApplicationsOutput,
    ListSMSSandboxPhoneNumbersInput,
    ListSMSSandboxPhoneNumbersOutput,
    ListSubscriptionsByTopicInput,
    ListSubscriptionsByTopicOutput,
    ListSubscriptionsInput,
    ListSubscriptionsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    ListTopicsInput,
    ListTopicsOutput,
    OptInPhoneNumberInput,
    OptInPhoneNumberOutput,
    PublishBatchInput,
    PublishBatchOutput,
    PublishInput,
    PublishOutput,
    PutDataProtectionPolicyInput,
    PutDataProtectionPolicyOutput,
    RemovePermissionInput,
    RemovePermissionOutput,
    SetEndpointAttributesInput,
    SetEndpointAttributesOutput,
    SetPlatformApplicationAttributesInput,
    SetPlatformApplicationAttributesOutput,
    SetSMSAttributesInput,
    SetSMSAttributesOutput,
    SetSubscriptionAttributesInput,
    SetSubscriptionAttributesOutput,
    SetTopicAttributesInput,
    SetTopicAttributesOutput,
    SubscribeInput,
    SubscribeOutput,
    TagResourceInput,
    TagResourceOutput,
    UnsubscribeInput,
    UnsubscribeOutput,
    UntagResourceInput,
    UntagResourceOutput,
    VerifySMSSandboxPhoneNumberInput,
    VerifySMSSandboxPhoneNumberOutput,
)


_ServiceInterceptor = Union[
    Interceptor[AddPermissionInput, AddPermissionOutput, Any, Any],
    Interceptor[
        CheckIfPhoneNumberIsOptedOutInput, CheckIfPhoneNumberIsOptedOutOutput, Any, Any
    ],
    Interceptor[ConfirmSubscriptionInput, ConfirmSubscriptionOutput, Any, Any],
    Interceptor[
        CreatePlatformApplicationInput, CreatePlatformApplicationOutput, Any, Any
    ],
    Interceptor[CreatePlatformEndpointInput, CreatePlatformEndpointOutput, Any, Any],
    Interceptor[
        CreateSMSSandboxPhoneNumberInput, CreateSMSSandboxPhoneNumberOutput, Any, Any
    ],
    Interceptor[CreateTopicInput, CreateTopicOutput, Any, Any],
    Interceptor[DeleteEndpointInput, DeleteEndpointOutput, Any, Any],
    Interceptor[
        DeletePlatformApplicationInput, DeletePlatformApplicationOutput, Any, Any
    ],
    Interceptor[
        DeleteSMSSandboxPhoneNumberInput, DeleteSMSSandboxPhoneNumberOutput, Any, Any
    ],
    Interceptor[DeleteTopicInput, DeleteTopicOutput, Any, Any],
    Interceptor[GetDataProtectionPolicyInput, GetDataProtectionPolicyOutput, Any, Any],
    Interceptor[GetEndpointAttributesInput, GetEndpointAttributesOutput, Any, Any],
    Interceptor[
        GetPlatformApplicationAttributesInput,
        GetPlatformApplicationAttributesOutput,
        Any,
        Any,
    ],
    Interceptor[GetSMSAttributesInput, GetSMSAttributesOutput, Any, Any],
    Interceptor[
        GetSMSSandboxAccountStatusInput, GetSMSSandboxAccountStatusOutput, Any, Any
    ],
    Interceptor[
        GetSubscriptionAttributesInput, GetSubscriptionAttributesOutput, Any, Any
    ],
    Interceptor[GetTopicAttributesInput, GetTopicAttributesOutput, Any, Any],
    Interceptor[
        ListEndpointsByPlatformApplicationInput,
        ListEndpointsByPlatformApplicationOutput,
        Any,
        Any,
    ],
    Interceptor[ListOriginationNumbersInput, ListOriginationNumbersOutput, Any, Any],
    Interceptor[
        ListPhoneNumbersOptedOutInput, ListPhoneNumbersOptedOutOutput, Any, Any
    ],
    Interceptor[
        ListPlatformApplicationsInput, ListPlatformApplicationsOutput, Any, Any
    ],
    Interceptor[
        ListSMSSandboxPhoneNumbersInput, ListSMSSandboxPhoneNumbersOutput, Any, Any
    ],
    Interceptor[ListSubscriptionsInput, ListSubscriptionsOutput, Any, Any],
    Interceptor[
        ListSubscriptionsByTopicInput, ListSubscriptionsByTopicOutput, Any, Any
    ],
    Interceptor[ListTagsForResourceInput, ListTagsForResourceOutput, Any, Any],
    Interceptor[ListTopicsInput, ListTopicsOutput, Any, Any],
    Interceptor[OptInPhoneNumberInput, OptInPhoneNumberOutput, Any, Any],
    Interceptor[PublishInput, PublishOutput, Any, Any],
    Interceptor[PublishBatchInput, PublishBatchOutput, Any, Any],
    Interceptor[PutDataProtectionPolicyInput, PutDataProtectionPolicyOutput, Any, Any],
    Interceptor[RemovePermissionInput, RemovePermissionOutput, Any, Any],
    Interceptor[SetEndpointAttributesInput, SetEndpointAttributesOutput, Any, Any],
    Interceptor[
        SetPlatformApplicationAttributesInput,
        SetPlatformApplicationAttributesOutput,
        Any,
        Any,
    ],
    Interceptor[SetSMSAttributesInput, SetSMSAttributesOutput, Any, Any],
    Interceptor[
        SetSubscriptionAttributesInput, SetSubscriptionAttributesOutput, Any, Any
    ],
    Interceptor[SetTopicAttributesInput, SetTopicAttributesOutput, Any, Any],
    Interceptor[SubscribeInput, SubscribeOutput, Any, Any],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[UnsubscribeInput, UnsubscribeOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[
        VerifySMSSandboxPhoneNumberInput, VerifySMSSandboxPhoneNumberOutput, Any, Any
    ],
]


@dataclass(init=False)
class Config:
    """Configuration for SNS."""

    auth_scheme_resolver: HTTPAuthSchemeResolver
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]]
    """A map of auth scheme ids to auth schemes."""

    aws_access_key_id: str | None
    """The identifier for a secret access key."""

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    )
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    aws_secret_access_key: str | None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None
    """An access key ID that identifies temporary security credentials."""

    endpoint_resolver: EndpointResolver
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    endpoint_uri: str | URI | None
    """A static URI to route requests to."""

    http_request_config: HTTPRequestConfiguration | None
    """Configuration for individual HTTP requests."""

    interceptors: list[_ServiceInterceptor]
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    protocol: ClientProtocol[Any, Any] | None
    """The protocol to serialize and deserialize requests with."""

    region: str | None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    retry_strategy: RetryStrategy | RetryStrategyOptions | None
    """
    The retry strategy or options for configuring retry behavior. Can be
    either a configured RetryStrategy or RetryStrategyOptions to create one.
    """

    sdk_ua_app_id: str | None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    transport: ClientTransport[Any, Any] | None
    """The transport to use to send requests (e.g. an HTTP client)."""

    user_agent_extra: str | None
    """Additional suffix to be added to the User-Agent header."""

    def __init__(
        self,
        *,
        auth_scheme_resolver: HTTPAuthSchemeResolver | None = None,
        auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None,
        aws_access_key_id: str | None = None,
        aws_credentials_identity_resolver: IdentityResolver[
            AWSCredentialsIdentity, AWSIdentityProperties
        ]
        | None = None,
        aws_secret_access_key: str | None = None,
        aws_session_token: str | None = None,
        endpoint_resolver: EndpointResolver | None = None,
        endpoint_uri: str | URI | None = None,
        http_request_config: HTTPRequestConfiguration | None = None,
        interceptors: list[_ServiceInterceptor] | None = None,
        protocol: ClientProtocol[Any, Any] | None = None,
        region: str | None = None,
        retry_strategy: RetryStrategy | RetryStrategyOptions | None = None,
        sdk_ua_app_id: str | None = None,
        transport: ClientTransport[Any, Any] | None = None,
        user_agent_extra: str | None = None,
    ):
        self.auth_scheme_resolver = auth_scheme_resolver or HTTPAuthSchemeResolver()
        self.auth_schemes = auth_schemes or {
            ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="sns")
        }
        self.aws_access_key_id = aws_access_key_id
        self.aws_credentials_identity_resolver = aws_credentials_identity_resolver
        self.aws_secret_access_key = aws_secret_access_key
        self.aws_session_token = aws_session_token
        self.endpoint_resolver = endpoint_resolver or StandardRegionalEndpointsResolver(
            endpoint_prefix="sns"
        )
        self.endpoint_uri = endpoint_uri
        self.http_request_config = http_request_config
        self.interceptors = interceptors or []
        self.protocol = protocol or AwsQueryClientProtocol(
            _SCHEMA_AMAZON_SIMPLE_NOTIFICATION_SERVICE, "2010-03-31"
        )
        self.region = region
        self.retry_strategy = retry_strategy
        self.sdk_ua_app_id = sdk_ua_app_id
        self.transport = transport or AIOHTTPClient()
        self.user_agent_extra = user_agent_extra

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Sets the implementation of an auth scheme.

        Using this method ensures the correct key is used.

        Args:
            scheme:
                The auth scheme to add.
        """
        self.auth_schemes[scheme.scheme_id] = scheme


Plugin: TypeAlias = Callable[[Config], None]
"""A callable that allows customizing the config object on each request."""
