# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging

from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.plugins import user_agent_plugin

from .config import Config, Plugin
from .models import (
    COPY_BLUEPRINT_STAGE,
    CREATE_BLUEPRINT,
    CREATE_BLUEPRINT_VERSION,
    CREATE_DATA_AUTOMATION_LIBRARY,
    CREATE_DATA_AUTOMATION_PROJECT,
    CopyBlueprintStageInput,
    CopyBlueprintStageOutput,
    CreateBlueprintInput,
    CreateBlueprintOutput,
    CreateBlueprintVersionInput,
    CreateBlueprintVersionOutput,
    CreateDataAutomationLibraryInput,
    CreateDataAutomationLibraryOutput,
    CreateDataAutomationProjectInput,
    CreateDataAutomationProjectOutput,
    DELETE_BLUEPRINT,
    DELETE_DATA_AUTOMATION_LIBRARY,
    DELETE_DATA_AUTOMATION_PROJECT,
    DeleteBlueprintInput,
    DeleteBlueprintOutput,
    DeleteDataAutomationLibraryInput,
    DeleteDataAutomationLibraryOutput,
    DeleteDataAutomationProjectInput,
    DeleteDataAutomationProjectOutput,
    GET_BLUEPRINT,
    GET_BLUEPRINT_OPTIMIZATION_STATUS,
    GET_DATA_AUTOMATION_LIBRARY,
    GET_DATA_AUTOMATION_LIBRARY_ENTITY,
    GET_DATA_AUTOMATION_LIBRARY_INGESTION_JOB,
    GET_DATA_AUTOMATION_PROJECT,
    GetBlueprintInput,
    GetBlueprintOptimizationStatusInput,
    GetBlueprintOptimizationStatusOutput,
    GetBlueprintOutput,
    GetDataAutomationLibraryEntityInput,
    GetDataAutomationLibraryEntityOutput,
    GetDataAutomationLibraryIngestionJobInput,
    GetDataAutomationLibraryIngestionJobOutput,
    GetDataAutomationLibraryInput,
    GetDataAutomationLibraryOutput,
    GetDataAutomationProjectInput,
    GetDataAutomationProjectOutput,
    INVOKE_BLUEPRINT_OPTIMIZATION_ASYNC,
    INVOKE_DATA_AUTOMATION_LIBRARY_INGESTION_JOB,
    InvokeBlueprintOptimizationAsyncInput,
    InvokeBlueprintOptimizationAsyncOutput,
    InvokeDataAutomationLibraryIngestionJobInput,
    InvokeDataAutomationLibraryIngestionJobOutput,
    LIST_BLUEPRINTS,
    LIST_DATA_AUTOMATION_LIBRARIES,
    LIST_DATA_AUTOMATION_LIBRARY_ENTITIES,
    LIST_DATA_AUTOMATION_LIBRARY_INGESTION_JOBS,
    LIST_DATA_AUTOMATION_PROJECTS,
    LIST_TAGS_FOR_RESOURCE,
    ListBlueprintsInput,
    ListBlueprintsOutput,
    ListDataAutomationLibrariesInput,
    ListDataAutomationLibrariesOutput,
    ListDataAutomationLibraryEntitiesInput,
    ListDataAutomationLibraryEntitiesOutput,
    ListDataAutomationLibraryIngestionJobsInput,
    ListDataAutomationLibraryIngestionJobsOutput,
    ListDataAutomationProjectsInput,
    ListDataAutomationProjectsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    TAG_RESOURCE,
    TagResourceInput,
    TagResourceOutput,
    UNTAG_RESOURCE,
    UPDATE_BLUEPRINT,
    UPDATE_DATA_AUTOMATION_LIBRARY,
    UPDATE_DATA_AUTOMATION_PROJECT,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateBlueprintInput,
    UpdateBlueprintOutput,
    UpdateDataAutomationLibraryInput,
    UpdateDataAutomationLibraryOutput,
    UpdateDataAutomationProjectInput,
    UpdateDataAutomationProjectOutput,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncBedrockDataAutomationClient:
    """Amazon Bedrock Data Automation BuildTime"""

    def __init__(
        self, config: Config | None = None, plugins: list[Plugin] | None = None
    ):
        """
        Constructor for `AsyncBedrockDataAutomationClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables that modify the configuration dynamically. These
                can be used to set defaults, for example.
        """
        self._config = config or Config()

        client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]
        if plugins:
            client_plugins.extend(plugins)

        for plugin in client_plugins:
            plugin(self._config)

        self._retry_strategy_resolver = RetryStrategyResolver()

    async def copy_blueprint_stage(
        self, input: CopyBlueprintStageInput, plugins: list[Plugin] | None = None
    ) -> CopyBlueprintStageOutput:
        """
        Copies a Blueprint from one stage to another

        Args:
            input:
                An instance of `CopyBlueprintStageInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CopyBlueprintStageOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=COPY_BLUEPRINT_STAGE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def create_blueprint(
        self, input: CreateBlueprintInput, plugins: list[Plugin] | None = None
    ) -> CreateBlueprintOutput:
        """
        Creates an Amazon Bedrock Data Automation Blueprint

        Args:
            input:
                An instance of `CreateBlueprintInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateBlueprintOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=CREATE_BLUEPRINT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def create_blueprint_version(
        self, input: CreateBlueprintVersionInput, plugins: list[Plugin] | None = None
    ) -> CreateBlueprintVersionOutput:
        """
        Creates a new version of an existing Amazon Bedrock Data Automation
        Blueprint

        Args:
            input:
                An instance of `CreateBlueprintVersionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateBlueprintVersionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=CREATE_BLUEPRINT_VERSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def create_data_automation_library(
        self,
        input: CreateDataAutomationLibraryInput,
        plugins: list[Plugin] | None = None,
    ) -> CreateDataAutomationLibraryOutput:
        """
        Creates an Amazon Bedrock Data Automation Library

        Args:
            input:
                An instance of `CreateDataAutomationLibraryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateDataAutomationLibraryOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=CREATE_DATA_AUTOMATION_LIBRARY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def create_data_automation_project(
        self,
        input: CreateDataAutomationProjectInput,
        plugins: list[Plugin] | None = None,
    ) -> CreateDataAutomationProjectOutput:
        """
        Creates an Amazon Bedrock Data Automation Project

        Args:
            input:
                An instance of `CreateDataAutomationProjectInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateDataAutomationProjectOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=CREATE_DATA_AUTOMATION_PROJECT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def delete_blueprint(
        self, input: DeleteBlueprintInput, plugins: list[Plugin] | None = None
    ) -> DeleteBlueprintOutput:
        """
        Deletes an existing Amazon Bedrock Data Automation Blueprint

        Args:
            input:
                An instance of `DeleteBlueprintInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteBlueprintOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DELETE_BLUEPRINT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def delete_data_automation_library(
        self,
        input: DeleteDataAutomationLibraryInput,
        plugins: list[Plugin] | None = None,
    ) -> DeleteDataAutomationLibraryOutput:
        """
        Deletes an existing Amazon Bedrock Data Automation Library

        Args:
            input:
                An instance of `DeleteDataAutomationLibraryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteDataAutomationLibraryOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DELETE_DATA_AUTOMATION_LIBRARY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def delete_data_automation_project(
        self,
        input: DeleteDataAutomationProjectInput,
        plugins: list[Plugin] | None = None,
    ) -> DeleteDataAutomationProjectOutput:
        """
        Deletes an existing Amazon Bedrock Data Automation Project

        Args:
            input:
                An instance of `DeleteDataAutomationProjectInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteDataAutomationProjectOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DELETE_DATA_AUTOMATION_PROJECT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_blueprint(
        self, input: GetBlueprintInput, plugins: list[Plugin] | None = None
    ) -> GetBlueprintOutput:
        """
        Gets an existing Amazon Bedrock Data Automation Blueprint

        Args:
            input:
                An instance of `GetBlueprintInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetBlueprintOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_BLUEPRINT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_blueprint_optimization_status(
        self,
        input: GetBlueprintOptimizationStatusInput,
        plugins: list[Plugin] | None = None,
    ) -> GetBlueprintOptimizationStatusOutput:
        """
        API used to get blueprint optimization status.

        Args:
            input:
                An instance of `GetBlueprintOptimizationStatusInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetBlueprintOptimizationStatusOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_BLUEPRINT_OPTIMIZATION_STATUS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_data_automation_library(
        self, input: GetDataAutomationLibraryInput, plugins: list[Plugin] | None = None
    ) -> GetDataAutomationLibraryOutput:
        """
        Gets an existing Amazon Bedrock Data Automation Library

        Args:
            input:
                An instance of `GetDataAutomationLibraryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDataAutomationLibraryOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_DATA_AUTOMATION_LIBRARY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_data_automation_library_entity(
        self,
        input: GetDataAutomationLibraryEntityInput,
        plugins: list[Plugin] | None = None,
    ) -> GetDataAutomationLibraryEntityOutput:
        """
        Gets an existing entity based on entity type from the library

        Args:
            input:
                An instance of `GetDataAutomationLibraryEntityInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDataAutomationLibraryEntityOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_DATA_AUTOMATION_LIBRARY_ENTITY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_data_automation_library_ingestion_job(
        self,
        input: GetDataAutomationLibraryIngestionJobInput,
        plugins: list[Plugin] | None = None,
    ) -> GetDataAutomationLibraryIngestionJobOutput:
        """
        API used to get status of data automation library ingestion job

        Args:
            input:
                An instance of `GetDataAutomationLibraryIngestionJobInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDataAutomationLibraryIngestionJobOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_DATA_AUTOMATION_LIBRARY_INGESTION_JOB,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_data_automation_project(
        self, input: GetDataAutomationProjectInput, plugins: list[Plugin] | None = None
    ) -> GetDataAutomationProjectOutput:
        """
        Gets an existing Amazon Bedrock Data Automation Project

        Args:
            input:
                An instance of `GetDataAutomationProjectInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDataAutomationProjectOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_DATA_AUTOMATION_PROJECT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def invoke_blueprint_optimization_async(
        self,
        input: InvokeBlueprintOptimizationAsyncInput,
        plugins: list[Plugin] | None = None,
    ) -> InvokeBlueprintOptimizationAsyncOutput:
        """
        Invoke an async job to perform Blueprint Optimization

        Args:
            input:
                An instance of `InvokeBlueprintOptimizationAsyncInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `InvokeBlueprintOptimizationAsyncOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=INVOKE_BLUEPRINT_OPTIMIZATION_ASYNC,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def invoke_data_automation_library_ingestion_job(
        self,
        input: InvokeDataAutomationLibraryIngestionJobInput,
        plugins: list[Plugin] | None = None,
    ) -> InvokeDataAutomationLibraryIngestionJobOutput:
        """
        Async API: Invoke data automation library ingestion job

        Args:
            input:
                An instance of `InvokeDataAutomationLibraryIngestionJobInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `InvokeDataAutomationLibraryIngestionJobOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=INVOKE_DATA_AUTOMATION_LIBRARY_INGESTION_JOB,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_blueprints(
        self, input: ListBlueprintsInput, plugins: list[Plugin] | None = None
    ) -> ListBlueprintsOutput:
        """
        Lists all existing Amazon Bedrock Data Automation Blueprints

        Args:
            input:
                An instance of `ListBlueprintsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListBlueprintsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_BLUEPRINTS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_data_automation_libraries(
        self,
        input: ListDataAutomationLibrariesInput,
        plugins: list[Plugin] | None = None,
    ) -> ListDataAutomationLibrariesOutput:
        """
        Lists all existing Amazon Bedrock Data Automation Libraries

        Args:
            input:
                An instance of `ListDataAutomationLibrariesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListDataAutomationLibrariesOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_DATA_AUTOMATION_LIBRARIES,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_data_automation_library_entities(
        self,
        input: ListDataAutomationLibraryEntitiesInput,
        plugins: list[Plugin] | None = None,
    ) -> ListDataAutomationLibraryEntitiesOutput:
        """
        Lists all stored entities in the library

        Args:
            input:
                An instance of `ListDataAutomationLibraryEntitiesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListDataAutomationLibraryEntitiesOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_DATA_AUTOMATION_LIBRARY_ENTITIES,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_data_automation_library_ingestion_jobs(
        self,
        input: ListDataAutomationLibraryIngestionJobsInput,
        plugins: list[Plugin] | None = None,
    ) -> ListDataAutomationLibraryIngestionJobsOutput:
        """
        Lists all data automation library ingestion jobs

        Args:
            input:
                An instance of `ListDataAutomationLibraryIngestionJobsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListDataAutomationLibraryIngestionJobsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_DATA_AUTOMATION_LIBRARY_INGESTION_JOBS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_data_automation_projects(
        self,
        input: ListDataAutomationProjectsInput,
        plugins: list[Plugin] | None = None,
    ) -> ListDataAutomationProjectsOutput:
        """
        Lists all existing Amazon Bedrock Data Automation Projects

        Args:
            input:
                An instance of `ListDataAutomationProjectsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListDataAutomationProjectsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_DATA_AUTOMATION_PROJECTS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_tags_for_resource(
        self, input: ListTagsForResourceInput, plugins: list[Plugin] | None = None
    ) -> ListTagsForResourceOutput:
        """
        List tags for an Amazon Bedrock Data Automation resource

        Args:
            input:
                An instance of `ListTagsForResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListTagsForResourceOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_TAGS_FOR_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def tag_resource(
        self, input: TagResourceInput, plugins: list[Plugin] | None = None
    ) -> TagResourceOutput:
        """
        Tag an Amazon Bedrock Data Automation resource

        Args:
            input:
                An instance of `TagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `TagResourceOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=TAG_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def untag_resource(
        self, input: UntagResourceInput, plugins: list[Plugin] | None = None
    ) -> UntagResourceOutput:
        """
        Untag an Amazon Bedrock Data Automation resource

        Args:
            input:
                An instance of `UntagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UntagResourceOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UNTAG_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def update_blueprint(
        self, input: UpdateBlueprintInput, plugins: list[Plugin] | None = None
    ) -> UpdateBlueprintOutput:
        """
        Updates an existing Amazon Bedrock Data Automation Blueprint

        Args:
            input:
                An instance of `UpdateBlueprintInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UpdateBlueprintOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UPDATE_BLUEPRINT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def update_data_automation_library(
        self,
        input: UpdateDataAutomationLibraryInput,
        plugins: list[Plugin] | None = None,
    ) -> UpdateDataAutomationLibraryOutput:
        """
        Updates an existing Amazon Bedrock Data Automation Library

        Args:
            input:
                An instance of `UpdateDataAutomationLibraryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UpdateDataAutomationLibraryOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UPDATE_DATA_AUTOMATION_LIBRARY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def update_data_automation_project(
        self,
        input: UpdateDataAutomationProjectInput,
        plugins: list[Plugin] | None = None,
    ) -> UpdateDataAutomationProjectOutput:
        """
        Updates an existing Amazon Bedrock Data Automation Project

        Args:
            input:
                An instance of `UpdateDataAutomationProjectInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UpdateDataAutomationProjectOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UPDATE_DATA_AUTOMATION_PROJECT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)
