# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging

from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.eventstream import OutputEventStream
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.plugins import user_agent_plugin

from .config import Config, Plugin
from .models import (
    AGENTIC_RETRIEVE_STREAM,
    AgenticRetrieveStreamInput,
    AgenticRetrieveStreamOutput,
    AgenticRetrieveStreamResponseOutput,
    CREATE_INVOCATION,
    CREATE_SESSION,
    CreateInvocationInput,
    CreateInvocationOutput,
    CreateSessionInput,
    CreateSessionOutput,
    DELETE_AGENT_MEMORY,
    DELETE_SESSION,
    DeleteAgentMemoryInput,
    DeleteAgentMemoryOutput,
    DeleteSessionInput,
    DeleteSessionOutput,
    END_SESSION,
    EndSessionInput,
    EndSessionOutput,
    FlowResponseStream,
    GENERATE_QUERY,
    GET_AGENT_MEMORY,
    GET_DOCUMENT_CONTENT,
    GET_EXECUTION_FLOW_SNAPSHOT,
    GET_FLOW_EXECUTION,
    GET_INVOCATION_STEP,
    GET_SESSION,
    GenerateQueryInput,
    GenerateQueryOutput,
    GetAgentMemoryInput,
    GetAgentMemoryOutput,
    GetDocumentContentInput,
    GetDocumentContentOutput,
    GetExecutionFlowSnapshotInput,
    GetExecutionFlowSnapshotOutput,
    GetFlowExecutionInput,
    GetFlowExecutionOutput,
    GetInvocationStepInput,
    GetInvocationStepOutput,
    GetSessionInput,
    GetSessionOutput,
    INVOKE_AGENT,
    INVOKE_FLOW,
    INVOKE_INLINE_AGENT,
    InlineAgentResponseStream,
    InvokeAgentInput,
    InvokeAgentOutput,
    InvokeFlowInput,
    InvokeFlowOutput,
    InvokeInlineAgentInput,
    InvokeInlineAgentOutput,
    LIST_FLOW_EXECUTIONS,
    LIST_FLOW_EXECUTION_EVENTS,
    LIST_INVOCATIONS,
    LIST_INVOCATION_STEPS,
    LIST_SESSIONS,
    LIST_TAGS_FOR_RESOURCE,
    ListFlowExecutionEventsInput,
    ListFlowExecutionEventsOutput,
    ListFlowExecutionsInput,
    ListFlowExecutionsOutput,
    ListInvocationStepsInput,
    ListInvocationStepsOutput,
    ListInvocationsInput,
    ListInvocationsOutput,
    ListSessionsInput,
    ListSessionsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    OPTIMIZE_PROMPT,
    OptimizePromptInput,
    OptimizePromptOutput,
    OptimizedPromptStream,
    PUT_INVOCATION_STEP,
    PutInvocationStepInput,
    PutInvocationStepOutput,
    RERANK,
    RETRIEVE,
    RETRIEVE_AND_GENERATE,
    RETRIEVE_AND_GENERATE_STREAM,
    RerankInput,
    RerankOutput,
    ResponseStream,
    RetrieveAndGenerateOperationInput,
    RetrieveAndGenerateOperationOutput,
    RetrieveAndGenerateStreamInput,
    RetrieveAndGenerateStreamOutput,
    RetrieveAndGenerateStreamResponseOutput,
    RetrieveInput,
    RetrieveOutput,
    START_FLOW_EXECUTION,
    STOP_FLOW_EXECUTION,
    StartFlowExecutionInput,
    StartFlowExecutionOutput,
    StopFlowExecutionInput,
    StopFlowExecutionOutput,
    TAG_RESOURCE,
    TagResourceInput,
    TagResourceOutput,
    UNTAG_RESOURCE,
    UPDATE_SESSION,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateSessionInput,
    UpdateSessionOutput,
    _AgenticRetrieveStreamResponseOutputDeserializer,
    _FlowResponseStreamDeserializer,
    _InlineAgentResponseStreamDeserializer,
    _OptimizedPromptStreamDeserializer,
    _ResponseStreamDeserializer,
    _RetrieveAndGenerateStreamResponseOutputDeserializer,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncBedrockAgentRuntimeClient:
    """
    Contains APIs related to model invocation and querying of knowledge
    bases.
    """

    def __init__(
        self, config: Config | None = None, plugins: list[Plugin] | None = None
    ):
        """
        Constructor for `AsyncBedrockAgentRuntimeClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables that modify the configuration dynamically. These
                can be used to set defaults, for example.
        """
        self._config = config or Config()

        client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]
        if plugins:
            client_plugins.extend(plugins)

        for plugin in client_plugins:
            plugin(self._config)

        self._retry_strategy_resolver = RetryStrategyResolver()

    async def agentic_retrieve_stream(
        self, input: AgenticRetrieveStreamInput, plugins: list[Plugin] | None = None
    ) -> OutputEventStream[
        AgenticRetrieveStreamResponseOutput, AgenticRetrieveStreamOutput
    ]:
        """
        Retrieves information from one or more knowledge bases using an agentic
        approach. Agentic retrieval uses a foundation model to intelligently
        decompose complex queries into sub-queries and iteratively retrieve
        relevant information from your knowledge bases. This approach improves
        retrieval accuracy for complex, multi-step questions that a single
        retrieval pass might not fully address.

        The operation returns results through a stream that includes retrieval
        results, trace events for visibility into the process, and a generated
        response synthesized from the results by default, which can be turned
        off.

        Args:
            input:
                An instance of `AgenticRetrieveStreamInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An `OutputEventStream` for server-to-client streaming.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=AGENTIC_RETRIEVE_STREAM,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline.output_stream(
            call,
            AgenticRetrieveStreamResponseOutput,
            _AgenticRetrieveStreamResponseOutputDeserializer().deserialize,
        )

    async def create_invocation(
        self, input: CreateInvocationInput, plugins: list[Plugin] | None = None
    ) -> CreateInvocationOutput:
        """
        Creates a new invocation within a session. An invocation groups the
        related invocation steps that store the content from a conversation. For
        more information about sessions, see [Store and retrieve conversation
        history and context with Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        Related APIs

        - [ListInvocations](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_ListInvocations.html)

        - [ListSessions](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_ListSessions.html)

        - [GetSession](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_GetSession.html)

        Args:
            input:
                An instance of `CreateInvocationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateInvocationOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=CREATE_INVOCATION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def create_session(
        self, input: CreateSessionInput, plugins: list[Plugin] | None = None
    ) -> CreateSessionOutput:
        """
        Creates a session to temporarily store conversations for generative AI
        (GenAI) applications built with open-source frameworks such as LangGraph
        and LlamaIndex. Sessions enable you to save the state of conversations
        at checkpoints, with the added security and infrastructure of Amazon Web
        Services. For more information, see [Store and retrieve conversation
        history and context with Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        By default, Amazon Bedrock uses Amazon Web Services-managed keys for
        session encryption, including session metadata, or you can use your own
        KMS key. For more information, see [Amazon Bedrock session
        encryption](https://docs.aws.amazon.com/bedrock/latest/userguide/session-encryption.html).

        Note:
            You use a session to store state and conversation history for generative
            AI applications built with open-source frameworks. For Amazon Bedrock
            Agents, the service automatically manages conversation context and
            associates them with the agent-specific sessionId you specify in the
            [InvokeAgent](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_InvokeAgent.html)
            API operation.

        Related APIs:

        - [ListSessions](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_ListSessions.html)

        - [GetSession](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_GetSession.html)

        - [EndSession](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_EndSession.html)

        - [DeleteSession](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_DeleteSession.html)

        Args:
            input:
                An instance of `CreateSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateSessionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=CREATE_SESSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def delete_agent_memory(
        self, input: DeleteAgentMemoryInput, plugins: list[Plugin] | None = None
    ) -> DeleteAgentMemoryOutput:
        """
        Deletes memory from the specified memory identifier.

        Args:
            input:
                An instance of `DeleteAgentMemoryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteAgentMemoryOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DELETE_AGENT_MEMORY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def delete_session(
        self, input: DeleteSessionInput, plugins: list[Plugin] | None = None
    ) -> DeleteSessionOutput:
        """
        Deletes a session that you ended. You can't delete a session with an
        `ACTIVE` status. To delete an active session, you must first end it with
        the
        [EndSession](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_EndSession.html)
        API operation. For more information about sessions, see [Store and
        retrieve conversation history and context with Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        Args:
            input:
                An instance of `DeleteSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteSessionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DELETE_SESSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def end_session(
        self, input: EndSessionInput, plugins: list[Plugin] | None = None
    ) -> EndSessionOutput:
        """
        Ends the session. After you end a session, you can still access its
        content but you can't add to it. To delete the session and it's
        content, you use the DeleteSession API operation. For more information
        about sessions, see [Store and retrieve conversation history and context
        with Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        Args:
            input:
                An instance of `EndSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `EndSessionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=END_SESSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def generate_query(
        self, input: GenerateQueryInput, plugins: list[Plugin] | None = None
    ) -> GenerateQueryOutput:
        """
        Generates an SQL query from a natural language query. For more
        information, see [Generate a query for structured
        data](https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-generate-query.html)
        in the Amazon Bedrock User Guide.

        Args:
            input:
                An instance of `GenerateQueryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GenerateQueryOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GENERATE_QUERY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_agent_memory(
        self, input: GetAgentMemoryInput, plugins: list[Plugin] | None = None
    ) -> GetAgentMemoryOutput:
        """
        Gets the sessions stored in the memory of the agent.

        Args:
            input:
                An instance of `GetAgentMemoryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetAgentMemoryOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_AGENT_MEMORY,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_document_content(
        self, input: GetDocumentContentInput, plugins: list[Plugin] | None = None
    ) -> GetDocumentContentOutput:
        """
        Retrieves the content of an ingested document from a knowledge base.
        Returns a pre-signed URL for secure document access.

        Args:
            input:
                An instance of `GetDocumentContentInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDocumentContentOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_DOCUMENT_CONTENT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_execution_flow_snapshot(
        self, input: GetExecutionFlowSnapshotInput, plugins: list[Plugin] | None = None
    ) -> GetExecutionFlowSnapshotOutput:
        """
        Retrieves the flow definition snapshot used for a flow execution. The
        snapshot represents the flow metadata and definition as it existed at
        the time the execution was started. Note that even if the flow is edited
        after an execution starts, the snapshot connected to the execution
        remains unchanged.

        Note:
            Flow executions is in preview release for Amazon Bedrock and is subject
            to change.

        Args:
            input:
                An instance of `GetExecutionFlowSnapshotInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetExecutionFlowSnapshotOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_EXECUTION_FLOW_SNAPSHOT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_flow_execution(
        self, input: GetFlowExecutionInput, plugins: list[Plugin] | None = None
    ) -> GetFlowExecutionOutput:
        """
        Retrieves details about a specific flow execution, including its status,
        start and end times, and any errors that occurred during execution.

        Args:
            input:
                An instance of `GetFlowExecutionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetFlowExecutionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_FLOW_EXECUTION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_invocation_step(
        self, input: GetInvocationStepInput, plugins: list[Plugin] | None = None
    ) -> GetInvocationStepOutput:
        """
        Retrieves the details of a specific invocation step within an invocation
        in a session. For more information about sessions, see [Store and
        retrieve conversation history and context with Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        Args:
            input:
                An instance of `GetInvocationStepInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetInvocationStepOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_INVOCATION_STEP,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_session(
        self, input: GetSessionInput, plugins: list[Plugin] | None = None
    ) -> GetSessionOutput:
        """
        Retrieves details about a specific session. For more information about
        sessions, see [Store and retrieve conversation history and context with
        Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        Args:
            input:
                An instance of `GetSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetSessionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_SESSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def invoke_agent(
        self, input: InvokeAgentInput, plugins: list[Plugin] | None = None
    ) -> OutputEventStream[ResponseStream, InvokeAgentOutput]:
        """
        Note:

        Sends a prompt for the agent to process and respond to. Note the
        following fields for the request:

        - To continue the same conversation with an agent, use the same
          `sessionId` value in the request.

        - To activate trace enablement, turn `enableTrace` to `true`. Trace
          enablement helps you follow the agent's reasoning process that led it
          to the information it processed, the actions it took, and the final
          result it yielded. For more information, see [Trace
          enablement](https://docs.aws.amazon.com/bedrock/latest/userguide/agents-test.html#trace-events).

        - End a conversation by setting `endSession` to `true`.

        - In the `sessionState` object, you can include attributes for the
          session or prompt or, if you configured an action group to return
          control, results from invocation of the action group.

        The response contains both **chunk** and **trace** attributes.

        The final response is returned in the `bytes` field of the `chunk`
        object. The `InvokeAgent` returns one chunk for the entire interaction.

        - The `attribution` object contains citations for parts of the response.

        - If you set `enableTrace` to `true` in the request, you can trace the
          agent's steps and reasoning process that led it to the response.

        - If the action predicted was configured to return control, the response
          returns parameters for the action, elicited from the user, in the
          `returnControl` field.

        - Errors are also surfaced in the response.

        Args:
            input:
                An instance of `InvokeAgentInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An `OutputEventStream` for server-to-client streaming.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=INVOKE_AGENT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline.output_stream(
            call, ResponseStream, _ResponseStreamDeserializer().deserialize
        )

    async def invoke_flow(
        self, input: InvokeFlowInput, plugins: list[Plugin] | None = None
    ) -> OutputEventStream[FlowResponseStream, InvokeFlowOutput]:
        """
        Invokes an alias of a flow to run the inputs that you specify and return
        the output of each node as a stream. If there's an error, the error is
        returned. For more information, see [Test a flow in Amazon
        Bedrock](https://docs.aws.amazon.com/bedrock/latest/userguide/flows-test.html)
        in the [Amazon Bedrock User
        Guide](https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-service.html).

        Note:
            The CLI doesn't support streaming operations in Amazon Bedrock,
            including `InvokeFlow`.

        Args:
            input:
                An instance of `InvokeFlowInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An `OutputEventStream` for server-to-client streaming.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=INVOKE_FLOW,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline.output_stream(
            call, FlowResponseStream, _FlowResponseStreamDeserializer().deserialize
        )

    async def invoke_inline_agent(
        self, input: InvokeInlineAgentInput, plugins: list[Plugin] | None = None
    ) -> OutputEventStream[InlineAgentResponseStream, InvokeInlineAgentOutput]:
        """
        Invokes an inline Amazon Bedrock agent using the configurations you
        provide with the request.

        - Specify the following fields for security purposes.

          - (Optional) `customerEncryptionKeyArn` -- The Amazon Resource Name
            (ARN) of a KMS key to encrypt the creation of the agent.

          - (Optional) `idleSessionTTLinSeconds` -- Specify the number of
            seconds for which the agent should maintain session information.
            After this time expires, the subsequent `InvokeInlineAgent` request
            begins a new session.

        - To override the default prompt behavior for agent orchestration and to
          use advanced prompts, include a `promptOverrideConfiguration` object.
          For more information, see [Advanced
          prompts](https://docs.aws.amazon.com/bedrock/latest/userguide/advanced-prompts.html).

        - The agent instructions will not be honored if your agent has only one
          knowledge base, uses default prompts, has no action group, and user
          input is disabled.

        Note:

        Args:
            input:
                An instance of `InvokeInlineAgentInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An `OutputEventStream` for server-to-client streaming.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=INVOKE_INLINE_AGENT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline.output_stream(
            call,
            InlineAgentResponseStream,
            _InlineAgentResponseStreamDeserializer().deserialize,
        )

    async def list_flow_execution_events(
        self, input: ListFlowExecutionEventsInput, plugins: list[Plugin] | None = None
    ) -> ListFlowExecutionEventsOutput:
        """
        Lists events that occurred during a flow execution. Events provide
        detailed information about the execution progress, including node inputs
        and outputs, flow inputs and outputs, condition results, and failure
        events.

        Note:
            Flow executions is in preview release for Amazon Bedrock and is subject
            to change.

        Args:
            input:
                An instance of `ListFlowExecutionEventsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListFlowExecutionEventsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_FLOW_EXECUTION_EVENTS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_flow_executions(
        self, input: ListFlowExecutionsInput, plugins: list[Plugin] | None = None
    ) -> ListFlowExecutionsOutput:
        """
        Lists all executions of a flow. Results can be paginated and include
        summary information about each execution, such as status, start and end
        times, and the execution's Amazon Resource Name (ARN).

        Note:
            Flow executions is in preview release for Amazon Bedrock and is subject
            to change.

        Args:
            input:
                An instance of `ListFlowExecutionsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListFlowExecutionsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_FLOW_EXECUTIONS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_invocations(
        self, input: ListInvocationsInput, plugins: list[Plugin] | None = None
    ) -> ListInvocationsOutput:
        """
        Lists all invocations associated with a specific session. For more
        information about sessions, see [Store and retrieve conversation history
        and context with Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        Args:
            input:
                An instance of `ListInvocationsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListInvocationsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_INVOCATIONS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_invocation_steps(
        self, input: ListInvocationStepsInput, plugins: list[Plugin] | None = None
    ) -> ListInvocationStepsOutput:
        """
        Lists all invocation steps associated with a session and optionally, an
        invocation within the session. For more information about sessions, see
        [Store and retrieve conversation history and context with Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        Args:
            input:
                An instance of `ListInvocationStepsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListInvocationStepsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_INVOCATION_STEPS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_sessions(
        self, input: ListSessionsInput, plugins: list[Plugin] | None = None
    ) -> ListSessionsOutput:
        """
        Lists all sessions in your Amazon Web Services account. For more
        information about sessions, see [Store and retrieve conversation history
        and context with Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        Args:
            input:
                An instance of `ListSessionsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListSessionsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_SESSIONS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_tags_for_resource(
        self, input: ListTagsForResourceInput, plugins: list[Plugin] | None = None
    ) -> ListTagsForResourceOutput:
        """
        List all the tags for the resource you specify.

        Args:
            input:
                An instance of `ListTagsForResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListTagsForResourceOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_TAGS_FOR_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def optimize_prompt(
        self, input: OptimizePromptInput, plugins: list[Plugin] | None = None
    ) -> OutputEventStream[OptimizedPromptStream, OptimizePromptOutput]:
        """
        Optimizes a prompt for the task that you specify. For more information,
        see [Optimize a
        prompt](https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-management-optimize.html)
        in the [Amazon Bedrock User
        Guide](https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-service.html).

        Args:
            input:
                An instance of `OptimizePromptInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An `OutputEventStream` for server-to-client streaming.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=OPTIMIZE_PROMPT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline.output_stream(
            call,
            OptimizedPromptStream,
            _OptimizedPromptStreamDeserializer().deserialize,
        )

    async def put_invocation_step(
        self, input: PutInvocationStepInput, plugins: list[Plugin] | None = None
    ) -> PutInvocationStepOutput:
        """
        Add an invocation step to an invocation in a session. An invocation step
        stores fine-grained state checkpoints, including text and images, for
        each interaction. For more information about sessions, see [Store and
        retrieve conversation history and context with Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        Related APIs:

        - [GetInvocationStep](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_GetInvocationStep.html)

        - [ListInvocationSteps](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_ListInvocationSteps.html)

        - [ListInvocations](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_ListInvocations.html)

        - [ListSessions](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_ListInvocations.html)

        Args:
            input:
                An instance of `PutInvocationStepInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutInvocationStepOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=PUT_INVOCATION_STEP,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def rerank(
        self, input: RerankInput, plugins: list[Plugin] | None = None
    ) -> RerankOutput:
        """
        Reranks the relevance of sources based on queries. For more information,
        see [Improve the relevance of query responses with a reranker
        model](https://docs.aws.amazon.com/bedrock/latest/userguide/rerank.html).

        Args:
            input:
                An instance of `RerankInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RerankOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=RERANK,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def retrieve(
        self, input: RetrieveInput, plugins: list[Plugin] | None = None
    ) -> RetrieveOutput:
        """
        Queries a knowledge base and retrieves information from it.

        Args:
            input:
                An instance of `RetrieveInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RetrieveOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=RETRIEVE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def retrieve_and_generate(
        self,
        input: RetrieveAndGenerateOperationInput,
        plugins: list[Plugin] | None = None,
    ) -> RetrieveAndGenerateOperationOutput:
        """
        Queries a knowledge base and generates responses based on the retrieved
        results and using the specified foundation model or [inference
        profile](https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference.html).
        The response only cites sources that are relevant to the query.

        Note:
            This API cannot be used with managed knowledge bases. Use
            [AgenticRetrieveStream](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_AgenticRetrieveStream.html)
            or
            [Retrieve](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Retrieve.html)
            with managed knowledge bases.

        Args:
            input:
                An instance of `RetrieveAndGenerateOperationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RetrieveAndGenerateOperationOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=RETRIEVE_AND_GENERATE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def retrieve_and_generate_stream(
        self, input: RetrieveAndGenerateStreamInput, plugins: list[Plugin] | None = None
    ) -> OutputEventStream[
        RetrieveAndGenerateStreamResponseOutput, RetrieveAndGenerateStreamOutput
    ]:
        """
        Queries a knowledge base and generates responses based on the retrieved
        results, with output in streaming format.

        Note:
            This API cannot be used with managed knowledge bases. Use
            [AgenticRetrieveStream](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_AgenticRetrieveStream.html)
            or
            [Retrieve](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Retrieve.html)
            with managed knowledge bases.
        Note:
            The CLI doesn't support streaming operations in Amazon Bedrock,
            including `InvokeModelWithResponseStream`.

        This operation requires permission for the
        ` bedrock:RetrieveAndGenerate` action.

        Args:
            input:
                An instance of `RetrieveAndGenerateStreamInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An `OutputEventStream` for server-to-client streaming.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=RETRIEVE_AND_GENERATE_STREAM,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline.output_stream(
            call,
            RetrieveAndGenerateStreamResponseOutput,
            _RetrieveAndGenerateStreamResponseOutputDeserializer().deserialize,
        )

    async def start_flow_execution(
        self, input: StartFlowExecutionInput, plugins: list[Plugin] | None = None
    ) -> StartFlowExecutionOutput:
        """
        Starts an execution of an Amazon Bedrock flow. Unlike flows that run
        until completion or time out after five minutes, flow executions let you
        run flows asynchronously for longer durations. Flow executions also
        yield control so that your application can perform other tasks.

        This operation returns an Amazon Resource Name (ARN) that you can use to
        track and manage your flow execution.

        Note:
            Flow executions is in preview release for Amazon Bedrock and is subject
            to change.

        Args:
            input:
                An instance of `StartFlowExecutionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `StartFlowExecutionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=START_FLOW_EXECUTION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def stop_flow_execution(
        self, input: StopFlowExecutionInput, plugins: list[Plugin] | None = None
    ) -> StopFlowExecutionOutput:
        """
        Stops an Amazon Bedrock flow's execution. This operation prevents
        further processing of the flow and changes the execution status to
        `Aborted`.

        Args:
            input:
                An instance of `StopFlowExecutionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `StopFlowExecutionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=STOP_FLOW_EXECUTION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def tag_resource(
        self, input: TagResourceInput, plugins: list[Plugin] | None = None
    ) -> TagResourceOutput:
        """
        Associate tags with a resource. For more information, see [Tagging
        resources](https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-service.html)
        in the Amazon Bedrock User Guide.

        Args:
            input:
                An instance of `TagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `TagResourceOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=TAG_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def untag_resource(
        self, input: UntagResourceInput, plugins: list[Plugin] | None = None
    ) -> UntagResourceOutput:
        """
        Remove tags from a resource.

        Args:
            input:
                An instance of `UntagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UntagResourceOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UNTAG_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def update_session(
        self, input: UpdateSessionInput, plugins: list[Plugin] | None = None
    ) -> UpdateSessionOutput:
        """
        Updates the metadata or encryption settings of a session. For more
        information about sessions, see [Store and retrieve conversation history
        and context with Amazon Bedrock
        sessions](https://docs.aws.amazon.com/bedrock/latest/userguide/sessions.html).

        Args:
            input:
                An instance of `UpdateSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UpdateSessionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UPDATE_SESSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)
