# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging
from typing import Any, TYPE_CHECKING
import warnings

from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.eventstream import DuplexEventStream
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.plugins import user_agent_plugin

from .config import Config, Plugin
from .models import (
    ACTIVATE_SUBSCRIPTION,
    ActivateSubscriptionInput,
    ActivateSubscriptionOutput,
    CREATE_DOMAIN,
    CREATE_SUBSCRIPTION,
    CreateDomainInput,
    CreateDomainOutput,
    CreateSubscriptionInput,
    CreateSubscriptionOutput,
    DEACTIVATE_SUBSCRIPTION,
    DELETE_DOMAIN,
    DeactivateSubscriptionInput,
    DeactivateSubscriptionOutput,
    DeleteDomainInput,
    DeleteDomainOutput,
    GET_DOMAIN,
    GET_MEDICAL_SCRIBE_LISTENING_SESSION,
    GET_PATIENT_INSIGHTS_JOB,
    GET_SUBSCRIPTION,
    GetDomainInput,
    GetDomainOutput,
    GetMedicalScribeListeningSessionInput,
    GetMedicalScribeListeningSessionOutput,
    GetPatientInsightsJobInput,
    GetPatientInsightsJobOutput,
    GetSubscriptionInput,
    GetSubscriptionOutput,
    LIST_DOMAINS,
    LIST_SUBSCRIPTIONS,
    LIST_TAGS_FOR_RESOURCE,
    ListDomainsInput,
    ListDomainsOutput,
    ListSubscriptionsInput,
    ListSubscriptionsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    MedicalScribeInputStream,
    MedicalScribeOutputStream,
    START_MEDICAL_SCRIBE_LISTENING_SESSION,
    START_PATIENT_INSIGHTS_JOB,
    StartMedicalScribeListeningSessionInput,
    StartMedicalScribeListeningSessionOutput,
    StartPatientInsightsJobInput,
    StartPatientInsightsJobOutput,
    TAG_RESOURCE,
    TagResourceInput,
    TagResourceOutput,
    UNTAG_RESOURCE,
    UntagResourceInput,
    UntagResourceOutput,
    _MedicalScribeOutputStreamDeserializer,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncConnectHealthClient:
    """
    Amazon Connect Health is an AI-powered healthcare service built on
    Amazon Connect. It provides pre-built agents that automate patient
    engagement workflows and support clinical documentation at the point of
    care.

    You can use the Amazon Connect Health API to programmatically manage
    domains, configure patient engagement agents, run patient insights jobs,
    and stream ambient documentation sessions. This API reference describes
    the available API operations and data types for Amazon Connect Health.

    We recommend that you use the AWS SDKs to make programmatic API calls to
    Amazon Connect Health.
    """

    def __init__(
        self, config: Config | None = None, plugins: list[Plugin] | None = None
    ):
        """
        Constructor for `AsyncConnectHealthClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables that modify the configuration dynamically. These
                can be used to set defaults, for example.
        """
        self._config = config or Config()

        client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]
        if plugins:
            client_plugins.extend(plugins)

        for plugin in client_plugins:
            plugin(self._config)

        self._retry_strategy_resolver = RetryStrategyResolver()

    async def activate_subscription(
        self, input: ActivateSubscriptionInput, plugins: list[Plugin] | None = None
    ) -> ActivateSubscriptionOutput:
        """
        Activates a Subscription to enable billing for a user.

        Args:
            input:
                An instance of `ActivateSubscriptionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ActivateSubscriptionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=ACTIVATE_SUBSCRIPTION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def create_domain(
        self, input: CreateDomainInput, plugins: list[Plugin] | None = None
    ) -> CreateDomainOutput:
        """
        Creates a new Domain for managing HealthAgent resources.

        Args:
            input:
                An instance of `CreateDomainInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateDomainOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=CREATE_DOMAIN,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def create_subscription(
        self, input: CreateSubscriptionInput, plugins: list[Plugin] | None = None
    ) -> CreateSubscriptionOutput:
        """
        Creates a new Subscription within a Domain for billing and user
        management.

        Args:
            input:
                An instance of `CreateSubscriptionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateSubscriptionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=CREATE_SUBSCRIPTION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def deactivate_subscription(
        self, input: DeactivateSubscriptionInput, plugins: list[Plugin] | None = None
    ) -> DeactivateSubscriptionOutput:
        """
        Deactivates a Subscription to stop billing for a user.

        Args:
            input:
                An instance of `DeactivateSubscriptionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeactivateSubscriptionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DEACTIVATE_SUBSCRIPTION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def delete_domain(
        self, input: DeleteDomainInput, plugins: list[Plugin] | None = None
    ) -> DeleteDomainOutput:
        """
        Deletes a Domain and all associated resources.

        Args:
            input:
                An instance of `DeleteDomainInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteDomainOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DELETE_DOMAIN,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_domain(
        self, input: GetDomainInput, plugins: list[Plugin] | None = None
    ) -> GetDomainOutput:
        """
        Retrieves information about a Domain.

        Args:
            input:
                An instance of `GetDomainInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDomainOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_DOMAIN,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_medical_scribe_listening_session(
        self,
        input: GetMedicalScribeListeningSessionInput,
        plugins: list[Plugin] | None = None,
    ) -> GetMedicalScribeListeningSessionOutput:
        """
        Retrieves details about an existing Medical Scribe listening session

        Args:
            input:
                An instance of `GetMedicalScribeListeningSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetMedicalScribeListeningSessionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_MEDICAL_SCRIBE_LISTENING_SESSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_patient_insights_job(
        self, input: GetPatientInsightsJobInput, plugins: list[Plugin] | None = None
    ) -> GetPatientInsightsJobOutput:
        """
        Get details of a started patient insights job.

        Args:
            input:
                An instance of `GetPatientInsightsJobInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetPatientInsightsJobOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_PATIENT_INSIGHTS_JOB,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_subscription(
        self, input: GetSubscriptionInput, plugins: list[Plugin] | None = None
    ) -> GetSubscriptionOutput:
        """
        Retrieves information about a Subscription.

        Args:
            input:
                An instance of `GetSubscriptionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetSubscriptionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_SUBSCRIPTION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_domains(
        self, input: ListDomainsInput, plugins: list[Plugin] | None = None
    ) -> ListDomainsOutput:
        """
        Lists Domains for a given account.

        Args:
            input:
                An instance of `ListDomainsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListDomainsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_DOMAINS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_subscriptions(
        self, input: ListSubscriptionsInput, plugins: list[Plugin] | None = None
    ) -> ListSubscriptionsOutput:
        """
        Lists all Subscriptions within a Domain.

        Args:
            input:
                An instance of `ListSubscriptionsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListSubscriptionsOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_SUBSCRIPTIONS,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def list_tags_for_resource(
        self, input: ListTagsForResourceInput, plugins: list[Plugin] | None = None
    ) -> ListTagsForResourceOutput:
        """
        Lists the tags associated with the specified resource

        Args:
            input:
                An instance of `ListTagsForResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListTagsForResourceOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=LIST_TAGS_FOR_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def start_medical_scribe_listening_session(
        self,
        input: StartMedicalScribeListeningSessionInput,
        plugins: list[Plugin] | None = None,
    ) -> DuplexEventStream[
        MedicalScribeInputStream,
        MedicalScribeOutputStream,
        StartMedicalScribeListeningSessionOutput,
    ]:
        """
        Starts a new Medical Scribe listening session for real-time audio
        transcription

        Args:
            input:
                An instance of `StartMedicalScribeListeningSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            A `DuplexEventStream` for bidirectional streaming.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=START_MEDICAL_SCRIBE_LISTENING_SESSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline.duplex_stream(
            call,
            MedicalScribeInputStream,
            MedicalScribeOutputStream,
            _MedicalScribeOutputStreamDeserializer().deserialize,
        )

    async def start_patient_insights_job(
        self, input: StartPatientInsightsJobInput, plugins: list[Plugin] | None = None
    ) -> StartPatientInsightsJobOutput:
        """
        Starts a new patient insights job.

        Args:
            input:
                An instance of `StartPatientInsightsJobInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `StartPatientInsightsJobOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=START_PATIENT_INSIGHTS_JOB,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def tag_resource(
        self, input: TagResourceInput, plugins: list[Plugin] | None = None
    ) -> TagResourceOutput:
        """
        Associates the specified tags with the specified resource

        Args:
            input:
                An instance of `TagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `TagResourceOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=TAG_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def untag_resource(
        self, input: UntagResourceInput, plugins: list[Plugin] | None = None
    ) -> UntagResourceOutput:
        """
        Removes the specified tags from the specified resource

        Args:
            input:
                An instance of `UntagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UntagResourceOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=UNTAG_RESOURCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)


if TYPE_CHECKING:
    # Deprecated alias for backwards compatibility, to be removed.
    ConnectHealthClient = AsyncConnectHealthClient


def __getattr__(name: str) -> Any:
    if name == "ConnectHealthClient":
        warnings.warn(
            "ConnectHealthClient is deprecated, use AsyncConnectHealthClient instead. "
            "This alias will be removed in a future version.",
            DeprecationWarning,
            stacklevel=2,
        )
        return AsyncConnectHealthClient
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
