# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
from typing import Any, Callable, TypeAlias, Union

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, ClientTransport, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.aio.interfaces.retries import RetryStrategy
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces import URI
from smithy_core.retries import RetryStrategyOptions
from smithy_core.shapes import ShapeID
from smithy_http.aio.crt import AWSCRTHTTPClient
from smithy_http.interfaces import HTTPRequestConfiguration

from ._private.schemas import AWS_GIR_API_SERVICE as _SCHEMA_AWS_GIR_API_SERVICE
from .auth import HTTPAuthSchemeResolver
from .models import (
    AddLayerVersionPermissionInput,
    AddLayerVersionPermissionOutput,
    AddPermissionInput,
    AddPermissionOutput,
    CheckpointDurableExecutionInput,
    CheckpointDurableExecutionOutput,
    CreateAliasInput,
    CreateAliasOutput,
    CreateCapacityProviderInput,
    CreateCapacityProviderOutput,
    CreateCodeSigningConfigInput,
    CreateCodeSigningConfigOutput,
    CreateEventSourceMappingInput,
    CreateEventSourceMappingOutput,
    CreateFunctionInput,
    CreateFunctionOutput,
    CreateFunctionUrlConfigInput,
    CreateFunctionUrlConfigOutput,
    DeleteAliasInput,
    DeleteAliasOutput,
    DeleteCapacityProviderInput,
    DeleteCapacityProviderOutput,
    DeleteCodeSigningConfigInput,
    DeleteCodeSigningConfigOutput,
    DeleteEventSourceMappingInput,
    DeleteEventSourceMappingOutput,
    DeleteFunctionCodeSigningConfigInput,
    DeleteFunctionCodeSigningConfigOutput,
    DeleteFunctionConcurrencyInput,
    DeleteFunctionConcurrencyOutput,
    DeleteFunctionEventInvokeConfigInput,
    DeleteFunctionEventInvokeConfigOutput,
    DeleteFunctionInput,
    DeleteFunctionOutput,
    DeleteFunctionUrlConfigInput,
    DeleteFunctionUrlConfigOutput,
    DeleteLayerVersionInput,
    DeleteLayerVersionOutput,
    DeleteProvisionedConcurrencyConfigInput,
    DeleteProvisionedConcurrencyConfigOutput,
    GetAccountSettingsInput,
    GetAccountSettingsOutput,
    GetAliasInput,
    GetAliasOutput,
    GetCapacityProviderInput,
    GetCapacityProviderOutput,
    GetCodeSigningConfigInput,
    GetCodeSigningConfigOutput,
    GetDurableExecutionHistoryInput,
    GetDurableExecutionHistoryOutput,
    GetDurableExecutionInput,
    GetDurableExecutionOutput,
    GetDurableExecutionStateInput,
    GetDurableExecutionStateOutput,
    GetEventSourceMappingInput,
    GetEventSourceMappingOutput,
    GetFunctionCodeSigningConfigInput,
    GetFunctionCodeSigningConfigOutput,
    GetFunctionConcurrencyInput,
    GetFunctionConcurrencyOutput,
    GetFunctionConfigurationInput,
    GetFunctionConfigurationOutput,
    GetFunctionEventInvokeConfigInput,
    GetFunctionEventInvokeConfigOutput,
    GetFunctionInput,
    GetFunctionOutput,
    GetFunctionRecursionConfigInput,
    GetFunctionRecursionConfigOutput,
    GetFunctionScalingConfigInput,
    GetFunctionScalingConfigOutput,
    GetFunctionUrlConfigInput,
    GetFunctionUrlConfigOutput,
    GetLayerVersionByArnInput,
    GetLayerVersionByArnOutput,
    GetLayerVersionInput,
    GetLayerVersionOutput,
    GetLayerVersionPolicyInput,
    GetLayerVersionPolicyOutput,
    GetPolicyInput,
    GetPolicyOutput,
    GetProvisionedConcurrencyConfigInput,
    GetProvisionedConcurrencyConfigOutput,
    GetRuntimeManagementConfigInput,
    GetRuntimeManagementConfigOutput,
    InvokeAsyncInput,
    InvokeAsyncOutput,
    InvokeInput,
    InvokeOutput,
    InvokeWithResponseStreamInput,
    InvokeWithResponseStreamOutput,
    ListAliasesInput,
    ListAliasesOutput,
    ListCapacityProvidersInput,
    ListCapacityProvidersOutput,
    ListCodeSigningConfigsInput,
    ListCodeSigningConfigsOutput,
    ListDurableExecutionsByFunctionInput,
    ListDurableExecutionsByFunctionOutput,
    ListEventSourceMappingsInput,
    ListEventSourceMappingsOutput,
    ListFunctionEventInvokeConfigsInput,
    ListFunctionEventInvokeConfigsOutput,
    ListFunctionUrlConfigsInput,
    ListFunctionUrlConfigsOutput,
    ListFunctionVersionsByCapacityProviderInput,
    ListFunctionVersionsByCapacityProviderOutput,
    ListFunctionsByCodeSigningConfigInput,
    ListFunctionsByCodeSigningConfigOutput,
    ListFunctionsInput,
    ListFunctionsOutput,
    ListLayerVersionsInput,
    ListLayerVersionsOutput,
    ListLayersInput,
    ListLayersOutput,
    ListProvisionedConcurrencyConfigsInput,
    ListProvisionedConcurrencyConfigsOutput,
    ListTagsInput,
    ListTagsOutput,
    ListVersionsByFunctionInput,
    ListVersionsByFunctionOutput,
    PublishLayerVersionInput,
    PublishLayerVersionOutput,
    PublishVersionInput,
    PublishVersionOutput,
    PutFunctionCodeSigningConfigInput,
    PutFunctionCodeSigningConfigOutput,
    PutFunctionConcurrencyInput,
    PutFunctionConcurrencyOutput,
    PutFunctionEventInvokeConfigInput,
    PutFunctionEventInvokeConfigOutput,
    PutFunctionRecursionConfigInput,
    PutFunctionRecursionConfigOutput,
    PutFunctionScalingConfigInput,
    PutFunctionScalingConfigOutput,
    PutProvisionedConcurrencyConfigInput,
    PutProvisionedConcurrencyConfigOutput,
    PutRuntimeManagementConfigInput,
    PutRuntimeManagementConfigOutput,
    RemoveLayerVersionPermissionInput,
    RemoveLayerVersionPermissionOutput,
    RemovePermissionInput,
    RemovePermissionOutput,
    SendDurableExecutionCallbackFailureInput,
    SendDurableExecutionCallbackFailureOutput,
    SendDurableExecutionCallbackHeartbeatInput,
    SendDurableExecutionCallbackHeartbeatOutput,
    SendDurableExecutionCallbackSuccessInput,
    SendDurableExecutionCallbackSuccessOutput,
    StopDurableExecutionInput,
    StopDurableExecutionOutput,
    TagResourceInput,
    TagResourceOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateAliasInput,
    UpdateAliasOutput,
    UpdateCapacityProviderInput,
    UpdateCapacityProviderOutput,
    UpdateCodeSigningConfigInput,
    UpdateCodeSigningConfigOutput,
    UpdateEventSourceMappingInput,
    UpdateEventSourceMappingOutput,
    UpdateFunctionCodeInput,
    UpdateFunctionCodeOutput,
    UpdateFunctionConfigurationInput,
    UpdateFunctionConfigurationOutput,
    UpdateFunctionEventInvokeConfigInput,
    UpdateFunctionEventInvokeConfigOutput,
    UpdateFunctionUrlConfigInput,
    UpdateFunctionUrlConfigOutput,
)


_ServiceInterceptor = Union[
    Interceptor[
        AddLayerVersionPermissionInput, AddLayerVersionPermissionOutput, Any, Any
    ],
    Interceptor[AddPermissionInput, AddPermissionOutput, Any, Any],
    Interceptor[
        CheckpointDurableExecutionInput, CheckpointDurableExecutionOutput, Any, Any
    ],
    Interceptor[CreateAliasInput, CreateAliasOutput, Any, Any],
    Interceptor[CreateCapacityProviderInput, CreateCapacityProviderOutput, Any, Any],
    Interceptor[CreateCodeSigningConfigInput, CreateCodeSigningConfigOutput, Any, Any],
    Interceptor[
        CreateEventSourceMappingInput, CreateEventSourceMappingOutput, Any, Any
    ],
    Interceptor[CreateFunctionInput, CreateFunctionOutput, Any, Any],
    Interceptor[CreateFunctionUrlConfigInput, CreateFunctionUrlConfigOutput, Any, Any],
    Interceptor[DeleteAliasInput, DeleteAliasOutput, Any, Any],
    Interceptor[DeleteCapacityProviderInput, DeleteCapacityProviderOutput, Any, Any],
    Interceptor[DeleteCodeSigningConfigInput, DeleteCodeSigningConfigOutput, Any, Any],
    Interceptor[
        DeleteEventSourceMappingInput, DeleteEventSourceMappingOutput, Any, Any
    ],
    Interceptor[DeleteFunctionInput, DeleteFunctionOutput, Any, Any],
    Interceptor[
        DeleteFunctionCodeSigningConfigInput,
        DeleteFunctionCodeSigningConfigOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteFunctionConcurrencyInput, DeleteFunctionConcurrencyOutput, Any, Any
    ],
    Interceptor[
        DeleteFunctionEventInvokeConfigInput,
        DeleteFunctionEventInvokeConfigOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteFunctionUrlConfigInput, DeleteFunctionUrlConfigOutput, Any, Any],
    Interceptor[DeleteLayerVersionInput, DeleteLayerVersionOutput, Any, Any],
    Interceptor[
        DeleteProvisionedConcurrencyConfigInput,
        DeleteProvisionedConcurrencyConfigOutput,
        Any,
        Any,
    ],
    Interceptor[GetAccountSettingsInput, GetAccountSettingsOutput, Any, Any],
    Interceptor[GetAliasInput, GetAliasOutput, Any, Any],
    Interceptor[GetCapacityProviderInput, GetCapacityProviderOutput, Any, Any],
    Interceptor[GetCodeSigningConfigInput, GetCodeSigningConfigOutput, Any, Any],
    Interceptor[GetDurableExecutionInput, GetDurableExecutionOutput, Any, Any],
    Interceptor[
        GetDurableExecutionHistoryInput, GetDurableExecutionHistoryOutput, Any, Any
    ],
    Interceptor[
        GetDurableExecutionStateInput, GetDurableExecutionStateOutput, Any, Any
    ],
    Interceptor[GetEventSourceMappingInput, GetEventSourceMappingOutput, Any, Any],
    Interceptor[GetFunctionInput, GetFunctionOutput, Any, Any],
    Interceptor[
        GetFunctionCodeSigningConfigInput, GetFunctionCodeSigningConfigOutput, Any, Any
    ],
    Interceptor[GetFunctionConcurrencyInput, GetFunctionConcurrencyOutput, Any, Any],
    Interceptor[
        GetFunctionConfigurationInput, GetFunctionConfigurationOutput, Any, Any
    ],
    Interceptor[
        GetFunctionEventInvokeConfigInput, GetFunctionEventInvokeConfigOutput, Any, Any
    ],
    Interceptor[
        GetFunctionRecursionConfigInput, GetFunctionRecursionConfigOutput, Any, Any
    ],
    Interceptor[
        GetFunctionScalingConfigInput, GetFunctionScalingConfigOutput, Any, Any
    ],
    Interceptor[GetFunctionUrlConfigInput, GetFunctionUrlConfigOutput, Any, Any],
    Interceptor[GetLayerVersionInput, GetLayerVersionOutput, Any, Any],
    Interceptor[GetLayerVersionByArnInput, GetLayerVersionByArnOutput, Any, Any],
    Interceptor[GetLayerVersionPolicyInput, GetLayerVersionPolicyOutput, Any, Any],
    Interceptor[GetPolicyInput, GetPolicyOutput, Any, Any],
    Interceptor[
        GetProvisionedConcurrencyConfigInput,
        GetProvisionedConcurrencyConfigOutput,
        Any,
        Any,
    ],
    Interceptor[
        GetRuntimeManagementConfigInput, GetRuntimeManagementConfigOutput, Any, Any
    ],
    Interceptor[InvokeInput, InvokeOutput, Any, Any],
    Interceptor[InvokeAsyncInput, InvokeAsyncOutput, Any, Any],
    Interceptor[
        InvokeWithResponseStreamInput, InvokeWithResponseStreamOutput, Any, Any
    ],
    Interceptor[ListAliasesInput, ListAliasesOutput, Any, Any],
    Interceptor[ListCapacityProvidersInput, ListCapacityProvidersOutput, Any, Any],
    Interceptor[ListCodeSigningConfigsInput, ListCodeSigningConfigsOutput, Any, Any],
    Interceptor[
        ListDurableExecutionsByFunctionInput,
        ListDurableExecutionsByFunctionOutput,
        Any,
        Any,
    ],
    Interceptor[ListEventSourceMappingsInput, ListEventSourceMappingsOutput, Any, Any],
    Interceptor[
        ListFunctionEventInvokeConfigsInput,
        ListFunctionEventInvokeConfigsOutput,
        Any,
        Any,
    ],
    Interceptor[ListFunctionsInput, ListFunctionsOutput, Any, Any],
    Interceptor[
        ListFunctionsByCodeSigningConfigInput,
        ListFunctionsByCodeSigningConfigOutput,
        Any,
        Any,
    ],
    Interceptor[ListFunctionUrlConfigsInput, ListFunctionUrlConfigsOutput, Any, Any],
    Interceptor[
        ListFunctionVersionsByCapacityProviderInput,
        ListFunctionVersionsByCapacityProviderOutput,
        Any,
        Any,
    ],
    Interceptor[ListLayersInput, ListLayersOutput, Any, Any],
    Interceptor[ListLayerVersionsInput, ListLayerVersionsOutput, Any, Any],
    Interceptor[
        ListProvisionedConcurrencyConfigsInput,
        ListProvisionedConcurrencyConfigsOutput,
        Any,
        Any,
    ],
    Interceptor[ListTagsInput, ListTagsOutput, Any, Any],
    Interceptor[ListVersionsByFunctionInput, ListVersionsByFunctionOutput, Any, Any],
    Interceptor[PublishLayerVersionInput, PublishLayerVersionOutput, Any, Any],
    Interceptor[PublishVersionInput, PublishVersionOutput, Any, Any],
    Interceptor[
        PutFunctionCodeSigningConfigInput, PutFunctionCodeSigningConfigOutput, Any, Any
    ],
    Interceptor[PutFunctionConcurrencyInput, PutFunctionConcurrencyOutput, Any, Any],
    Interceptor[
        PutFunctionEventInvokeConfigInput, PutFunctionEventInvokeConfigOutput, Any, Any
    ],
    Interceptor[
        PutFunctionRecursionConfigInput, PutFunctionRecursionConfigOutput, Any, Any
    ],
    Interceptor[
        PutFunctionScalingConfigInput, PutFunctionScalingConfigOutput, Any, Any
    ],
    Interceptor[
        PutProvisionedConcurrencyConfigInput,
        PutProvisionedConcurrencyConfigOutput,
        Any,
        Any,
    ],
    Interceptor[
        PutRuntimeManagementConfigInput, PutRuntimeManagementConfigOutput, Any, Any
    ],
    Interceptor[
        RemoveLayerVersionPermissionInput, RemoveLayerVersionPermissionOutput, Any, Any
    ],
    Interceptor[RemovePermissionInput, RemovePermissionOutput, Any, Any],
    Interceptor[
        SendDurableExecutionCallbackFailureInput,
        SendDurableExecutionCallbackFailureOutput,
        Any,
        Any,
    ],
    Interceptor[
        SendDurableExecutionCallbackHeartbeatInput,
        SendDurableExecutionCallbackHeartbeatOutput,
        Any,
        Any,
    ],
    Interceptor[
        SendDurableExecutionCallbackSuccessInput,
        SendDurableExecutionCallbackSuccessOutput,
        Any,
        Any,
    ],
    Interceptor[StopDurableExecutionInput, StopDurableExecutionOutput, Any, Any],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[UpdateAliasInput, UpdateAliasOutput, Any, Any],
    Interceptor[UpdateCapacityProviderInput, UpdateCapacityProviderOutput, Any, Any],
    Interceptor[UpdateCodeSigningConfigInput, UpdateCodeSigningConfigOutput, Any, Any],
    Interceptor[
        UpdateEventSourceMappingInput, UpdateEventSourceMappingOutput, Any, Any
    ],
    Interceptor[UpdateFunctionCodeInput, UpdateFunctionCodeOutput, Any, Any],
    Interceptor[
        UpdateFunctionConfigurationInput, UpdateFunctionConfigurationOutput, Any, Any
    ],
    Interceptor[
        UpdateFunctionEventInvokeConfigInput,
        UpdateFunctionEventInvokeConfigOutput,
        Any,
        Any,
    ],
    Interceptor[UpdateFunctionUrlConfigInput, UpdateFunctionUrlConfigOutput, Any, Any],
]


@dataclass(init=False)
class Config:
    """Configuration for Lambda."""

    auth_scheme_resolver: HTTPAuthSchemeResolver
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]]
    """A map of auth scheme ids to auth schemes."""

    aws_access_key_id: str | None
    """The identifier for a secret access key."""

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    )
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    aws_secret_access_key: str | None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None
    """An access key ID that identifies temporary security credentials."""

    endpoint_resolver: EndpointResolver
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    endpoint_uri: str | URI | None
    """A static URI to route requests to."""

    http_request_config: HTTPRequestConfiguration | None
    """Configuration for individual HTTP requests."""

    interceptors: list[_ServiceInterceptor]
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    protocol: ClientProtocol[Any, Any] | None
    """The protocol to serialize and deserialize requests with."""

    region: str | None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    retry_strategy: RetryStrategy | RetryStrategyOptions | None
    """
    The retry strategy or options for configuring retry behavior. Can be
    either a configured RetryStrategy or RetryStrategyOptions to create one.
    """

    sdk_ua_app_id: str | None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    transport: ClientTransport[Any, Any] | None
    """The transport to use to send requests (e.g. an HTTP client)."""

    user_agent_extra: str | None
    """Additional suffix to be added to the User-Agent header."""

    def __init__(
        self,
        *,
        auth_scheme_resolver: HTTPAuthSchemeResolver | None = None,
        auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None,
        aws_access_key_id: str | None = None,
        aws_credentials_identity_resolver: IdentityResolver[
            AWSCredentialsIdentity, AWSIdentityProperties
        ]
        | None = None,
        aws_secret_access_key: str | None = None,
        aws_session_token: str | None = None,
        endpoint_resolver: EndpointResolver | None = None,
        endpoint_uri: str | URI | None = None,
        http_request_config: HTTPRequestConfiguration | None = None,
        interceptors: list[_ServiceInterceptor] | None = None,
        protocol: ClientProtocol[Any, Any] | None = None,
        region: str | None = None,
        retry_strategy: RetryStrategy | RetryStrategyOptions | None = None,
        sdk_ua_app_id: str | None = None,
        transport: ClientTransport[Any, Any] | None = None,
        user_agent_extra: str | None = None,
    ):
        self.auth_scheme_resolver = auth_scheme_resolver or HTTPAuthSchemeResolver()
        self.auth_schemes = auth_schemes or {
            ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="lambda")
        }
        self.aws_access_key_id = aws_access_key_id
        self.aws_credentials_identity_resolver = aws_credentials_identity_resolver
        self.aws_secret_access_key = aws_secret_access_key
        self.aws_session_token = aws_session_token
        self.endpoint_resolver = endpoint_resolver or StandardRegionalEndpointsResolver(
            endpoint_prefix="lambda"
        )
        self.endpoint_uri = endpoint_uri
        self.http_request_config = http_request_config
        self.interceptors = interceptors or []
        self.protocol = protocol or RestJsonClientProtocol(_SCHEMA_AWS_GIR_API_SERVICE)
        self.region = region
        self.retry_strategy = retry_strategy
        self.sdk_ua_app_id = sdk_ua_app_id
        self.transport = transport or AWSCRTHTTPClient()
        self.user_agent_extra = user_agent_extra

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Sets the implementation of an auth scheme.

        Using this method ensures the correct key is used.

        Args:
            scheme:
                The auth scheme to add.
        """
        self.auth_schemes[scheme.scheme_id] = scheme


Plugin: TypeAlias = Callable[[Config], None]
"""A callable that allows customizing the config object on each request."""
