# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
from typing import Any, Callable, TypeAlias, Union

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, ClientTransport, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.aio.interfaces.retries import RetryStrategy
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces import URI
from smithy_core.retries import RetryStrategyOptions
from smithy_core.shapes import ShapeID
from smithy_http.aio.aiohttp import AIOHTTPClient
from smithy_http.interfaces import HTTPRequestConfiguration

from ._private.schemas import (
    AMAZON_BEDROCK_AGENT_CORE_CONTROL as _SCHEMA_AMAZON_BEDROCK_AGENT_CORE_CONTROL,
)
from .auth import HTTPAuthSchemeResolver
from .models import (
    AddDatasetExamplesInput,
    AddDatasetExamplesOutput,
    CreateAgentRuntimeEndpointInput,
    CreateAgentRuntimeEndpointOutput,
    CreateAgentRuntimeInput,
    CreateAgentRuntimeOutput,
    CreateApiKeyCredentialProviderInput,
    CreateApiKeyCredentialProviderOutput,
    CreateBrowserInput,
    CreateBrowserOutput,
    CreateBrowserProfileInput,
    CreateBrowserProfileOutput,
    CreateCodeInterpreterInput,
    CreateCodeInterpreterOutput,
    CreateConfigurationBundleInput,
    CreateConfigurationBundleOutput,
    CreateDatasetInput,
    CreateDatasetOutput,
    CreateDatasetVersionInput,
    CreateDatasetVersionOutput,
    CreateEvaluatorInput,
    CreateEvaluatorOutput,
    CreateGatewayInput,
    CreateGatewayOutput,
    CreateGatewayRuleInput,
    CreateGatewayRuleOutput,
    CreateGatewayTargetInput,
    CreateGatewayTargetOutput,
    CreateHarnessEndpointInput,
    CreateHarnessEndpointOutput,
    CreateHarnessInput,
    CreateHarnessOutput,
    CreateMemoryInput,
    CreateMemoryOutput,
    CreateOauth2CredentialProviderInput,
    CreateOauth2CredentialProviderOutput,
    CreateOnlineEvaluationConfigInput,
    CreateOnlineEvaluationConfigOutput,
    CreatePaymentConnectorInput,
    CreatePaymentConnectorOutput,
    CreatePaymentCredentialProviderInput,
    CreatePaymentCredentialProviderOutput,
    CreatePaymentManagerInput,
    CreatePaymentManagerOutput,
    CreatePolicyEngineInput,
    CreatePolicyEngineOutput,
    CreatePolicyInput,
    CreatePolicyOutput,
    CreateRegistryInput,
    CreateRegistryOutput,
    CreateRegistryRecordInput,
    CreateRegistryRecordOutput,
    CreateWorkloadIdentityInput,
    CreateWorkloadIdentityOutput,
    DeleteAgentRuntimeEndpointInput,
    DeleteAgentRuntimeEndpointOutput,
    DeleteAgentRuntimeInput,
    DeleteAgentRuntimeOutput,
    DeleteApiKeyCredentialProviderInput,
    DeleteApiKeyCredentialProviderOutput,
    DeleteBrowserInput,
    DeleteBrowserOutput,
    DeleteBrowserProfileInput,
    DeleteBrowserProfileOutput,
    DeleteCodeInterpreterInput,
    DeleteCodeInterpreterOutput,
    DeleteConfigurationBundleInput,
    DeleteConfigurationBundleOutput,
    DeleteDatasetExamplesInput,
    DeleteDatasetExamplesOutput,
    DeleteDatasetInput,
    DeleteDatasetOutput,
    DeleteEvaluatorInput,
    DeleteEvaluatorOutput,
    DeleteGatewayInput,
    DeleteGatewayOutput,
    DeleteGatewayRuleInput,
    DeleteGatewayRuleOutput,
    DeleteGatewayTargetInput,
    DeleteGatewayTargetOutput,
    DeleteHarnessEndpointInput,
    DeleteHarnessEndpointOutput,
    DeleteHarnessInput,
    DeleteHarnessOutput,
    DeleteMemoryInput,
    DeleteMemoryOutput,
    DeleteOauth2CredentialProviderInput,
    DeleteOauth2CredentialProviderOutput,
    DeleteOnlineEvaluationConfigInput,
    DeleteOnlineEvaluationConfigOutput,
    DeletePaymentConnectorInput,
    DeletePaymentConnectorOutput,
    DeletePaymentCredentialProviderInput,
    DeletePaymentCredentialProviderOutput,
    DeletePaymentManagerInput,
    DeletePaymentManagerOutput,
    DeletePolicyEngineInput,
    DeletePolicyEngineOutput,
    DeletePolicyInput,
    DeletePolicyOutput,
    DeleteRegistryInput,
    DeleteRegistryOutput,
    DeleteRegistryRecordInput,
    DeleteRegistryRecordOutput,
    DeleteResourcePolicyInput,
    DeleteResourcePolicyOutput,
    DeleteWorkloadIdentityInput,
    DeleteWorkloadIdentityOutput,
    GetAgentRuntimeEndpointInput,
    GetAgentRuntimeEndpointOutput,
    GetAgentRuntimeInput,
    GetAgentRuntimeOutput,
    GetApiKeyCredentialProviderInput,
    GetApiKeyCredentialProviderOutput,
    GetBrowserInput,
    GetBrowserOutput,
    GetBrowserProfileInput,
    GetBrowserProfileOutput,
    GetCodeInterpreterInput,
    GetCodeInterpreterOutput,
    GetConfigurationBundleInput,
    GetConfigurationBundleOutput,
    GetConfigurationBundleVersionInput,
    GetConfigurationBundleVersionOutput,
    GetDatasetInput,
    GetDatasetOutput,
    GetEvaluatorInput,
    GetEvaluatorOutput,
    GetGatewayInput,
    GetGatewayOutput,
    GetGatewayRuleInput,
    GetGatewayRuleOutput,
    GetGatewayTargetInput,
    GetGatewayTargetOutput,
    GetHarnessEndpointInput,
    GetHarnessEndpointOutput,
    GetHarnessInput,
    GetHarnessOutput,
    GetMemoryInput,
    GetMemoryOutput,
    GetOauth2CredentialProviderInput,
    GetOauth2CredentialProviderOutput,
    GetOnlineEvaluationConfigInput,
    GetOnlineEvaluationConfigOutput,
    GetPaymentConnectorInput,
    GetPaymentConnectorOutput,
    GetPaymentCredentialProviderInput,
    GetPaymentCredentialProviderOutput,
    GetPaymentManagerInput,
    GetPaymentManagerOutput,
    GetPolicyEngineInput,
    GetPolicyEngineOutput,
    GetPolicyEngineSummaryInput,
    GetPolicyEngineSummaryOutput,
    GetPolicyGenerationInput,
    GetPolicyGenerationOutput,
    GetPolicyGenerationSummaryInput,
    GetPolicyGenerationSummaryOutput,
    GetPolicyInput,
    GetPolicyOutput,
    GetPolicySummaryInput,
    GetPolicySummaryOutput,
    GetRegistryInput,
    GetRegistryOutput,
    GetRegistryRecordInput,
    GetRegistryRecordOutput,
    GetResourcePolicyInput,
    GetResourcePolicyOutput,
    GetTokenVaultInput,
    GetTokenVaultOutput,
    GetWorkloadIdentityInput,
    GetWorkloadIdentityOutput,
    ListAgentRuntimeEndpointsInput,
    ListAgentRuntimeEndpointsOutput,
    ListAgentRuntimeVersionsInput,
    ListAgentRuntimeVersionsOutput,
    ListAgentRuntimesInput,
    ListAgentRuntimesOutput,
    ListApiKeyCredentialProvidersInput,
    ListApiKeyCredentialProvidersOutput,
    ListBrowserProfilesInput,
    ListBrowserProfilesOutput,
    ListBrowsersInput,
    ListBrowsersOutput,
    ListCodeInterpretersInput,
    ListCodeInterpretersOutput,
    ListConfigurationBundleVersionsInput,
    ListConfigurationBundleVersionsOutput,
    ListConfigurationBundlesInput,
    ListConfigurationBundlesOutput,
    ListDatasetExamplesInput,
    ListDatasetExamplesOutput,
    ListDatasetVersionsInput,
    ListDatasetVersionsOutput,
    ListDatasetsInput,
    ListDatasetsOutput,
    ListEvaluatorsInput,
    ListEvaluatorsOutput,
    ListGatewayRulesInput,
    ListGatewayRulesOutput,
    ListGatewayTargetsInput,
    ListGatewayTargetsOutput,
    ListGatewaysInput,
    ListGatewaysOutput,
    ListHarnessEndpointsInput,
    ListHarnessEndpointsOutput,
    ListHarnessVersionsInput,
    ListHarnessVersionsOutput,
    ListHarnessesInput,
    ListHarnessesOutput,
    ListMemoriesInput,
    ListMemoriesOutput,
    ListOauth2CredentialProvidersInput,
    ListOauth2CredentialProvidersOutput,
    ListOnlineEvaluationConfigsInput,
    ListOnlineEvaluationConfigsOutput,
    ListPaymentConnectorsInput,
    ListPaymentConnectorsOutput,
    ListPaymentCredentialProvidersInput,
    ListPaymentCredentialProvidersOutput,
    ListPaymentManagersInput,
    ListPaymentManagersOutput,
    ListPoliciesInput,
    ListPoliciesOutput,
    ListPolicyEngineSummariesInput,
    ListPolicyEngineSummariesOutput,
    ListPolicyEnginesInput,
    ListPolicyEnginesOutput,
    ListPolicyGenerationAssetsInput,
    ListPolicyGenerationAssetsOutput,
    ListPolicyGenerationSummariesInput,
    ListPolicyGenerationSummariesOutput,
    ListPolicyGenerationsInput,
    ListPolicyGenerationsOutput,
    ListPolicySummariesInput,
    ListPolicySummariesOutput,
    ListRegistriesInput,
    ListRegistriesOutput,
    ListRegistryRecordsInput,
    ListRegistryRecordsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    ListWorkloadIdentitiesInput,
    ListWorkloadIdentitiesOutput,
    PutResourcePolicyInput,
    PutResourcePolicyOutput,
    SetTokenVaultCMKInput,
    SetTokenVaultCMKOutput,
    StartPolicyGenerationInput,
    StartPolicyGenerationOutput,
    SubmitRegistryRecordForApprovalInput,
    SubmitRegistryRecordForApprovalOutput,
    SynchronizeGatewayTargetsInput,
    SynchronizeGatewayTargetsOutput,
    TagResourceInput,
    TagResourceOutput,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateAgentRuntimeEndpointInput,
    UpdateAgentRuntimeEndpointOutput,
    UpdateAgentRuntimeInput,
    UpdateAgentRuntimeOutput,
    UpdateApiKeyCredentialProviderInput,
    UpdateApiKeyCredentialProviderOutput,
    UpdateConfigurationBundleInput,
    UpdateConfigurationBundleOutput,
    UpdateDatasetExamplesInput,
    UpdateDatasetExamplesOutput,
    UpdateDatasetInput,
    UpdateDatasetOutput,
    UpdateEvaluatorInput,
    UpdateEvaluatorOutput,
    UpdateGatewayInput,
    UpdateGatewayOutput,
    UpdateGatewayRuleInput,
    UpdateGatewayRuleOutput,
    UpdateGatewayTargetInput,
    UpdateGatewayTargetOutput,
    UpdateHarnessEndpointInput,
    UpdateHarnessEndpointOutput,
    UpdateHarnessInput,
    UpdateHarnessOutput,
    UpdateMemoryInput,
    UpdateMemoryOutput,
    UpdateOauth2CredentialProviderInput,
    UpdateOauth2CredentialProviderOutput,
    UpdateOnlineEvaluationConfigInput,
    UpdateOnlineEvaluationConfigOutput,
    UpdatePaymentConnectorInput,
    UpdatePaymentConnectorOutput,
    UpdatePaymentCredentialProviderInput,
    UpdatePaymentCredentialProviderOutput,
    UpdatePaymentManagerInput,
    UpdatePaymentManagerOutput,
    UpdatePolicyEngineInput,
    UpdatePolicyEngineOutput,
    UpdatePolicyInput,
    UpdatePolicyOutput,
    UpdateRegistryInput,
    UpdateRegistryOutput,
    UpdateRegistryRecordInput,
    UpdateRegistryRecordOutput,
    UpdateRegistryRecordStatusInput,
    UpdateRegistryRecordStatusOutput,
    UpdateWorkloadIdentityInput,
    UpdateWorkloadIdentityOutput,
)


_ServiceInterceptor = Union[
    Interceptor[AddDatasetExamplesInput, AddDatasetExamplesOutput, Any, Any],
    Interceptor[CreateAgentRuntimeInput, CreateAgentRuntimeOutput, Any, Any],
    Interceptor[
        CreateAgentRuntimeEndpointInput, CreateAgentRuntimeEndpointOutput, Any, Any
    ],
    Interceptor[
        CreateApiKeyCredentialProviderInput,
        CreateApiKeyCredentialProviderOutput,
        Any,
        Any,
    ],
    Interceptor[CreateBrowserInput, CreateBrowserOutput, Any, Any],
    Interceptor[CreateBrowserProfileInput, CreateBrowserProfileOutput, Any, Any],
    Interceptor[CreateCodeInterpreterInput, CreateCodeInterpreterOutput, Any, Any],
    Interceptor[
        CreateConfigurationBundleInput, CreateConfigurationBundleOutput, Any, Any
    ],
    Interceptor[CreateDatasetInput, CreateDatasetOutput, Any, Any],
    Interceptor[CreateDatasetVersionInput, CreateDatasetVersionOutput, Any, Any],
    Interceptor[CreateEvaluatorInput, CreateEvaluatorOutput, Any, Any],
    Interceptor[CreateGatewayInput, CreateGatewayOutput, Any, Any],
    Interceptor[CreateGatewayRuleInput, CreateGatewayRuleOutput, Any, Any],
    Interceptor[CreateGatewayTargetInput, CreateGatewayTargetOutput, Any, Any],
    Interceptor[CreateHarnessInput, CreateHarnessOutput, Any, Any],
    Interceptor[CreateHarnessEndpointInput, CreateHarnessEndpointOutput, Any, Any],
    Interceptor[CreateMemoryInput, CreateMemoryOutput, Any, Any],
    Interceptor[
        CreateOauth2CredentialProviderInput,
        CreateOauth2CredentialProviderOutput,
        Any,
        Any,
    ],
    Interceptor[
        CreateOnlineEvaluationConfigInput, CreateOnlineEvaluationConfigOutput, Any, Any
    ],
    Interceptor[CreatePaymentConnectorInput, CreatePaymentConnectorOutput, Any, Any],
    Interceptor[
        CreatePaymentCredentialProviderInput,
        CreatePaymentCredentialProviderOutput,
        Any,
        Any,
    ],
    Interceptor[CreatePaymentManagerInput, CreatePaymentManagerOutput, Any, Any],
    Interceptor[CreatePolicyInput, CreatePolicyOutput, Any, Any],
    Interceptor[CreatePolicyEngineInput, CreatePolicyEngineOutput, Any, Any],
    Interceptor[CreateRegistryInput, CreateRegistryOutput, Any, Any],
    Interceptor[CreateRegistryRecordInput, CreateRegistryRecordOutput, Any, Any],
    Interceptor[CreateWorkloadIdentityInput, CreateWorkloadIdentityOutput, Any, Any],
    Interceptor[DeleteAgentRuntimeInput, DeleteAgentRuntimeOutput, Any, Any],
    Interceptor[
        DeleteAgentRuntimeEndpointInput, DeleteAgentRuntimeEndpointOutput, Any, Any
    ],
    Interceptor[
        DeleteApiKeyCredentialProviderInput,
        DeleteApiKeyCredentialProviderOutput,
        Any,
        Any,
    ],
    Interceptor[DeleteBrowserInput, DeleteBrowserOutput, Any, Any],
    Interceptor[DeleteBrowserProfileInput, DeleteBrowserProfileOutput, Any, Any],
    Interceptor[DeleteCodeInterpreterInput, DeleteCodeInterpreterOutput, Any, Any],
    Interceptor[
        DeleteConfigurationBundleInput, DeleteConfigurationBundleOutput, Any, Any
    ],
    Interceptor[DeleteDatasetInput, DeleteDatasetOutput, Any, Any],
    Interceptor[DeleteDatasetExamplesInput, DeleteDatasetExamplesOutput, Any, Any],
    Interceptor[DeleteEvaluatorInput, DeleteEvaluatorOutput, Any, Any],
    Interceptor[DeleteGatewayInput, DeleteGatewayOutput, Any, Any],
    Interceptor[DeleteGatewayRuleInput, DeleteGatewayRuleOutput, Any, Any],
    Interceptor[DeleteGatewayTargetInput, DeleteGatewayTargetOutput, Any, Any],
    Interceptor[DeleteHarnessInput, DeleteHarnessOutput, Any, Any],
    Interceptor[DeleteHarnessEndpointInput, DeleteHarnessEndpointOutput, Any, Any],
    Interceptor[DeleteMemoryInput, DeleteMemoryOutput, Any, Any],
    Interceptor[
        DeleteOauth2CredentialProviderInput,
        DeleteOauth2CredentialProviderOutput,
        Any,
        Any,
    ],
    Interceptor[
        DeleteOnlineEvaluationConfigInput, DeleteOnlineEvaluationConfigOutput, Any, Any
    ],
    Interceptor[DeletePaymentConnectorInput, DeletePaymentConnectorOutput, Any, Any],
    Interceptor[
        DeletePaymentCredentialProviderInput,
        DeletePaymentCredentialProviderOutput,
        Any,
        Any,
    ],
    Interceptor[DeletePaymentManagerInput, DeletePaymentManagerOutput, Any, Any],
    Interceptor[DeletePolicyInput, DeletePolicyOutput, Any, Any],
    Interceptor[DeletePolicyEngineInput, DeletePolicyEngineOutput, Any, Any],
    Interceptor[DeleteRegistryInput, DeleteRegistryOutput, Any, Any],
    Interceptor[DeleteRegistryRecordInput, DeleteRegistryRecordOutput, Any, Any],
    Interceptor[DeleteResourcePolicyInput, DeleteResourcePolicyOutput, Any, Any],
    Interceptor[DeleteWorkloadIdentityInput, DeleteWorkloadIdentityOutput, Any, Any],
    Interceptor[GetAgentRuntimeInput, GetAgentRuntimeOutput, Any, Any],
    Interceptor[GetAgentRuntimeEndpointInput, GetAgentRuntimeEndpointOutput, Any, Any],
    Interceptor[
        GetApiKeyCredentialProviderInput, GetApiKeyCredentialProviderOutput, Any, Any
    ],
    Interceptor[GetBrowserInput, GetBrowserOutput, Any, Any],
    Interceptor[GetBrowserProfileInput, GetBrowserProfileOutput, Any, Any],
    Interceptor[GetCodeInterpreterInput, GetCodeInterpreterOutput, Any, Any],
    Interceptor[GetConfigurationBundleInput, GetConfigurationBundleOutput, Any, Any],
    Interceptor[
        GetConfigurationBundleVersionInput,
        GetConfigurationBundleVersionOutput,
        Any,
        Any,
    ],
    Interceptor[GetDatasetInput, GetDatasetOutput, Any, Any],
    Interceptor[GetEvaluatorInput, GetEvaluatorOutput, Any, Any],
    Interceptor[GetGatewayInput, GetGatewayOutput, Any, Any],
    Interceptor[GetGatewayRuleInput, GetGatewayRuleOutput, Any, Any],
    Interceptor[GetGatewayTargetInput, GetGatewayTargetOutput, Any, Any],
    Interceptor[GetHarnessInput, GetHarnessOutput, Any, Any],
    Interceptor[GetHarnessEndpointInput, GetHarnessEndpointOutput, Any, Any],
    Interceptor[GetMemoryInput, GetMemoryOutput, Any, Any],
    Interceptor[
        GetOauth2CredentialProviderInput, GetOauth2CredentialProviderOutput, Any, Any
    ],
    Interceptor[
        GetOnlineEvaluationConfigInput, GetOnlineEvaluationConfigOutput, Any, Any
    ],
    Interceptor[GetPaymentConnectorInput, GetPaymentConnectorOutput, Any, Any],
    Interceptor[
        GetPaymentCredentialProviderInput, GetPaymentCredentialProviderOutput, Any, Any
    ],
    Interceptor[GetPaymentManagerInput, GetPaymentManagerOutput, Any, Any],
    Interceptor[GetPolicyInput, GetPolicyOutput, Any, Any],
    Interceptor[GetPolicyEngineInput, GetPolicyEngineOutput, Any, Any],
    Interceptor[GetPolicyEngineSummaryInput, GetPolicyEngineSummaryOutput, Any, Any],
    Interceptor[GetPolicyGenerationInput, GetPolicyGenerationOutput, Any, Any],
    Interceptor[
        GetPolicyGenerationSummaryInput, GetPolicyGenerationSummaryOutput, Any, Any
    ],
    Interceptor[GetPolicySummaryInput, GetPolicySummaryOutput, Any, Any],
    Interceptor[GetRegistryInput, GetRegistryOutput, Any, Any],
    Interceptor[GetRegistryRecordInput, GetRegistryRecordOutput, Any, Any],
    Interceptor[GetResourcePolicyInput, GetResourcePolicyOutput, Any, Any],
    Interceptor[GetTokenVaultInput, GetTokenVaultOutput, Any, Any],
    Interceptor[GetWorkloadIdentityInput, GetWorkloadIdentityOutput, Any, Any],
    Interceptor[
        ListAgentRuntimeEndpointsInput, ListAgentRuntimeEndpointsOutput, Any, Any
    ],
    Interceptor[ListAgentRuntimesInput, ListAgentRuntimesOutput, Any, Any],
    Interceptor[
        ListAgentRuntimeVersionsInput, ListAgentRuntimeVersionsOutput, Any, Any
    ],
    Interceptor[
        ListApiKeyCredentialProvidersInput,
        ListApiKeyCredentialProvidersOutput,
        Any,
        Any,
    ],
    Interceptor[ListBrowserProfilesInput, ListBrowserProfilesOutput, Any, Any],
    Interceptor[ListBrowsersInput, ListBrowsersOutput, Any, Any],
    Interceptor[ListCodeInterpretersInput, ListCodeInterpretersOutput, Any, Any],
    Interceptor[
        ListConfigurationBundlesInput, ListConfigurationBundlesOutput, Any, Any
    ],
    Interceptor[
        ListConfigurationBundleVersionsInput,
        ListConfigurationBundleVersionsOutput,
        Any,
        Any,
    ],
    Interceptor[ListDatasetExamplesInput, ListDatasetExamplesOutput, Any, Any],
    Interceptor[ListDatasetsInput, ListDatasetsOutput, Any, Any],
    Interceptor[ListDatasetVersionsInput, ListDatasetVersionsOutput, Any, Any],
    Interceptor[ListEvaluatorsInput, ListEvaluatorsOutput, Any, Any],
    Interceptor[ListGatewayRulesInput, ListGatewayRulesOutput, Any, Any],
    Interceptor[ListGatewaysInput, ListGatewaysOutput, Any, Any],
    Interceptor[ListGatewayTargetsInput, ListGatewayTargetsOutput, Any, Any],
    Interceptor[ListHarnessEndpointsInput, ListHarnessEndpointsOutput, Any, Any],
    Interceptor[ListHarnessesInput, ListHarnessesOutput, Any, Any],
    Interceptor[ListHarnessVersionsInput, ListHarnessVersionsOutput, Any, Any],
    Interceptor[ListMemoriesInput, ListMemoriesOutput, Any, Any],
    Interceptor[
        ListOauth2CredentialProvidersInput,
        ListOauth2CredentialProvidersOutput,
        Any,
        Any,
    ],
    Interceptor[
        ListOnlineEvaluationConfigsInput, ListOnlineEvaluationConfigsOutput, Any, Any
    ],
    Interceptor[ListPaymentConnectorsInput, ListPaymentConnectorsOutput, Any, Any],
    Interceptor[
        ListPaymentCredentialProvidersInput,
        ListPaymentCredentialProvidersOutput,
        Any,
        Any,
    ],
    Interceptor[ListPaymentManagersInput, ListPaymentManagersOutput, Any, Any],
    Interceptor[ListPoliciesInput, ListPoliciesOutput, Any, Any],
    Interceptor[ListPolicyEnginesInput, ListPolicyEnginesOutput, Any, Any],
    Interceptor[
        ListPolicyEngineSummariesInput, ListPolicyEngineSummariesOutput, Any, Any
    ],
    Interceptor[
        ListPolicyGenerationAssetsInput, ListPolicyGenerationAssetsOutput, Any, Any
    ],
    Interceptor[ListPolicyGenerationsInput, ListPolicyGenerationsOutput, Any, Any],
    Interceptor[
        ListPolicyGenerationSummariesInput,
        ListPolicyGenerationSummariesOutput,
        Any,
        Any,
    ],
    Interceptor[ListPolicySummariesInput, ListPolicySummariesOutput, Any, Any],
    Interceptor[ListRegistriesInput, ListRegistriesOutput, Any, Any],
    Interceptor[ListRegistryRecordsInput, ListRegistryRecordsOutput, Any, Any],
    Interceptor[ListTagsForResourceInput, ListTagsForResourceOutput, Any, Any],
    Interceptor[ListWorkloadIdentitiesInput, ListWorkloadIdentitiesOutput, Any, Any],
    Interceptor[PutResourcePolicyInput, PutResourcePolicyOutput, Any, Any],
    Interceptor[SetTokenVaultCMKInput, SetTokenVaultCMKOutput, Any, Any],
    Interceptor[StartPolicyGenerationInput, StartPolicyGenerationOutput, Any, Any],
    Interceptor[
        SubmitRegistryRecordForApprovalInput,
        SubmitRegistryRecordForApprovalOutput,
        Any,
        Any,
    ],
    Interceptor[
        SynchronizeGatewayTargetsInput, SynchronizeGatewayTargetsOutput, Any, Any
    ],
    Interceptor[TagResourceInput, TagResourceOutput, Any, Any],
    Interceptor[UntagResourceInput, UntagResourceOutput, Any, Any],
    Interceptor[UpdateAgentRuntimeInput, UpdateAgentRuntimeOutput, Any, Any],
    Interceptor[
        UpdateAgentRuntimeEndpointInput, UpdateAgentRuntimeEndpointOutput, Any, Any
    ],
    Interceptor[
        UpdateApiKeyCredentialProviderInput,
        UpdateApiKeyCredentialProviderOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateConfigurationBundleInput, UpdateConfigurationBundleOutput, Any, Any
    ],
    Interceptor[UpdateDatasetInput, UpdateDatasetOutput, Any, Any],
    Interceptor[UpdateDatasetExamplesInput, UpdateDatasetExamplesOutput, Any, Any],
    Interceptor[UpdateEvaluatorInput, UpdateEvaluatorOutput, Any, Any],
    Interceptor[UpdateGatewayInput, UpdateGatewayOutput, Any, Any],
    Interceptor[UpdateGatewayRuleInput, UpdateGatewayRuleOutput, Any, Any],
    Interceptor[UpdateGatewayTargetInput, UpdateGatewayTargetOutput, Any, Any],
    Interceptor[UpdateHarnessInput, UpdateHarnessOutput, Any, Any],
    Interceptor[UpdateHarnessEndpointInput, UpdateHarnessEndpointOutput, Any, Any],
    Interceptor[UpdateMemoryInput, UpdateMemoryOutput, Any, Any],
    Interceptor[
        UpdateOauth2CredentialProviderInput,
        UpdateOauth2CredentialProviderOutput,
        Any,
        Any,
    ],
    Interceptor[
        UpdateOnlineEvaluationConfigInput, UpdateOnlineEvaluationConfigOutput, Any, Any
    ],
    Interceptor[UpdatePaymentConnectorInput, UpdatePaymentConnectorOutput, Any, Any],
    Interceptor[
        UpdatePaymentCredentialProviderInput,
        UpdatePaymentCredentialProviderOutput,
        Any,
        Any,
    ],
    Interceptor[UpdatePaymentManagerInput, UpdatePaymentManagerOutput, Any, Any],
    Interceptor[UpdatePolicyInput, UpdatePolicyOutput, Any, Any],
    Interceptor[UpdatePolicyEngineInput, UpdatePolicyEngineOutput, Any, Any],
    Interceptor[UpdateRegistryInput, UpdateRegistryOutput, Any, Any],
    Interceptor[UpdateRegistryRecordInput, UpdateRegistryRecordOutput, Any, Any],
    Interceptor[
        UpdateRegistryRecordStatusInput, UpdateRegistryRecordStatusOutput, Any, Any
    ],
    Interceptor[UpdateWorkloadIdentityInput, UpdateWorkloadIdentityOutput, Any, Any],
]


@dataclass(init=False)
class Config:
    """Configuration for Bedrock AgentCore Control."""

    auth_scheme_resolver: HTTPAuthSchemeResolver
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]]
    """A map of auth scheme ids to auth schemes."""

    aws_access_key_id: str | None
    """The identifier for a secret access key."""

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    )
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    aws_secret_access_key: str | None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None
    """An access key ID that identifies temporary security credentials."""

    endpoint_resolver: EndpointResolver
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    endpoint_uri: str | URI | None
    """A static URI to route requests to."""

    http_request_config: HTTPRequestConfiguration | None
    """Configuration for individual HTTP requests."""

    interceptors: list[_ServiceInterceptor]
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    protocol: ClientProtocol[Any, Any] | None
    """The protocol to serialize and deserialize requests with."""

    region: str | None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    retry_strategy: RetryStrategy | RetryStrategyOptions | None
    """
    The retry strategy or options for configuring retry behavior. Can be
    either a configured RetryStrategy or RetryStrategyOptions to create one.
    """

    sdk_ua_app_id: str | None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    transport: ClientTransport[Any, Any] | None
    """The transport to use to send requests (e.g. an HTTP client)."""

    user_agent_extra: str | None
    """Additional suffix to be added to the User-Agent header."""

    def __init__(
        self,
        *,
        auth_scheme_resolver: HTTPAuthSchemeResolver | None = None,
        auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None,
        aws_access_key_id: str | None = None,
        aws_credentials_identity_resolver: IdentityResolver[
            AWSCredentialsIdentity, AWSIdentityProperties
        ]
        | None = None,
        aws_secret_access_key: str | None = None,
        aws_session_token: str | None = None,
        endpoint_resolver: EndpointResolver | None = None,
        endpoint_uri: str | URI | None = None,
        http_request_config: HTTPRequestConfiguration | None = None,
        interceptors: list[_ServiceInterceptor] | None = None,
        protocol: ClientProtocol[Any, Any] | None = None,
        region: str | None = None,
        retry_strategy: RetryStrategy | RetryStrategyOptions | None = None,
        sdk_ua_app_id: str | None = None,
        transport: ClientTransport[Any, Any] | None = None,
        user_agent_extra: str | None = None,
    ):
        self.auth_scheme_resolver = auth_scheme_resolver or HTTPAuthSchemeResolver()
        self.auth_schemes = auth_schemes or {
            ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="bedrock-agentcore")
        }
        self.aws_access_key_id = aws_access_key_id
        self.aws_credentials_identity_resolver = aws_credentials_identity_resolver
        self.aws_secret_access_key = aws_secret_access_key
        self.aws_session_token = aws_session_token
        self.endpoint_resolver = endpoint_resolver or StandardRegionalEndpointsResolver(
            endpoint_prefix="bedrock-agentcore-control"
        )
        self.endpoint_uri = endpoint_uri
        self.http_request_config = http_request_config
        self.interceptors = interceptors or []
        self.protocol = protocol or RestJsonClientProtocol(
            _SCHEMA_AMAZON_BEDROCK_AGENT_CORE_CONTROL
        )
        self.region = region
        self.retry_strategy = retry_strategy
        self.sdk_ua_app_id = sdk_ua_app_id
        self.transport = transport or AIOHTTPClient()
        self.user_agent_extra = user_agent_extra

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Sets the implementation of an auth scheme.

        Using this method ensures the correct key is used.

        Args:
            scheme:
                The auth scheme to add.
        """
        self.auth_schemes[scheme.scheme_id] = scheme


Plugin: TypeAlias = Callable[[Config], None]
"""A callable that allows customizing the config object on each request."""
