# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging
from typing import Any, TYPE_CHECKING
import warnings

from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.eventstream import DuplexEventStream
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.plugins import user_agent_plugin

from .config import Config, Plugin
from .models import (
    DELETE_SESSION,
    DeleteSessionInput,
    DeleteSessionOutput,
    GET_SESSION,
    GetSessionInput,
    GetSessionOutput,
    PUT_SESSION,
    PutSessionInput,
    PutSessionOutput,
    RECOGNIZE_TEXT,
    RECOGNIZE_UTTERANCE,
    RecognizeTextInput,
    RecognizeTextOutput,
    RecognizeUtteranceInput,
    RecognizeUtteranceOutput,
    START_CONVERSATION,
    StartConversationInput,
    StartConversationOutput,
    StartConversationRequestEventStream,
    StartConversationResponseEventStream,
    _StartConversationResponseEventStreamDeserializer,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncLexRuntimeV2Client:
    """
    This section contains documentation for the Amazon Lex V2 Runtime V2 API
    operations.
    """

    def __init__(
        self, config: Config | None = None, plugins: list[Plugin] | None = None
    ):
        """
        Constructor for `AsyncLexRuntimeV2Client`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables that modify the configuration dynamically. These
                can be used to set defaults, for example.
        """
        self._config = config or Config()

        client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]
        if plugins:
            client_plugins.extend(plugins)

        for plugin in client_plugins:
            plugin(self._config)

        self._retry_strategy_resolver = RetryStrategyResolver()

    async def delete_session(
        self, input: DeleteSessionInput, plugins: list[Plugin] | None = None
    ) -> DeleteSessionOutput:
        """
        Removes session information for a specified bot, alias, and user ID.

        You can use this operation to restart a conversation with a bot. When
        you remove a session, the entire history of the session is removed so
        that you can start again.

        You don't need to delete a session. Sessions have a time limit and will
        expire. Set the session time limit when you create the bot. The default
        is 5 minutes, but you can specify anything between 1 minute and 24
        hours.

        If you specify a bot or alias ID that doesn't exist, you receive a
        `BadRequestException.`

        If the locale doesn't exist in the bot, or if the locale hasn't been
        enables for the alias, you receive a `BadRequestException`.

        Args:
            input:
                An instance of `DeleteSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteSessionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=DELETE_SESSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_session(
        self, input: GetSessionInput, plugins: list[Plugin] | None = None
    ) -> GetSessionOutput:
        """
        Returns session information for a specified bot, alias, and user.

        For example, you can use this operation to retrieve session information
        for a user that has left a long-running session in use.

        If the bot, alias, or session identifier doesn't exist, Amazon Lex V2
        returns a `BadRequestException`. If the locale doesn't exist or is not
        enabled for the alias, you receive a `BadRequestException`.

        Args:
            input:
                An instance of `GetSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetSessionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=GET_SESSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def put_session(
        self, input: PutSessionInput, plugins: list[Plugin] | None = None
    ) -> PutSessionOutput:
        """
        Creates a new session or modifies an existing session with an Amazon Lex
        V2 bot. Use this operation to enable your application to set the state
        of the bot.

        Args:
            input:
                An instance of `PutSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutSessionOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=PUT_SESSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def recognize_text(
        self, input: RecognizeTextInput, plugins: list[Plugin] | None = None
    ) -> RecognizeTextOutput:
        """
        Sends user input to Amazon Lex V2. Client applications use this API to
        send requests to Amazon Lex V2 at runtime. Amazon Lex V2 then interprets
        the user input using the machine learning model that it build for the
        bot.

        In response, Amazon Lex V2 returns the next message to convey to the
        user and an optional response card to display.

        If the optional post-fulfillment response is specified, the messages are
        returned as follows. For more information, see
        [PostFulfillmentStatusSpecification](https://docs.aws.amazon.com/lexv2/latest/dg/API_PostFulfillmentStatusSpecification.html).

        - **Success message** - Returned if the Lambda function completes
          successfully and the intent state is fulfilled or ready fulfillment if
          the message is present.

        - **Failed message** - The failed message is returned if the Lambda
          function throws an exception or if the Lambda function returns a
          failed intent state without a message.

        - **Timeout message** - If you don't configure a timeout message and a
          timeout, and the Lambda function doesn't return within 30 seconds,
          the timeout message is returned. If you configure a timeout, the
          timeout message is returned when the period times out.

        For more information, see [Completion
        message](https://docs.aws.amazon.com/lexv2/latest/dg/streaming-progress.html#progress-complete.html).

        Args:
            input:
                An instance of `RecognizeTextInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RecognizeTextOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=RECOGNIZE_TEXT,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def recognize_utterance(
        self, input: RecognizeUtteranceInput, plugins: list[Plugin] | None = None
    ) -> RecognizeUtteranceOutput:
        """
        Sends user input to Amazon Lex V2. You can send text or speech. Clients
        use this API to send text and audio requests to Amazon Lex V2 at
        runtime. Amazon Lex V2 interprets the user input using the machine
        learning model built for the bot.

        The following request fields must be compressed with gzip and then
        base64 encoded before you send them to Amazon Lex V2.

        - requestAttributes

        - sessionState

        The following response fields are compressed using gzip and then base64
        encoded by Amazon Lex V2. Before you can use these fields, you must
        decode and decompress them.

        - inputTranscript

        - interpretations

        - messages

        - requestAttributes

        - sessionState

        The example contains a Java application that compresses and encodes a
        Java object to send to Amazon Lex V2, and a second that decodes and
        decompresses a response from Amazon Lex V2.

        If the optional post-fulfillment response is specified, the messages are
        returned as follows. For more information, see
        [PostFulfillmentStatusSpecification](https://docs.aws.amazon.com/lexv2/latest/dg/API_PostFulfillmentStatusSpecification.html).

        - **Success message** - Returned if the Lambda function completes
          successfully and the intent state is fulfilled or ready fulfillment if
          the message is present.

        - **Failed message** - The failed message is returned if the Lambda
          function throws an exception or if the Lambda function returns a
          failed intent state without a message.

        - **Timeout message** - If you don't configure a timeout message and a
          timeout, and the Lambda function doesn't return within 30 seconds,
          the timeout message is returned. If you configure a timeout, the
          timeout message is returned when the period times out.

        For more information, see [Completion
        message](https://docs.aws.amazon.com/lexv2/latest/dg/streaming-progress.html#progress-complete.html).

        Args:
            input:
                An instance of `RecognizeUtteranceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RecognizeUtteranceOutput`.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=RECOGNIZE_UTTERANCE,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def start_conversation(
        self, input: StartConversationInput, plugins: list[Plugin] | None = None
    ) -> DuplexEventStream[
        StartConversationRequestEventStream,
        StartConversationResponseEventStream,
        StartConversationOutput,
    ]:
        """
        Starts an HTTP/2 bidirectional event stream that enables you to send
        audio, text, or DTMF input in real time. After your application starts a
        conversation, users send input to Amazon Lex V2 as a stream of events.
        Amazon Lex V2 processes the incoming events and responds with streaming
        text or audio events.

        Audio input must be in the following format:
        `audio/lpcm sample-rate=8000 sample-size-bits=16 channel-count=1; is-big-endian=false`.

        If the optional post-fulfillment response is specified, the messages are
        returned as follows. For more information, see
        [PostFulfillmentStatusSpecification](https://docs.aws.amazon.com/lexv2/latest/dg/API_PostFulfillmentStatusSpecification.html).

        - **Success message** - Returned if the Lambda function completes
          successfully and the intent state is fulfilled or ready fulfillment if
          the message is present.

        - **Failed message** - The failed message is returned if the Lambda
          function throws an exception or if the Lambda function returns a
          failed intent state without a message.

        - **Timeout message** - If you don't configure a timeout message and a
          timeout, and the Lambda function doesn't return within 30 seconds,
          the timeout message is returned. If you configure a timeout, the
          timeout message is returned when the period times out.

        For more information, see [Completion
        message](https://docs.aws.amazon.com/lexv2/latest/dg/streaming-progress.html#progress-complete.html).

        If the optional update message is configured, it is played at the
        specified frequency while the Lambda function is running and the update
        message state is active. If the fulfillment update message is not
        active, the Lambda function runs with a 30 second timeout.

        For more information, see [Update
        message](https://docs.aws.amazon.com/lexv2/latest/dg/streaming-progress.html#progress-update.html)

        The `StartConversation` operation is supported only in the following
        SDKs:

        - [AWS SDK for
          C++](https://docs.aws.amazon.com/goto/SdkForCpp/runtime.lex.v2-2020-08-07/StartConversation)

        - [AWS SDK for Java
          V2](https://docs.aws.amazon.com/goto/SdkForJavaV2/runtime.lex.v2-2020-08-07/StartConversation)

        - [AWS SDK for Ruby
          V3](https://docs.aws.amazon.com/goto/SdkForRubyV3/runtime.lex.v2-2020-08-07/StartConversation)

        Args:
            input:
                An instance of `StartConversationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            A `DuplexEventStream` for bidirectional streaming.
        """
        operation_plugins: list[Plugin] = []
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError(
                "protocol and transport MUST be set on the config to make calls."
            )

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(protocol=config.protocol, transport=config.transport)
        call = ClientCall(
            input=input,
            operation=START_CONVERSATION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline.duplex_stream(
            call,
            StartConversationRequestEventStream,
            StartConversationResponseEventStream,
            _StartConversationResponseEventStreamDeserializer().deserialize,
        )


if TYPE_CHECKING:
    # Deprecated alias for backwards compatibility, to be removed.
    LexRuntimeV2Client = AsyncLexRuntimeV2Client


def __getattr__(name: str) -> Any:
    if name == "LexRuntimeV2Client":
        warnings.warn(
            "LexRuntimeV2Client is deprecated, use AsyncLexRuntimeV2Client instead. "
            "This alias will be removed in a future version.",
            DeprecationWarning,
            stacklevel=2,
        )
        return AsyncLexRuntimeV2Client
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
