# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
from typing import Any, Callable, TypeAlias, Union

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_aws_core.auth import SigV4AuthScheme
from smithy_aws_core.endpoints.standard_regional import (
    StandardRegionalEndpointsResolver,
)
from smithy_aws_core.identity import AWSCredentialsIdentity, AWSIdentityProperties
from smithy_core.aio.interfaces import ClientProtocol, ClientTransport, EndpointResolver
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.aio.interfaces.retries import RetryStrategy
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces import URI
from smithy_core.retries import RetryStrategyOptions
from smithy_core.shapes import ShapeID
from smithy_http.aio.crt import AWSCRTHTTPClient
from smithy_http.interfaces import HTTPRequestConfiguration

from ._private.schemas import (
    AMAZON_BEDROCK_AGENT_CORE as _SCHEMA_AMAZON_BEDROCK_AGENT_CORE,
)
from .auth import HTTPAuthSchemeResolver
from .models import (
    BatchCreateMemoryRecordsInput,
    BatchCreateMemoryRecordsOutput,
    BatchDeleteMemoryRecordsInput,
    BatchDeleteMemoryRecordsOutput,
    BatchUpdateMemoryRecordsInput,
    BatchUpdateMemoryRecordsOutput,
    CompleteResourceTokenAuthInput,
    CompleteResourceTokenAuthOutput,
    CreateABTestInput,
    CreateABTestOutput,
    CreateEventInput,
    CreateEventOutput,
    CreatePaymentInstrumentInput,
    CreatePaymentInstrumentOutput,
    CreatePaymentSessionInput,
    CreatePaymentSessionOutput,
    DeleteABTestInput,
    DeleteABTestOutput,
    DeleteBatchEvaluationInput,
    DeleteBatchEvaluationOutput,
    DeleteEventInput,
    DeleteEventOutput,
    DeleteMemoryRecordInput,
    DeleteMemoryRecordOutput,
    DeletePaymentInstrumentInput,
    DeletePaymentInstrumentOutput,
    DeletePaymentSessionInput,
    DeletePaymentSessionOutput,
    DeleteRecommendationInput,
    DeleteRecommendationOutput,
    EvaluateInput,
    EvaluateOutput,
    GetABTestInput,
    GetABTestOutput,
    GetAgentCardInput,
    GetAgentCardOutput,
    GetBatchEvaluationInput,
    GetBatchEvaluationOutput,
    GetBrowserSessionInput,
    GetBrowserSessionOutput,
    GetCodeInterpreterSessionInput,
    GetCodeInterpreterSessionOutput,
    GetEventInput,
    GetEventOutput,
    GetMemoryRecordInput,
    GetMemoryRecordOutput,
    GetPaymentInstrumentBalanceInput,
    GetPaymentInstrumentBalanceOutput,
    GetPaymentInstrumentInput,
    GetPaymentInstrumentOutput,
    GetPaymentSessionInput,
    GetPaymentSessionOutput,
    GetRecommendationInput,
    GetRecommendationOutput,
    GetResourceApiKeyInput,
    GetResourceApiKeyOutput,
    GetResourceOauth2TokenInput,
    GetResourceOauth2TokenOutput,
    GetResourcePaymentTokenInput,
    GetResourcePaymentTokenOutput,
    GetWorkloadAccessTokenForJWTInput,
    GetWorkloadAccessTokenForJWTOutput,
    GetWorkloadAccessTokenForUserIdInput,
    GetWorkloadAccessTokenForUserIdOutput,
    GetWorkloadAccessTokenInput,
    GetWorkloadAccessTokenOutput,
    InvokeAgentRuntimeCommandInput,
    InvokeAgentRuntimeCommandOutput,
    InvokeAgentRuntimeInput,
    InvokeAgentRuntimeOutput,
    InvokeBrowserInput,
    InvokeBrowserOutput,
    InvokeCodeInterpreterInput,
    InvokeCodeInterpreterOutput,
    InvokeHarnessInput,
    InvokeHarnessOutput,
    ListABTestsInput,
    ListABTestsOutput,
    ListActorsInput,
    ListActorsOutput,
    ListBatchEvaluationsInput,
    ListBatchEvaluationsOutput,
    ListBrowserSessionsInput,
    ListBrowserSessionsOutput,
    ListCodeInterpreterSessionsInput,
    ListCodeInterpreterSessionsOutput,
    ListEventsInput,
    ListEventsOutput,
    ListMemoryExtractionJobsInput,
    ListMemoryExtractionJobsOutput,
    ListMemoryRecordsInput,
    ListMemoryRecordsOutput,
    ListPaymentInstrumentsInput,
    ListPaymentInstrumentsOutput,
    ListPaymentSessionsInput,
    ListPaymentSessionsOutput,
    ListRecommendationsInput,
    ListRecommendationsOutput,
    ListSessionsInput,
    ListSessionsOutput,
    ProcessPaymentInput,
    ProcessPaymentOutput,
    RetrieveMemoryRecordsInput,
    RetrieveMemoryRecordsOutput,
    SaveBrowserSessionProfileInput,
    SaveBrowserSessionProfileOutput,
    SearchRegistryRecordsInput,
    SearchRegistryRecordsOutput,
    StartBatchEvaluationInput,
    StartBatchEvaluationOutput,
    StartBrowserSessionInput,
    StartBrowserSessionOutput,
    StartCodeInterpreterSessionInput,
    StartCodeInterpreterSessionOutput,
    StartMemoryExtractionJobInput,
    StartMemoryExtractionJobOutput,
    StartRecommendationInput,
    StartRecommendationOutput,
    StopBatchEvaluationInput,
    StopBatchEvaluationOutput,
    StopBrowserSessionInput,
    StopBrowserSessionOutput,
    StopCodeInterpreterSessionInput,
    StopCodeInterpreterSessionOutput,
    StopRuntimeSessionInput,
    StopRuntimeSessionOutput,
    UpdateABTestInput,
    UpdateABTestOutput,
    UpdateBrowserStreamInput,
    UpdateBrowserStreamOutput,
)


_ServiceInterceptor = Union[
    Interceptor[
        BatchCreateMemoryRecordsInput, BatchCreateMemoryRecordsOutput, Any, Any
    ],
    Interceptor[
        BatchDeleteMemoryRecordsInput, BatchDeleteMemoryRecordsOutput, Any, Any
    ],
    Interceptor[
        BatchUpdateMemoryRecordsInput, BatchUpdateMemoryRecordsOutput, Any, Any
    ],
    Interceptor[
        CompleteResourceTokenAuthInput, CompleteResourceTokenAuthOutput, Any, Any
    ],
    Interceptor[CreateABTestInput, CreateABTestOutput, Any, Any],
    Interceptor[CreateEventInput, CreateEventOutput, Any, Any],
    Interceptor[CreatePaymentInstrumentInput, CreatePaymentInstrumentOutput, Any, Any],
    Interceptor[CreatePaymentSessionInput, CreatePaymentSessionOutput, Any, Any],
    Interceptor[DeleteABTestInput, DeleteABTestOutput, Any, Any],
    Interceptor[DeleteBatchEvaluationInput, DeleteBatchEvaluationOutput, Any, Any],
    Interceptor[DeleteEventInput, DeleteEventOutput, Any, Any],
    Interceptor[DeleteMemoryRecordInput, DeleteMemoryRecordOutput, Any, Any],
    Interceptor[DeletePaymentInstrumentInput, DeletePaymentInstrumentOutput, Any, Any],
    Interceptor[DeletePaymentSessionInput, DeletePaymentSessionOutput, Any, Any],
    Interceptor[DeleteRecommendationInput, DeleteRecommendationOutput, Any, Any],
    Interceptor[EvaluateInput, EvaluateOutput, Any, Any],
    Interceptor[GetABTestInput, GetABTestOutput, Any, Any],
    Interceptor[GetAgentCardInput, GetAgentCardOutput, Any, Any],
    Interceptor[GetBatchEvaluationInput, GetBatchEvaluationOutput, Any, Any],
    Interceptor[GetBrowserSessionInput, GetBrowserSessionOutput, Any, Any],
    Interceptor[
        GetCodeInterpreterSessionInput, GetCodeInterpreterSessionOutput, Any, Any
    ],
    Interceptor[GetEventInput, GetEventOutput, Any, Any],
    Interceptor[GetMemoryRecordInput, GetMemoryRecordOutput, Any, Any],
    Interceptor[GetPaymentInstrumentInput, GetPaymentInstrumentOutput, Any, Any],
    Interceptor[
        GetPaymentInstrumentBalanceInput, GetPaymentInstrumentBalanceOutput, Any, Any
    ],
    Interceptor[GetPaymentSessionInput, GetPaymentSessionOutput, Any, Any],
    Interceptor[GetRecommendationInput, GetRecommendationOutput, Any, Any],
    Interceptor[GetResourceApiKeyInput, GetResourceApiKeyOutput, Any, Any],
    Interceptor[GetResourceOauth2TokenInput, GetResourceOauth2TokenOutput, Any, Any],
    Interceptor[GetResourcePaymentTokenInput, GetResourcePaymentTokenOutput, Any, Any],
    Interceptor[GetWorkloadAccessTokenInput, GetWorkloadAccessTokenOutput, Any, Any],
    Interceptor[
        GetWorkloadAccessTokenForJWTInput, GetWorkloadAccessTokenForJWTOutput, Any, Any
    ],
    Interceptor[
        GetWorkloadAccessTokenForUserIdInput,
        GetWorkloadAccessTokenForUserIdOutput,
        Any,
        Any,
    ],
    Interceptor[InvokeAgentRuntimeInput, InvokeAgentRuntimeOutput, Any, Any],
    Interceptor[
        InvokeAgentRuntimeCommandInput, InvokeAgentRuntimeCommandOutput, Any, Any
    ],
    Interceptor[InvokeBrowserInput, InvokeBrowserOutput, Any, Any],
    Interceptor[InvokeCodeInterpreterInput, InvokeCodeInterpreterOutput, Any, Any],
    Interceptor[InvokeHarnessInput, InvokeHarnessOutput, Any, Any],
    Interceptor[ListABTestsInput, ListABTestsOutput, Any, Any],
    Interceptor[ListActorsInput, ListActorsOutput, Any, Any],
    Interceptor[ListBatchEvaluationsInput, ListBatchEvaluationsOutput, Any, Any],
    Interceptor[ListBrowserSessionsInput, ListBrowserSessionsOutput, Any, Any],
    Interceptor[
        ListCodeInterpreterSessionsInput, ListCodeInterpreterSessionsOutput, Any, Any
    ],
    Interceptor[ListEventsInput, ListEventsOutput, Any, Any],
    Interceptor[
        ListMemoryExtractionJobsInput, ListMemoryExtractionJobsOutput, Any, Any
    ],
    Interceptor[ListMemoryRecordsInput, ListMemoryRecordsOutput, Any, Any],
    Interceptor[ListPaymentInstrumentsInput, ListPaymentInstrumentsOutput, Any, Any],
    Interceptor[ListPaymentSessionsInput, ListPaymentSessionsOutput, Any, Any],
    Interceptor[ListRecommendationsInput, ListRecommendationsOutput, Any, Any],
    Interceptor[ListSessionsInput, ListSessionsOutput, Any, Any],
    Interceptor[ProcessPaymentInput, ProcessPaymentOutput, Any, Any],
    Interceptor[RetrieveMemoryRecordsInput, RetrieveMemoryRecordsOutput, Any, Any],
    Interceptor[
        SaveBrowserSessionProfileInput, SaveBrowserSessionProfileOutput, Any, Any
    ],
    Interceptor[SearchRegistryRecordsInput, SearchRegistryRecordsOutput, Any, Any],
    Interceptor[StartBatchEvaluationInput, StartBatchEvaluationOutput, Any, Any],
    Interceptor[StartBrowserSessionInput, StartBrowserSessionOutput, Any, Any],
    Interceptor[
        StartCodeInterpreterSessionInput, StartCodeInterpreterSessionOutput, Any, Any
    ],
    Interceptor[
        StartMemoryExtractionJobInput, StartMemoryExtractionJobOutput, Any, Any
    ],
    Interceptor[StartRecommendationInput, StartRecommendationOutput, Any, Any],
    Interceptor[StopBatchEvaluationInput, StopBatchEvaluationOutput, Any, Any],
    Interceptor[StopBrowserSessionInput, StopBrowserSessionOutput, Any, Any],
    Interceptor[
        StopCodeInterpreterSessionInput, StopCodeInterpreterSessionOutput, Any, Any
    ],
    Interceptor[StopRuntimeSessionInput, StopRuntimeSessionOutput, Any, Any],
    Interceptor[UpdateABTestInput, UpdateABTestOutput, Any, Any],
    Interceptor[UpdateBrowserStreamInput, UpdateBrowserStreamOutput, Any, Any],
]


@dataclass(init=False)
class Config:
    """Configuration for Bedrock AgentCore."""

    auth_scheme_resolver: HTTPAuthSchemeResolver
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]]
    """A map of auth scheme ids to auth schemes."""

    aws_access_key_id: str | None
    """The identifier for a secret access key."""

    aws_credentials_identity_resolver: (
        IdentityResolver[AWSCredentialsIdentity, AWSIdentityProperties] | None
    )
    """Resolves AWS Credentials. Required for operations that use Sigv4 Auth."""

    aws_secret_access_key: str | None
    """A secret access key that can be used to sign requests."""

    aws_session_token: str | None
    """An access key ID that identifies temporary security credentials."""

    endpoint_resolver: EndpointResolver
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    endpoint_uri: str | URI | None
    """A static URI to route requests to."""

    http_request_config: HTTPRequestConfiguration | None
    """Configuration for individual HTTP requests."""

    interceptors: list[_ServiceInterceptor]
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    protocol: ClientProtocol[Any, Any] | None
    """The protocol to serialize and deserialize requests with."""

    region: str | None
    """
    The AWS region to connect to. The configured region is used to determine
    the service endpoint.
    """

    retry_strategy: RetryStrategy | RetryStrategyOptions | None
    """
    The retry strategy or options for configuring retry behavior. Can be
    either a configured RetryStrategy or RetryStrategyOptions to create one.
    """

    sdk_ua_app_id: str | None
    """
    A unique and opaque application ID that is appended to the User-Agent
    header.
    """

    transport: ClientTransport[Any, Any] | None
    """The transport to use to send requests (e.g. an HTTP client)."""

    user_agent_extra: str | None
    """Additional suffix to be added to the User-Agent header."""

    def __init__(
        self,
        *,
        auth_scheme_resolver: HTTPAuthSchemeResolver | None = None,
        auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None,
        aws_access_key_id: str | None = None,
        aws_credentials_identity_resolver: IdentityResolver[
            AWSCredentialsIdentity, AWSIdentityProperties
        ]
        | None = None,
        aws_secret_access_key: str | None = None,
        aws_session_token: str | None = None,
        endpoint_resolver: EndpointResolver | None = None,
        endpoint_uri: str | URI | None = None,
        http_request_config: HTTPRequestConfiguration | None = None,
        interceptors: list[_ServiceInterceptor] | None = None,
        protocol: ClientProtocol[Any, Any] | None = None,
        region: str | None = None,
        retry_strategy: RetryStrategy | RetryStrategyOptions | None = None,
        sdk_ua_app_id: str | None = None,
        transport: ClientTransport[Any, Any] | None = None,
        user_agent_extra: str | None = None,
    ):
        self.auth_scheme_resolver = auth_scheme_resolver or HTTPAuthSchemeResolver()
        self.auth_schemes = auth_schemes or {
            ShapeID("aws.auth#sigv4"): SigV4AuthScheme(service="bedrock-agentcore")
        }
        self.aws_access_key_id = aws_access_key_id
        self.aws_credentials_identity_resolver = aws_credentials_identity_resolver
        self.aws_secret_access_key = aws_secret_access_key
        self.aws_session_token = aws_session_token
        self.endpoint_resolver = endpoint_resolver or StandardRegionalEndpointsResolver(
            endpoint_prefix="bedrock-agentcore"
        )
        self.endpoint_uri = endpoint_uri
        self.http_request_config = http_request_config
        self.interceptors = interceptors or []
        self.protocol = protocol or RestJsonClientProtocol(
            _SCHEMA_AMAZON_BEDROCK_AGENT_CORE
        )
        self.region = region
        self.retry_strategy = retry_strategy
        self.sdk_ua_app_id = sdk_ua_app_id
        self.transport = transport or AWSCRTHTTPClient()
        self.user_agent_extra = user_agent_extra

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Sets the implementation of an auth scheme.

        Using this method ensures the correct key is used.

        Args:
            scheme:
                The auth scheme to add.
        """
        self.auth_schemes[scheme.scheme_id] = scheme


Plugin: TypeAlias = Callable[[Config], None]
"""A callable that allows customizing the config object on each request."""
